#+title: A meeting with the Pro Vice-Chancellor
#+FIRN_ORDER: 23

Author: Laura Ritchie

As a teacher, Peeragogy is a way of life for me, for my students, and
for those I come into contact with. However, introducing it to others
can be daunting and confusing. My methodology for an explanation of
interactions is to show by doing, and not only show, but include people
into the fold, so they experience it first hand. This case study
describes a meeting between the Pro Vice-Chancellor at my University,
myself, and three other people, two of whom were my guests from abroad.
So far it does not sound like Peeragogy, but like any meeting. It was
scheduled in an office to be a semi-formal meeting of introduction to my
superiors about Open Source Learning.

Pete is a final year student studying Instrumental & Vocal Teaching in
Music at the University of Chichester, and he knows both of my guests as
we all worked on a project in the previous academic year. This was a
flying visit for my guests and everyone thought it would be nice to say
hello in person, so I sent Pete a message to meet us before our meeting.
There were no other instructions, requirements, or explanations. When we
arrived to find Pete waiting, it was a jovial scene, with handshakes and
laughter. We all walked around the campus and when it came time for our
meeting, I said to Pete, "You have been a part of this, why don't you
come along?" There was no planned agenda, no script, nothing besides a
scheduled meeting time.

The four of us arrived at the office to meet with the Pro V-C and much
to his credit, he didn't question why one of my students was there
unannounced, but welcomed all of us. The Pro V-C asked most of the
questions, as he was the one being introduced to something new. My
guests, Pete, and I already work within a Peeragogical framework, but it
is fair to say that this concept is less prevalent and not the norm
across higher education contexts. The point of this particular meeting
was not to introduce Peeragogy, but Open Source Learning, which adds a
dimension to learning within an institution by extending beyond the
boundaries of discipline area, age, and physical setting.

In any institution people have responsibilities, and whenever a new
opportunity or idea presents itself, it is natural to discuss, sound it
out, and ask questions. That was the purpose of this meeting. The
interesting thing where Peeragogy is concerned is how the meeting
unfolded. It was not a meeting between four senior academics, but a
meeting between five people. A student joined us for that meeting and
played as active a role as any of the others present.

The exact detail of the content at this meeting is not important for
this case study, but some of the overall questions and how these were
answered by a demonstration of the underlying principles and unfolding
practices of Peeragogy are at the core of this example.

Peeragogy for me is a methodology that permeates the other aspects of
what I do both within and without teaching spaces. Open Source Learning
is something else that I do, which both encompasses and extends beyond
Peeragogy, and this meeting was instigated to introduce my Pro
Vice-Chancellor to the founder of the OSL Foundation, David Preston,
another professor visiting from California who also practices open
source learning, and myself, a co-founder of the OLS foundation.

Firstly, there was no sense of tension between those in the room. The
Professors, student, and Pro Vice-Chancellor were all as cogs in a
clock, working together to move forward. People sparked off one another
and hierarchies dissolved. There was no sense of 'hands up to speak',
and Pete spoke just as much as anyone else. This was also an organic
process. It was through the openness and receptivity of the Pro V-C that
he allowed and enabled himself to join an already working, organic body.
There was always respect for one another's experience, expertise,
viewpoints, and the relevance of an individual's contribution to the
discussion was valued. Pete could speak with as much authority and
conviction as the Professor of Architecture on co-learning and how
genuine learner-inquisitiveness enables autonomy. They explained
together, drawing upon one another's experience and perspectives to form
a more complete picture for our host.

The conversation went on, and one key question was: How does this help
the students, the learners? It is a very relevant question and one that
should be asked. As Pro V-C at a university, in a position of authority
where decisions about learning and teaching reside with your name on
them, it is so important to understand and really seek out all aspects
of opportunities, including the risks and benefits to all involved. In
short: What is the benefit to this over working within some other
defined or predetermined framework? The question is relevant beyond
educational settings, because in commerce, or in any interactive
situation there is always someone 'on the receiving end'. With Peeragogy
that boundary blurs between those people in a co-learning environment,
and with Open Source Learning the boundaries with the outside world also
dissolve.

These benefits were demonstrated within the meeting itself. We were five
people discussing a methodology, various projects, and possibilities. We
stepped beyond roles to work together in a productive, open, learning
environment. This is only possible when people in management positions,
and in this case on the senior management team, are willing to be
receptive to lecturers and students, who are then given the freedom and
respect to come to the table. The respect is essential as the
experience, skill, and perspective of a professor is inherently
different to that of a manager or a student, and each person has a
unique contribution to offer. Because one person has more or different
experience does not render another member of the group irrelevant. By
nature we need to learn from and with one another.

The individual skills within a specialism are valued and through an OSL
approach they are not at all undermined or threatened, but valued and
integral to the Peeragogical community that thrives within this
practice. Even at the table at that meeting were represented
Architecture, Music, History, English, and all still needed their
individually and meticulously developed specialist skills, which
prepared them for successful interactive co-learning. The Peeragogical
and Open Source Learning approaches develop a host of further skills
around communication, information gathering and research, collaboration,
and extend to develop confidence with using technology, presentation,
and dissemination to wider networks.

As a teacher, leader, and facilitator there was not a sense of giving
anything up to adopt a co-learning framework for the meeting. There was
no personal risk or degrading of my own value, instead it empowered
others and made the conversation and the interaction at that meeting
stronger.

We all left energised and interested in new possibilities to take
projects and relationships further. To understand the difference between
a Peeragogical, Open Sourced approach to learning and a more reactive
framework, consider the distance from there to here. In this case study,
five people came together and because of the shared outlook and
approach, we were all active in enacting solid, informed progress. How
many people could, without warning, ask a student to meet distinguished
guests and join them with the someone from the university's senior
management team, and not have any inhibitions? It is about transparency,
trust, building and sharing skills, and creating situations where
everyone finds value, where learning perpetuates and propagates. Looking
at it in those terms can illustrate the distance from 'there' to 'here'.
Afterwards Pete, the student amongst the academics, commented to me that
he wouldn't have been able to even show up at that meeting, let alone
speak if I didn't let him. In his words, 'That's a two-way respect right
there.'

