#+title: Adding Structure
#+FIRN_ORDER: 25

In the introduction to "Organizing a Learning Context", we remarked that
a "learning space" is /only potentially/ less structured than a
"course".  For example, a library tends to be highly structured, with
quiet rooms for reading, protocols for checking out books, a cataloging
and shelving system that allows people to find what they are looking
for, as well as rules that deter vandalism and theft. (Digital libraries
don't need to play by all the same rules, but are still structured.)

But more structure does not always lead to better learning. In a 2010
Forbes article titled, "The Classroom in 2020," George Kembel describes
a future in which "Tidy lectures will be supplanted by messy real-world
challenges." The Stanford School of Design, (or "d.school" -- which
Kemble co-founded and currently directs) is already well-known for its
open collaborative spaces, abundant supply of Post-It notes and markers,
and improvisational brainstorm activities -- almost the opposite of
traditional lecture-based learning.

One "unexpected benefit" of dealing with real-world challenges is that
we can change our approach as we go.  This is how it works in peer
learning: peers can decide on different structures not just once (say,
at the beginning of a course), but throughout the duration of their time
together. This way, they are never "stuck" with existing structures,
whether they be messy or clean. At least... that's the ideal.

In practice, "bottlenecks" frequently arise.  For example, in a digital
library context, there may be bottlenecks having to do with software
development, organizational resources, community good will, or access to
funding -- and probably all of the above.  In a didactic context, it may
be as simple as one person knowing something that others do not.

While we can't eliminate scarcity in one stroke, we can design
activities for peer learning that are "scarcity aware" and that help us
move in the direction of adaptive learning structures.

* Planning Peer Learning Activities
   :PROPERTIES:
   :CUSTOM_ID: planning-peer-learning-activities
   :END:

We begin with two simple questions:

- How do we select an appropriate learning activity?
- How do we go about creating a learning activity if we don't find an
  existing one?

"Planning a learning activity" should mean planning
an /effective/ learning activity, and in particular that means something
that people can and will engage with.  In short, an appropriate learning
activity may be one that you already do!  At the very least, current
activities can provide a "seed" for even more effective ones.

But when entering unfamiliar territory, it can be difficult to know
where to begin.  And remember the bottlenecks mentioned above?  When you
run into difficulty, ask yourself:
[[http://peeragogy.org/patterns-and-heuristics/][why is this hard?]] 
You might try adapting
[[http://learnpythonthehardway.org/book/intro.html#comment-409972596][Zed
Shaw's task-management trick]], and make a list of limiting factors,
obstacles, etc., then cross off those which you can find a strategy to
deal with (add an annotation as to why).  For example, you might decide
to overcome your lack of knowledge in some area by hiring a tutor or
expert consultant, or by putting in the hours learning things the hard
way (Zed would particularly approve of this choice).  If you can't find
a strategy to deal with some issue, presumably you can table it, at
least for a while.

Strategic thinking like this works well for one person. What about when
you're planning activities for someone else?  Here you have to be
careful: remember, this is peer learning, not traditional "teaching" or
"curriculum design".  The first rule of thumb for /peer learning/ is:
don't plan activities for others unless you plan to to take part as a
fully engaged participant.  Otherwise, you might be more interested in
the literature on /collaborative learning/, which has often been
deployed to good effect within a standard pedagogical context (see
e.g. Bruffee [1]).  In a peer learning setting, everyone will have
something to say about  "what do you need to do" and "why is it hard,"
and everyone is likely to be interested in everyone else's answer as
well as their own.

Furthermore, different participants will be doing different things, and
these will be "hard" for different reasons. Part of /your/ job is to try
to make sure that not only are all of the relevant roles covered, but
that the participants involved are getting enough support.

* One scenario: building activities for the Peeragogy Handbook
   :PROPERTIES:
   :CUSTOM_ID: one-scenario-building-activities-for-the-peeragogy-handbook
   :END:

Adding a bunch of activities to the handbook won't solve all of our
usability issues, but more activities would help.  We can think about
each article or section from this perspective:

1. When looking at this piece of text, what type of knowledge are we
   (and the reader) trying to gain?   Technical skills, or abstract
   skills?  What's the point?

2. What's difficult here?  What might be difficult for someone else?

3. What learning activity recipes or models might be appropriate? (See
   e.g. [2], [3].)

4. What customizations do we need for this particular application?

*/ /As a quick example: designing a learning activity for the current
page*

1. /We want to be able to come up with effective learning activities to
   accompany a "how to" article for peer learners/

2. /It might be difficult to "unplug" from all the reading and writing
   that we're habituated to doing./

3. /But there are lots and lots of ways to learn./

4. /Therefore, the proposed handbook activity is to simply step away
   from the handbook for a while./

5. *Look for some examples of peer learning in everyday life.  When
   you've gained an insight about peer learning from your own
   experience, come back and create a related activity to accompany
   another handbook page!*

* References
   :PROPERTIES:
   :CUSTOM_ID: references
   :END:

1. Bruffee, Kenneth A. (1984). "Collaborative learning and the
   conversation of mankind." /College English/ 46.7, 635-652

2. [[http://www.kstoolkit.org/KS+Methods][KS ToolKit]] from
   kstoolkit.org.

3. [[http://serc.carleton.edu/NAGTWorkshops/coursedesign/tutorial/strategies.html][Designing
   Effective and Innovative Sources]] (particularly the section on
   "Teaching Strategies for Actively Engaging Students in the
   Classroom")

