#+TITLE: Coworking Story
#+FIRN_ORDER: 32

The board of a housing association needs to set a strategy that takes
account of major changes in legislation, the UK benefits system and the
availability of long term construction loans. Julian, eager to make use
of his new-found peeragogical insights suggests an approach where
individuals research specific factors and the team work together to draw
out themes and strategic options. In the beginning, he proposes that
each board member researches an area of specific knowledge or interest.

Jim, the Chairman, identifies questions he wants to ask the Chairs of
other Housing Associations. Pamela (a lawyer) agrees to do an analysis
of the relevant legislation. Clare, the CEO, plans out a series of
meetings with the local councils in the boroughs of interest to
understand their reactions to the changes from central government.
Jenny, the operations director, starts modelling the impact on occupancy
from new benefits rules. Colin, the development director, re-purposes
existing work on options for development sites to reflect different
housing mixes on each site. Malcolm, the finance director, prepares a
briefing on the new treasury landscape and the changing positions of
major lenders.

Each member of the board documents their research in a private wiki.
Julian facilitates some synchronous and asynchronous discussion to draw
out themes in each area and map across the areas of interest. Malcolm,
the FD, adapts his financial models to take different options as
parameters. Clare refines the themes into a set of strategic options for
the association, with associated financial modelling provided by
Malcolm. Individual board members explore the options asynchronously
before convening for an all-day meeting to confirm the strategy.

/demo/
