#+TITLE: License
#+FIRN_ORDER: 42

These materials are made available under the terms of
[[http://creativecommons.org/publicdomain/zero/1.0/][Creative Commons 0
copyright waiver]] instead of a "traditional" copyleft license. We the
undersigned agree to the following, wherein "this work" refers to "The
Peeragogy Handbook" and all other content posted on
[[http://peeragogy.org][peeragogy.org]] or the original collaboratory
site, [[http://socialmediaclassroom.com/host/peeragogy]].

*I hereby waive all copyright and related or neighboring rights together
with all associated claims and causes of action with respect to this
work to the extent possible under the law.*

Signed:

- Bryan Alexander
- Paul Allison
- Elisa Armendáriz
- Régis Barondeau
- [[https://www.linkedin.com/in/dougbreitbart][Doug Breitbart]]
- George Brett
- Suz Burroughs
- [[http://metameso.org/~joe][Joseph Corneli]]
- Jay Cross
- Charles Jeffrey Danoff
- Analua Dutka-Chirichetti
- Julian Elve
- María Fernanda Arenas
- James Folkestad
- John Graves
- Kathy Gill
- Matthew Herschler
- Gigi Johnson
- Anna Keune
- John Laing
- Kyle Larson
- Roland Legrand
- Amanda Lyons
- Dorotea Mar
- Christopher Tillman Neal
- Ted Newcomb
- Stephanie Parker
- Miguel Ángel Pérez Álvarez
- [[http://piercepress.com][Charlotte Pierce]]
- David Preston
- Howard Rheingold
- Paola Ricaurte
- [[http://www.lauraritchie.com/][Laura Ritchie]]
- Verena Roberts
- Stephanie Schipper
- Lisa Snow MacDonald
- Fabrizio Terzi
- Geoff Walker

Note that this waiver does not apply to other works by the above
authors, including works linked to from
[[http://peeragogy.org][peeragogy.org]].

Future contributors: Note also that we will require a similar copyright
waiver agreement. That said, the waiver also means that you are free to
do essentially whatever you like with the content in your own work! Have
fun!

*** How we came to this decision
    :PROPERTIES:
    :CUSTOM_ID: how-we-came-to-this-decision
    :END:

These Creative Commons license options were proposed by various members
of the community:

- /CC Zero/ - public domain; no restrictions for downstream users
- /CC By-SA/ - requires downstream users to include attribution and to
  license their work in the same way
- /CC By-SA-NC/ - requires downstream users to include attribution, to
  license their work in the same way and disallows any commercial use of
  the content

After a brief discussion, no one was in favor of restricting downstream
users, so we decided to go with CC0. We agreed that we would get enough
"credit" by having our names on
[[http://peeragogy.org/][peeragogy.org]]. In connection with this
discussion, we agreed that we would work on ways to explicitly build
"reusability" into the handbook content.

