#+TITLE: Polling for ideas
#+FIRN_ORDER: 52

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

Polling for Ideas can happen at many junctures in a peer learning
experience. We could poll for ideas like "what's missing?", "who might
like to join our group?", and "what are the right tools and resources
for us to use at this point?"

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

We recognize that we don't always know the answers in advance --
particularly if we're trying to come up with an answer that satisfies
other people.

* Solution:
     :PROPERTIES:
     :CUSTOM_ID: solution
     :END:

Others might have an important or useful idea. Even if all you can
supply is the question and a context for discussion, they may be willing
to contribute these answers.

* Example:
     :PROPERTIES:
     :CUSTOM_ID: example
     :END:

Near the start of the project, Howard suggested that we use the forum
categories he set up, but opened the floor to other ideas, in this way:
"At the beginning, until we all know the ropes well enough to understand
when to create a new discussion forum topic and when to add to an
existing one, let's talk in this topic thread about what else we want to
discuss and I will start new topic threads when necessary."

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

In the Peeragogy in Action Google+ community, and in our earlier Social
Media Classroom forum, both of which have been open to any suggestion at
all, we've many different ideas appear and then roll by without being
catalogued. When you have too much data, it can be necessary to take
separate steps to organize it. At the other end of the spectrum, people
don't always respond to surveys, and you can end up with less data than
you'd like.

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

We've considered asking new members of the project to do an "entry
survey" as part of joining the project, to describe their aims and
understanding of what they hope to contribute. This could establish a
context of contribution, and help new members to feel like full "peers".
