#+TITLE: Stasis
#+FIRN_ORDER: 56

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

Actually, living beings are never really in stasis. It just sometimes
feels that way. Other anti-patterns like
[[http://peeragogy.org/antipatterns/isolation/][Isolation]] and
[[http://peeragogy.org/antipatterns/navel-gazing/][Navel Gazing]] have
described different aspects of the experience of feeling like one is in
stasis. Typically, what is happening in such a case is that one or more
dimensions of life are moving very slowly.

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

When important things are moving slowly or not at all, and when they are
mostly or entirely out of your control, this can be frustrating.

* (Bogus) Solution:
     :PROPERTIES:
     :CUSTOM_ID: bogus-solution
     :END:

It's tempting in this case just to be upset and to feel disempowered.

* Example:
     :PROPERTIES:
     :CUSTOM_ID: example
     :END:

We were not able to get programming support to improve the first version
of the Social Media Classroom, since all developer energy was allocated
to the next version of the system. It becomes frustrating if a specific
small feature is desired, but unavailable.

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

Of course, it's very unpleasant to be frustrated all the time. The hint
to pick up is that there is always some dimension on which you can make
progress. It might not be the same one you've been working on -- you
might have "over-harvested" that niche (see
[[http://peeragogy.org/patterns-usecases/patterns-and-heuristics/carrying-capacity/][Carrying
Capacity]]).

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

We're working on a new handbook chapter about the relationship of open
source software and peeragogy. This will include some more specific
ideas about ways of making change.
