#+TITLE: Summaries
#+FIRN_ORDER: 3

* Motivation
    :PROPERTIES:
    :CUSTOM_ID: motivation
    :END:

You might wonder why we're doing this project -- what we hope to get out
of it as volunteers, and how we think what we're doing can make a
positive difference in the world. Have a look at this chapter if you,
too, are thinking about getting involved in peeragogy, or wondering how
peeragogy can help you accelerate your learning projects.

** Case Study: 5PH1NX.
     :PROPERTIES:
     :CUSTOM_ID: case-study-5ph1nx.
     :END:

This example focuses on the interrelationship of pedagogy and peeragogy
in a high school English class, when students are encouraged to find and
share creative ways to learn. Explore this case study for ideas and
encouragement for your own learning adventures.

* Peeragogy in Practice
    :PROPERTIES:
    :CUSTOM_ID: peeragogy-in-practice
    :END:

Here we describe some of the interaction patterns that we've encountered
time and time again in the Peeragogy project. You can use the ideas in
this chapter as a starter-kit for your own experiments with peeragogy
right away. Sharing -- and revising -- patterns is one of the key
activities in peeragogy, so you will likely want to revisit this chapter
several times as you look through the rest of the book. Don't forget
your red pen or pencil, because you'll also want to tailor the patterns
we describe here to suit.

** Case Study: SWATS.
     :PROPERTIES:
     :CUSTOM_ID: case-study-swats.
     :END:

We present another example of peer learning in a classroom setting,
focusing on the process of improving overall student performance with
the help of a group of student experts. After describing the case study
in general terms, we then re-analyze it using our pattern tools to show
how examples like this can be integrated into our project.

* Convening a Group
    :PROPERTIES:
    :CUSTOM_ID: convening-a-group
    :END:

This chapter is about how to begin your own peeragogical project. You
can also use the ideas described here to strengthen an existing
collaboration. Simple but important questions will inspire unique
answers for you and your group. In short: who, what, when, where, why,
and how? Use this chapter to help design and critique your project's
roadmap.

** Play & Learning.
     :PROPERTIES:
     :CUSTOM_ID: play-learning.
     :END:

What makes learning fun? Just as actors learn their roles through the
dynamic process of performance, In other words, the more we engage with
a topic, the better we learn it and the more satisfying - or fun - the
process becomes.

** K-12 Peeragogy.
     :PROPERTIES:
     :CUSTOM_ID: k-12-peeragogy.
     :END:

The key to becoming a successful 'connected educator-learner' involves
spending the time needed to learn how to learn and share in an open,
connected environment. Once you make the decision to enter into a
dialogue with another user, you become a connected educator/learner and
tap into the power of networks to distribute the load of learning.
Depending on their age, you can even facilitate an awareness of peer
networks among your students.

** P2P Self-Organizing Learning Environments.
     :PROPERTIES:
     :CUSTOM_ID: p2p-self-organizing-learning-environments.
     :END:

This section invites an exploration of support for self-organized
learning in global and local networks. Emergent structures can create
startling ripple effects.

* Organizing a Learning Context
    :PROPERTIES:
    :CUSTOM_ID: organizing-a-learning-context
    :END:

Peer learning is sometimes organized in "courses" and sometimes in
"spaces." We present the results of an informal poll that reveals some
of the positive and some of the negative features of our own early
choices in this project.

** Adding Structure with Activities.
     :PROPERTIES:
     :CUSTOM_ID: adding-structure-with-activities.
     :END:

The first rule of thumb for peer learning is: announce activities only
when you plan to take part as a fully engaged participant. Then ask a
series of questions: what is the goal, what makes it challenging, what
worked in other situations, what recipe is appropriate, what is
different about learning about this topic?

** Student Authored Syllabus.
     :PROPERTIES:
     :CUSTOM_ID: student-authored-syllabus.
     :END:

This chapter describes various methods for co-creating a curriculum. If
you're tasked with teaching an existing curriculum, you may want to
start with a smaller co-created activity; but watch out, you may find
that co-creation is habit forming.[fn:1]

** Case Study: Collaborative Explorations.
     :PROPERTIES:
     :CUSTOM_ID: case-study-collaborative-explorations.
     :END:

This chapter describes collaborative peer learning among adult students
in the Master's program in Critical and Creative Thinking at University
of Massachusetts in Boston. The idea in the collaborative explorations
is to encourage individuals pursuing their own interests related to a
predetermined topic, while supporting learning of everyone in the group
through sharing and reflection. These interactions of supportive mutual
inquiry evolve the content and structure within a short time frame and
with open-ended results.

* Cooperation
    :PROPERTIES:
    :CUSTOM_ID: cooperation
    :END:

Sometimes omitting the figurehead empowers a group. Co-facilitation
tends to work in groups of people who gather to share common problems
and experiences. The chapter suggests several ways to co-facilitate
discussions, wiki workflows, and live online sessions. Conducting an
"after action review" can help expose blind spots.

** The Workscape.
     :PROPERTIES:
     :CUSTOM_ID: the-workscape.
     :END:

In a corporate workscape, people are free-range learners: protect the
learning environment, provide nutrients for growth, and let nature take
its course. A workscape features profiles, an activity stream, wikis,
virtual meetings, blogs, bookmarks, mobile access and a social network.

** Participation.
     :PROPERTIES:
     :CUSTOM_ID: participation.
     :END:

Participation grows from having a community of people who learn
together, using a curriculum as a starting point to organize and trigger
engagement. Keep in mind that participation may follow the 90/9/1
principle (lurkers/editors/authors) and that people may transition
through these roles over time.

** Designs For Co-Working.
     :PROPERTIES:
     :CUSTOM_ID: designs-for-co-working.
     :END:

Designing a co-working platform to include significant peer learning
aspects often requires a new approach. This chapter describes the
initial steps of converting an existing online encyclopedia project into
a peer learning platform.

* Assessment
    :PROPERTIES:
    :CUSTOM_ID: assessment
    :END:

"Usefulness" is an appropriate metric for assessment in peeragogy, where
we're concerned with devising our own problems rather than than the
problems that have been handed down by society. We use the idea of
return on investment (the value of changes in behavior divided by the
cost of inducing the change) to assess the Peeragogy project itself, as
one example.

** Researching peeragogy.
     :PROPERTIES:
     :CUSTOM_ID: researching-peeragogy.
     :END:

This chapter is based on a "found manuscript" created by one of us as an
undergraduate. It looks at the challenges that are associated with
combining the roles of student, teacher, and researcher. It shows the
relevance of peer support, and also illustrates the important factor of
time in the evolution of an idea.

* Technologies, Services, and Platforms
    :PROPERTIES:
    :CUSTOM_ID: technologies-services-and-platforms
    :END:

Issues of utility, choice, coaching, impact and roles attach to the wide
variety of tools and technologies available for peer learning. Keys to
selection include the features you need, what people are already using,
and the type of tool (low threshold, wide wall, high ceilings) used for
collaboration.

** Forums.
     :PROPERTIES:
     :CUSTOM_ID: forums.
     :END:

Forums are web-based communication media that enable groups of people to
conduct organized multimedia discussions about multiple topics over a
period of time, asynchronously. A rubric for evaluating forum posts
highlights the value of drawing connections. This chapter includes tips
on selecting forum software.

** Wiki.
     :PROPERTIES:
     :CUSTOM_ID: wiki.
     :END:

A wiki is a website whose users can add, modify, or delete its content
via a web browser. Pages have a feature called "history" which allows
users to see previous versions and roll back to them. This chapter
includes tips on how to use a wiki and select a wiki engine, with
particular attention to peer learning opportunities.

** Real-time meetings.
     :PROPERTIES:
     :CUSTOM_ID: real-time-meetings.
     :END:

Web services enable broadband-connected learners to communicate in real
time via audio, video, slides, whiteboards, chat, and screen-sharing.
Possible roles for participants in real-time meetings include searchers,
contextualizers, summarizers, lexicographers, mappers, and curators.
This mode of interaction supports emergent agendas.

** Connectivism in Practice.
     :PROPERTIES:
     :CUSTOM_ID: connectivism-in-practice.
     :END:

Massive Open Online Courses (MOOCs) are decentralized online learning
experiences: individuals and groups create blogs or wikis and comment on
each other's work, often with other tools helping find information.

* Resources
    :PROPERTIES:
    :CUSTOM_ID: resources
    :END:

Here we present a sample syllabus for bringing peer learning to life,
recommended reading and tips on writing for The Handbook, as well as our
Creative Commons Zero 1.0 Universal (CC0 1.0) Public Domain Dedication.

[fn:1] Quick tip: if you create a syllabus, share it!

