#+TITLE: Technologies
#+FIRN_ORDER: 35

*It is tempting to bring a list of technologies out as a glorious
cookbook.* We need a 1/2 cup of group writing tools, 2 tsp. of social
network elements, a thick slice of social bookmarking, and some sugar,
then put it in the oven for 1 hour for 350 degrees.

We have created a broad features/functions list for Handbook readers to
reflect upon and consider. The joy of this list is that you can consider
alternatives for the way you communicate and work while you are planning
the project, or can add in new elements to solve communications gaps or
create new tools.

However, too many tools spoil the broth. In the writing of this
Handbook, we found that out firsthand. We spent a lot of marvelous
energy exploring different tools to collaborate, curate information, do
research, tag resources, and adjudicate among all of our points of view.
In looking at groups working with the various MOOCs, as another example,
different groups of students often camp in different social media
technologies to work.

In large courses, students often have to be pushed into various social
media tools to "co-create" with great protest and lots of inertia. And
finally, co-learning groups often come from very different backgrounds,
ages, and stages of life, with very different tools embedded in their
current lives. Do we have time for three more tools in our busy days? Do
more tools help -- or do they interfere with our work?

In this section, we'll share with you a few issues:

- What technologies are most useful in peer learning? What do we use
  them for? What features or functions help our co-learning process?
- How do we decide (a) as a group and (b) for the group on what tools we
  can use? Do we decide upfront, or grow as we go?
- How do we coach and scaffold each other on use of tools?
- How much do the tool choices impact the actual outcome of our learning
  project?
- What are the different roles that co-learners can take in co-teaching
  and co-coaching the technology affordances/assumptions in the project
  to make others' lives easier?

Keep in mind -- your needs for tools, plus how the way the group uses
them, will change as the co-learning project moves along.  Technologies
themselves tend to change rapidly.  Are you willing to change tools
during the project as your needs and users change, or do you plan to use
a given tool set from the beginning to the end of your project?

** Features and Considerations
   :PROPERTIES:
   :CUSTOM_ID: features-and-considerations
   :END:

We will begin below with a discussions of "features" and initial
considerations, and then move to a broader "Choose Your Own
Adventure"-style matrix of features leading to a wide variety of
collaboration-based technology tools online.

*** Technologies and Features
    :PROPERTIES:
    :CUSTOM_ID: technologies-and-features
    :END:

As we will share in the extensive list below, there are abundant tools
now available -- both for free and for pay -- to bring great features to
our co-learning endeavors. It is tempting to grab a group of fancy tools
and bring the group into a fairly complex tool environment to find the
perfect combination of resources. The challenge: adult learners seek
both comfort and context in our lives [1], [2]. In choosing tool
"brands", we can ignore the features themselves and what we need as
parts of the puzzle for learning. We also can have anxiety about our
self-beliefs around computers and technology, which in turn can limit
our abilities [3].

Before we get to brands and choices, it helps to ask a few questions
about the learning goals and environments:

- What do we need as features, and at what stage of the learning
  process?
- What are we already comfortable with, individually and as a group?
- Do we want to stay with comfortable existing tools, or do we want to
  stretch, or both?
- What types of learners do we have in this group? Technologically
  advanced? Comfortable with basics?
- Do we want to invest the time to bring the whole group up to speed on
  tools? Do all the group members agree on this? Do we want to risk
  alienating members by making them invest time in new resources?
- We know that our use will migrate and adapt. Do we want to plan for
  adaptation? Observe it? Learn from it? Make that change intentional as
  we go?

Researchers over the years have heavily examined these questions of
human, technology, and task fit in many arenas.
[[http://en.wikipedia.org/wiki/Human-Computer_Interaction][Human-Computer
Interaction]] researchers have looked at "fit" and "adaptive behavior,"
as well as how the tools can affect how the problem is presented by
Te'eni [4]. Creativity support tools [5] have a whole line of design
research, as has the field of
[[http://en.wikipedia.org/wiki/Computer-supported_cooperative_work][Computer-Supported
Collaborative Work Systems (CSCW)]]. For co-learners and designers
interested in the abundance in this space, we've added some additional
links below. We here will make this a bit easier. For your co-learning
environment, you may want to do one or two exercises in your decision
planning:

What /features do you need/?  Do you need collaboration? Graphic models?
Places to work at the same time (synchronous)? Between meetings
(asynchronous)? What are the group members /already using/ as their
personal learning platforms? It also makes sense to do an inventory
about what the group already has as their learning platforms. I'm doing
that with another learning group right now. People are much more
comfortable -- as we also have found in our co-creation of this Handbook
-- creating and co-learning in tools with which they already are
comfortable. Members can be co-teachers to each other -- as we have have
-- in new platforms. What /type of tools/, based on the features that we
need, shall we start out with?  Resnick /at al./ [6] looked at tools
having:

- Low thresholds (easy to get people started)
- Wide walls (able to bring in lots of different situations and uses)
  and
- High ceilings (able to do complex tasks as the users and uses adapt
  and grow).

What are important features needed for co-creation and /working
together/? In other pages above, we talk abundantly about roles and
co-learning challenges. These issues also are not new; Dourish &
Bellottii [7] for example, shared long-standing issues in
computer-supportive collaborative work online about how we are aware of
the information from others, passive vs. active generation of
information about collaborators, etc. These challenges used to be
"solved" by software designers in individual tools. Now that tools are
open, abundant, and diverse, groups embrace these same challenges when
choosing between online resources for co-learning.

*** Useful Uses and Fancy Features of Technological Tools
    :PROPERTIES:
    :CUSTOM_ID: useful-uses-and-fancy-features-of-technological-tools
    :END:

From here, we will help you think about what might be possible, linking
to features and solution ideas.

We start with ways to ask the key questions: What do you want to do and
why? We will start with features organized around several different
axes:

1. Time/Place
2. Stages of Activities and Tasks
3. Skill Building/Bloom's Taxonomy
4. Use Cases
5. Learning Functions

Each will link to pages that will prompt you with features,
functionality, and technology tool ideas.

*** Time/Place
    :PROPERTIES:
    :CUSTOM_ID: timeplace
    :END:

We can further break down tools into whether they create or distribute,
or whether we can work simultaneously (synchronous) or at our own times
(ascynchronous). To make elements of time and place more visual, Baecker
[8] created a CSCW Matrix, bringing together time and place functions
and needs. Some tools are synchronous, such as Google+ Hangouts,
Blackboard Collaborate, and Adobe Connect, while others let us work
asynchronously, such as wikis and forums. Google Docs can work be used
both ways. We seem to be considering here mostly tools good for group
work, but not for solo, while many others are much easier solo or in
smaller groups.

*** Stages of Activities and Tasks
    :PROPERTIES:
    :CUSTOM_ID: stages-of-activities-and-tasks
    :END:

Ben Shneiderman [5] has simplified the proliferation of models in this
area (e.g., Couger and Cave) with a clear model of four general
activities and eight tasks for individuals, which we can lean on as
another framework for co-creation in co-learning.

Tools and functions won't be clear cut between areas. For example, some
tools are more focused on being generative, or for creating content.
Wikis, Etherpad, Google docs, and others usually have a commenting/talk
page element, yet generating content is the primary goal and
discursive/consultative functions are in service to that. Some tools are
discursive, or focused on working together for the creative element of
"relating" above -- Blackboard Collaborate, the social media class room
forums, etc.

*** Skill Building (Cognitive, a la Bloom's Taxonomy, see below)
    :PROPERTIES:
    :CUSTOM_ID: skill-building-cognitive-a-la-blooms-taxonomy-see-below
    :END:

Given that we are exploring learning, we can look to Bloom's Taxonomy
(revised, see [9]) for guidance as to how we can look at knowledge
support. Starting at the bottom, we have:

- Remembering, as a base;
- Understanding,
- Applying,
- Analyzing,
- Evaluating, and then, at the top,
- Creating.

We could put "search" in the Remembering category above. Others contest
that Search, done well, embraces most of the Bloom's elements above.
Samantha Penney has created a
[[http://www.usi.edu/distance/bdt.htm][Bloom's Digital Taxonomy
Pyramid]] infographic, describing tools for learning, which you may want
to check out.

*** Use Cases (I want to....)
    :PROPERTIES:
    :CUSTOM_ID: use-cases-i-want-to.
    :END:

Technologies can be outlined according to the need they serve, or the
use case they fulfill. Examples: If we need to 'curate', a platform like
Pearl Trees is an option. To 'publish' or 'create', we can look to a
wiki or WordPress. Other choices might be great in order to
'collaborate', etc.

One challenge is that tools are not that simple. As we look more closely
at the technologies today, we need to reach more broadly to add multiple
tags to them. For example Twitter can be used for "Convening a group,"
for "micro-blogging," for "research," etc.

- Collaborate with a Group
- Create Community
- Curate Information
- Research
- Publish Information
- Create Learning Activities
- Make Something

These plans get more complex, as you are making a group of decisions
about tool functionality in order to choose what combination works for
the use cases. It may be most useful to use a concept map (a tech tool)
to think about the needs and combinations that you would bring together
to achieve each Use Case or Learning Module.

*** Technology Features/Functions
    :PROPERTIES:
    :CUSTOM_ID: technology-featuresfunctions
    :END:

We have not made this easy! There are lots of moving elements and
options here, none of them right for everything, and some of them
fabulous for specific functions and needs. Some have the low thresholds
but may not be broad in scope. Some are broad for many uses; others are
specific task-oriented tools. That is some of the charm and frustration.

Weaving all of the above together, we have brought together a shared
taxonomy for us to discuss and think about co-learning technology
features and functions, which we present as an appendix below. This
connects various technology features within an expanded version of Ben
Shneiderman's creativity support tools framework. We've created this
linked toolset with multiple tags, hopefully making it easier for you to
evaluate which tool suits best the necessities of the group. Please
consider this a starting point for your own connected exploration.

** Appendix: Features and Functions
   :PROPERTIES:
   :CUSTOM_ID: appendix-features-and-functions
   :END:

Weaving all of these frameworks together, we have brought together a
shared taxonomy for us to discuss and think about co-learning technology
features and functions. We have connected various technology features
with an expanded version of Ben Shneiderman's creativity support tools
framework for the linked resource guide. For convenience and to help
keep it up to date, we're publishing this resource
[[http://goo.gl/H02fMA][on Google Docs]]. We present an overview in the
following chapters.

*** References
    :PROPERTIES:
    :CUSTOM_ID: references
    :END:

1. Schein, E. H. (1997). /Organizational learning as cognitive
   re-definition: Coercive persuasion revisited/. Cambridge, MA: Society
   for Organizational Learning.

2. Schein, E. H. (2004). /Organizational culture and leadership./ San
   Francisco, CA: Jossey-Bass.

3. Compeau, D.R., & Higgins, C.A. (1995, June). Computer Self-Efficacy:
   Development of a Measure and Initial Test. /MIS Quarterly, 19/, (2),
   189-211.

4. Te'eni, D. (2006). Designs that fit: An overview of fit
   conceptualizations in HCI. In /Human-Computer Interaction and
   Management Information Systems: Foundations/, edited by P. Zhang and
   D. Galletta, pp. 205-221, Armonk, NY: M.E. Sharpe.

5. Shneiderman, B. (2002). Creativity support tools. /Commun. ACM/ 45,
   10 (October 2002), 116-120.

6. Resnick, M, Myers, B, Nakakoji, K, Shneiderman, B, Pausch, R, Selker,
   T. & Eisenberg, M (2005). [[http://repository.cmu.edu/isr/816][Design
   principles for tools to support creative thinking]]. /Institute for
   Software Research./ Paper 816.

7. Dourish, P. & Bellotti, V. (1992). Awareness and coordination in
   shared workspaces. In /Proceedings of the 1992 ACM conference on
   Computer-supported cooperative work/ (CSCW '92). ACM, New York, NY,
   USA, 107-114.

8. Baecker, R.,
   [[http://www.interaction-design.org/references/authors/jonathan_grudin.html][Grudin]],
   J.,
   [[http://www.interaction-design.org/references/authors/william_buxton.html][Buxton]],
   W., &
   [[http://www.interaction-design.org/references/authors/saul_greenberg.html][Greenberg]],
   & (eds.) (1995): /Readings in Human-Computer Interaction: Toward the
   Year 2000./ New York, NY: Morgan Kaufmann Publishers

9. Anderson, L. W., & Krathwohl, D. R. (Eds.). (2001). /A taxonomy for
   learning, teaching and assessing: A revision of Bloom's Taxonomy of
   educational objectives: Complete edition/. New York, NY: Longman.

