#+TITLE: 10 November
#+AUTHOR: Peeragogy Project
#+FIRN_ORDER: 21
#+FIRN_UNDER: Updates
#+FIRN_LAYOUT: update
#+DATE_CREATED: <2021-01-06 Wed>

* Navigation
Next:[[file:../peeragogy_in_action_episode_4_project_action_review.org][Peeragogy in Action Episode 4 Project Action Review]]
* Review the intention: what do we expect to learn or make together?
Refine & coordinate the points we make in the article
Figure out whether we’re doing an example
Put the action review in the paper

* Establish what is happening: what and how are we learning?
Dialogue between Ray, Hermano, Charlie, Charlotte, and Joe
“Hive editing” of the EXAMPLE box
A lot about all the topic in our paper as we keep discussing them, e.g., the Delphi method

* What are some different perspectives on what’s happening?
Discussed putting the action review in the paper
Hermano is a recent addition to our group but has become fully involved & has an intuitive understanding what we’re trying to achieve & fresh, valuable, input
This is more fun than a normal co-authoring event 
Regular meetings w/ a time limit

* What did we learn or change?
Lots of ideas and talking over one another but there is an intuitive sense of when we need to step back and let someone speak - safe place to share your ideas versus other places where trolls will criticize some people’s ideas
Chaotic ideas w/ intuitive sense of when someone needs to express themselves
The environment fosters sharing of opinions, developed (and emerging) positions
Trolls don’t jump on you!

* What else should we change going forward?
Do a PAR at the end about the whole article
Review and refine all Pars
Delphi + Englebart action item for Charlie
Film one of the hive editing sessions and point out this is what 
