#+TITLE: 24 September, "A Picture of Change for a World in Constant Motion"
* Navigation
Next: [[file:30_september_tl_dr_last_six_months.org][30 September: tl;dr last six months]]
* Review the intention: what do we expect to learn or make together?
https://www.nytimes.com/interactive/2020/08/07/arts/design/hokusai-fuji.html
We hope to make the peeragogy forum into a "practice space".  That is to say: our primary method for advancing peeragogy is to "do" peeragogy, and our work is basically "practice-theoretic", in philosophy lingo (https://en.wikipedia.org/wiki/Practice_theory).
* Establish what is happening: what and how are we learning?
Different people have different ideas of practice and what peeragogy "is". The case of "peeragogy for kids" brings this to the fore. There are also severla rather different sets of practices in place in various online forums.
* What are some different perspectives on what’s happening?
That is, presumably, exactly how things should be, since we are trying to do peer learning, not Borg-like assimilation. However, given that there's widespread confusion and some ruffled feathers on the topic of "advertising" and broader relationships between Peeragogy and other groups and activities, we might want to make something explicit about these topics in the Peeragogy Community Guidelines, which presently exist only in draft form: https://docs.google.com/document/d/1bpFGRmtWVe8GoBKKH4wiuoM3uEBBDNfLzaYVzn20Ags/edit#heading=h.z8s7p3mq1dw0
* What did we learn or change?
My asking Charles to write a PAR made him feel "put on the spot." That wasn't my intention: I genuinely wanted to recommend a practice that I enjoy. On reflection probably the links that Charles & Roland shared to CICOLab and MetaCAugs events are in the same basic genre of "sharing practices that I like." We could potentially approach all generically-labeled "sharing" through a more articulated language of "consent", keeping in mind these failure modes:
- If somebody serves non-consensually they’re being a martyr or rescuer.
- If somebody takes non-consensually they’re being a perpetrator or groper.
- If somebody allows non-consensually they’re being a doormat or pushover.
- If somebody accepts non-consensually they’re being entitled and freeloading.
— https://www.rewriting-the-rules.com/sex/wheel-consent-im-fan/
How might that look here?  Well, at present I'm trying to "share" a (partially?) filled-in PAR rather than a "blank canvas".  This invites participation but doesn't require it.  I think Charlotte's suggestion, above, "How about a periodic short posting recapping the topics of interest to Peeragogy (which is almost all your content, TBH), and add a subscription link so people can opt-in?" runs on the same lines.  We've all "consented" to share some of our attention with others, but not necessarily to engage in others' preferred practices.  So, sharing thought-through and reasonably well-digested reflections rather than just invitations could help prevent people feeling "put on the spot."  We should also think about how we work together with more preliminary non-digested content...which in my experience is often one of the most fun parts of the peeragogy project!  But a topic for another day.
* What else should we change going forward?
Circumstantially: I want to move the Peeragogy forum to OSU Open Source Lab hosting soon. The initial purpose of my OSU OSL lab request was to be a one-for-one replacement for the Google Forum that makes it accessible to people who do not have a Google login, so I don't want to confuse matters by making it into something else in midstream. However, we might also want to think about making an "opt-in" moment sometime soon, so that we know that everyone who is on the forum actually wants to be there, and so that we get some of the other points of un-clarity cleared up. This could go along with introducing the "new" community guidelines.  To my mind, such opt-in moments have been a good part of our work in the past, and in light of the above comments about "consent" I think we should give these matters some attention!
