#+TITLE: 2 August PAR by Vitor
#+AUTHOR: Peeragogy Project
#+FIRN_ORDER: 11
#+FIRN_UNDER: Updates
#+FIRN_LAYOUT: update
#+DATE_CREATED: <2021-01-06 Wed>

* Navigation
Next: [[file:2_august_par_by_charlotte_and_charlie.org][2 August PAR by Charlotte and Charlie]]
* Review the intention: what do we expect to learn or make together?

    Master a new method/approach to teach and/or learn peeragogically, then add the tech up.

* Establish what is happening: what and how are we learning?

    Related to peeragogy, so far I'm learning by doing, I mean by being in the meeting, I still think an onboarding material would help, like a study guide, the first gaming level AKA tutorial.

* What are some different perspectives on what’s happening?

    I'm starting to read by my own about early peeragogy 

* What did we learn or change?

    We became more friends, I mean some times was afraid of being the less smart of the room, I still am, but now it doesn't bother me anymore

* What else should we change going forward?

    Structured learning, some homework, strategies to where are we heading to
