#+TITLE: 2 August PAR by Charlotte and Charlie
* Navigation
Next: [[file:hyperreal_enterprises_action_review.org][Hyperreal Enterprises Action Review]]
* Review the intention: what do/did we expect to learn or make together?

    As course co-coordinators we expected to learn more about how to run a course in peeragogy.
    We expected the participants to learn more peer learning and peer production
    Develop a “product” or focus for peeragogy, “what does it do?”
    Participants and co-coordinators figure out “What’s in it for me?” with peeragogy and the course itself

* Identify what happened: what and how did we learn?

    HOW: Video conferencing - allows for global participation
    Open source ethos - Hermano
    Business orientation - Vitor
    Get practical/aka no mo’ navel gazing - Charlotte
    Building the syllabus taught me how to make a markdown document in GitHub - Charlie

* What are some different perspectives on what transpired?

    I felt like we made a lot of great memories and co-created some wonderful learning moments - Charlie
    Gave some structure to my day/week- Charlotte
    Unlike other meetings, I never dreaded these.

* What did we learn or change during the process?

    Accept “newcomers” - Hermano, Vitor
    We weren’t always “prepared” :-o
    We “kept going”
    Organized on calendar (session 6/8, etc.)
    Decided on one place to take notes - in this case it was the zoom chat
    Use of other platforms does not need to be disruptive. But it does help to have a central one that others feed into. Synchronizing different apps and platforms remains an ongoing challenge.

* What else should we change going forward?

    Develop system to encourage participation
    Maybe circulate agenda/outline for comment a few days before course session
    Develop system for “getting the word out” and onboarding if it brings in new ppl
    Map out a better definition of the course - along the lines of Joe’s for Tufts pilot
    Update Rheingoldian meeting roles to have “primary” ones that should be filled first and “nice to have”
    Update the Peeragogical Action Review to account for use during an activity itself or after its completed
