#+TITLE: 30 September: tl;dr last six months
* Navigation
Next: [[file:april_to_september_wrap.org][April to September Wrap]]
* Review the intention: what do we expect to learn or make together?
For the tl/dr version of six months, peep this PAR, or Project Action Review[1]. Special thanks to Vitor for his assistance with this one.

To produce some meaningful learning products (article, course, software, etc).

* Establish what is happening: what and how are we learning?

We’ve been reading, reviewing the texts, doing side projects, developing educational techniques.

* What are some different perspectives on what’s happening?

It has not been a linear path of progress over the last six months, but we have definitely progressed!

* What did we learn or change?

We've learned to manage expectations, lean on the friends we never met face to face, and to survive during the COVID-19 crisis.

* What else should we change going forward?

Think in a sustainable way to make the group self-sufficient by creating sellable products (book, article, courses) so that the group can have more than one website and raise our visibility.

https://groups.google.com/g/peeragogy/c/NStX-vt1l1M/m/Wr-N8VzlAwAJ
