#+TITLE: 6 November
* Navigation
Next: [[file:10_november.org][10 November]]
* Review the intention what did/do we want to accomplish?

Work on our last review of the paper

* What and how are we learning?

Same as before we are making progress on the paper
Met a new person in Giuliana who had awesome ideas & questions 
Realized we need to answer More questions from the intro 

* What are some different perspectives on what’s happening?

Went great getting new perspectives with Giuliana 
Becoming even more fluid, our discussion and onboarding of new people
Her presence gave us fresh perspective, rich example of how newcomer can come & enrich the discussion 
Example of how we can try to make peeragogy more accessible to new people 

* What did we learn or change?

Best learning mode for peeragogy might be experience (peeragogy in action)
Learned more about newcomers 

* What should we change going forward?

Promote our hive editing videos more as examples of collective mind In action 
seconds of hire editing in action so person can see what its about 
Can we use this PAR method to write the conclusion, make sure we answer questions in introduction 
