#+TITLE: Concept
As we noted in the introduction, various notions of ‘pattern’ have been used by
anthropologists (Benedict, 1946), mythologists (Campbell, 1949), historians
14(Inayatullah, 1998a), and others, to understand extant social structures. Alexander and
his cohorts utilized the central property of patterns — the fact that they recur with
variations — to help design new structures for habitation. Because ​ futures studies ​ go
beyond ​ design ​ , and consider not just new structures but our entire orientation towards
the future, we were curious to explore how design patterns might relate to this more
general setting. Just as narrative methods (Gill, 2013; Liveley, 2017; Wagner-Lawlor,
2017) have been applied in design, and from there, reapplied in futures studies, we
have proposed that patterns can be used for futures studies.
Our main results outlined several ways in which design patterns can be used to model
future-directed activities. As we have noted, they can also be used to promote
heterogeneity of thought and behavior. Design pattern methods could be developed
further and made to interact with macrohistorical patterns for anticipation, or combined
with CLA (Inayatullah, 2006, 1998b), to connect diverse and divergent themes across
multiple layers of experience and observation.
In reflecting on the challenges still to come, we ask: how can we foster and cherish
thoughts about the future, and connect them with action? One broad answer is to
develop a culture in which we learn things, and share what we have learned in a way
that makes that learning maximally accessible to others, while remaining maximally
open and nondogmatic, actively promoting the diversification of viewpoints.
