#+TITLE: Wrap March
#+AUTHOR: Peeragogy Project
#+FIRN_ORDER: 8
#+FIRN_UNDER: Updates
#+FIRN_LAYOUT: update
#+DATE_CREATED: <2021-01-06 Wed>

* Navigation
Next: [[file:29_may_2020.org][29 May 2020]]
* Review the intention: what do we expect to learn or make together?
• Finish the initial version of the peeragogy course
• Make progress on version 4 of the handbook
• Work on a paper to submit
• Share our ideas and methods with others
• See if there are ways we can help or support others in time of COVID-19
* Establish what is happening: what and how are we learning?
• We made progress on sharing and writing
• The course was completed!
• We got involved with some interesting COVID-19 projects
* What are some different perspectives on what’s happening?
• I had fun, learned a lot, and was excited to complete the first course!
• What do you think of what we did, dear reader?
* What did we learn or change?
• Learned about how to run a course from start to finish
• Watched how other groups of peers came together rapidly to produce some neat, timely, and helpful things for their fellow humans, including the Coronavirus Tech Handbook6 and shared medical supply designs7
* 5
N/A
