#+TITLE: Cofacilitation
#+FIRN_ORDER: 28

Facilitation is a process of helping groups work cooperatively and
effectively. Facilitation can be particularly helpful for individuals
who, based on a certain level of insecurity or inexperience, tend to
lurk rather than participate. At the same time, in peeragogy, a
facilitator isn't necessarily an "authority." Rather, facilitation work
is done in service to the group and the group dialogue and process. For
example, a facilitator may simply "hold space" for the group by setting
up a meeting or a regular series of discussions.

** Co-facilitating in peer-to-peer learning
   :PROPERTIES:
   :CUSTOM_ID: co-facilitating-in-peer-to-peer-learning
   :END:

Co-facilitation can be found in collaborations between two or
more people who need each other to complete a task, for example, learn
about a given subject, author a technical report, solve a problem, or
conduct research. Dee Fink writes that "in this process, there has to be
some kind of change in the learner. No change, no learning" [1].
Significant learning requires that there be some kind of lasting change
that is important in terms of the learner's life; in peeragogy, one way
to measure the effectiveness of co-facilitation is to look for a change
in the peer group.

Co-facilitation roles can be found in groups/teams like basketball,
health, Alcoholics Anonymous, spiritual groups, etc. For example,
self-help groups are composed of people who gather to share common
problems and experiences associated with a particular problem,
condition, illness, or personal circumstance.  There are some further
commonalities across different settings.  Commenting on the work of Carl
Rogers:

#+BEGIN_QUOTE
  *Godfrey Barrett-Lennard*: The educational situation which most
  effectively promotes significant learning is one in which (1) threat
  to the self of the learner is reduced a minimum, and (2)
  differentiated perception of the field of experience is facilitated.
  [2]
#+END_QUOTE

Part of the facilitator's role is to create a safe place for learning to
take place; but they should also challenge the participants.

#+BEGIN_QUOTE
  *John Heron*: Too much hierarchical control, and participants become
  passive and dependent or hostile and resistant. They wane in
  self-direction, which is the core of all learning. Too
  much cooperative guidance may degenerate into a subtle kind of
  nurturing oppression, and may deny the group the benefits of totally
  autonomous learning. Too much autonomy for participants and
  laissez-faire on your part, and they may wallow in ignorance,
  misconception, and chaos. [3]
#+END_QUOTE

** Co-facilitating discussion forums
   :PROPERTIES:
   :CUSTOM_ID: co-facilitating-discussion-forums
   :END:

If peers are preparing a forum discussion, here are some ideas from
"[[http://ctb.ku.edu/en/tablecontents/section_1180.aspx][The Community
Tool Box]]", that can be helpful as guidelines:

- Explain the importance of collaborative group work and make it a
  requirement.
- Establish how you will communicate in the forum.
- Be aware of mutual blind spots in facilitating and observing others.
- Watch out for different rhythms of intervention.

** Co-facilitating wiki workflows
   :PROPERTIES:
   :CUSTOM_ID: co-facilitating-wiki-workflows
   :END:

A good place to begin for any group of co-facilitators working with a
wiki are Wikipedia's famous "5 Pillars."

- Wikipedia is an encyclopedia.
- Wikipedia writes articles from a neutral point-of-view.
- Wikipedia is free content that anyone can edit, use, modify, and
  distribute.
- Editors should interact with each other in a respectful and civil
  manner.
- Wikipedia does not have firm rules.

** Co-facilitating live sessions
   :PROPERTIES:
   :CUSTOM_ID: co-facilitating-live-sessions
   :END:

Learning experiences in live sessions are described in the article
[[http://dmlcentral.net/blog/howard-rheingold/learning-reimagined-participatory-peer-global-online][Learning
Re-imagined: Participatory, Peer, Global, Online]] by Howard Rheingold,
and many of these points are revisited in the handbook section on
[[http://peeragogy.org/real-time-meetings/][real-time tools]].  But we
want to emphasize one point here:

#+BEGIN_QUOTE
  *Howard Rheingold*: Remember you came together with your peers to
  accomplish something, not to discuss an agenda or play with
  online tools; keep everything as easily accessible as possible to
  ensure you realize your goals.
#+END_QUOTE

** References
   :PROPERTIES:
   :CUSTOM_ID: references
   :END:

1. Fink, L. D (2003). /Creating significant learning experiences: An
   integrated approach to designing college courses/. John Wiley & Sons.

2. Barrett-Lennard, G. T. (1998). /Carl Rogers' Helping System: Journey
   & Substance/. Sage.

3. Heron, J. (1999). /The complete facilitator's handbook/. London:
   Kogan Page.

 
