#+TITLE: Connectivism
#+FIRN_ORDER: 39

Massive Open Online Courses (MOOCs) are online learning events that can
take place synchronously and asynchronously for months. Participants
assemble to hear, see, and participate in backchannel communication
during live lectures. They read the same texts at the same time,
according to a calendar. Learning takes place through self-organized
networks of participants, and is almost completely decentralized:
individuals and groups create blogs or wikis around their own
interpretations of the texts and lectures, and comment on each other's
work; each individual and group publicises their RSS feed, which are
automatically aggregated by a special (freely available) tool,
gRSShopper. Every day, an email goes out to all participants,
aggregating activity streams from all the blogs and wikis that engage
that week's material. MOOCs are a practical application of a learning
theory known as "connectivism" that situates learning in the networks of
connections made between individuals and between texts.

Not all MOOCs are Connectivist MOOCs (or /cMOOCs/).  Platforms such as
[[https://www.coursera.org/][Coursera]], [[https://www.edx.org/][edX]]
and [[http://www.udacity.com/][Udacity]] offering MOOCs which follow a
more traditional, centralized approach (these are sometimes called
/xMOOCs/). In this type of MOOC, a professor is taking the lead and the
learning-experience is organized top-down. However, some xMOOCs seem to
adopt a more blended approach. For instance, the course
/[[https://www.coursera.org/course/edc][E-learning and Digital
Cultures]]/ makes use of online spaces beyond the Coursera environment,
and the course organizers want some aspects of participation in this
course to involve the wider social web.

In this chapter we'll focus on cMOOCs.  One might wonder why a course
would want to be 'massive' and what '/massive/' means. cMOOC-pioneer
Stephen Downes explains that his focus is on the development of a
/network structure/, as opposed to a /group structure/, to manage the
course. In a network structure there isn't any central focus, for
example, a central discussion. That's also the reason why he
considers the figure of 150 active participants -- /Dunbar's Number/ --
to be the lower cut-off in order to talk about 'massive':

#+BEGIN_QUOTE
  *Stephen Downes*: Why Dunbar's number? The reason is that it
  represents the maximum (theoretical) number of people a person can
  reasonably interact with. How many blogs can a person read, follow and
  respond to? Maybe around 150, if Dunbar is correct. Which means that
  if we have 170 blogs, then the blogs don't constitute a 'core' -
  people begin to be selective about which blogs they're reading, and
  different (and interacting) subcommunities can form.
#+END_QUOTE

* A learning theory for the digital age
   :PROPERTIES:
   :CUSTOM_ID: a-learning-theory-for-the-digital-age
   :END:

Traditionally, scholars distinguish between three
main [[http://ryan2point0.wordpress.com/2010/01/12/taxonomy-of-learning-theories/][categories
of learning theories]]: /behaviorism/, /cognitivism/ and
/constructivism/. Stephen Downes and others would add a fourth
one: [[http://en.wikipedia.org/wiki/Connectivism][connectivism]], but
this is [[http://en.wikipedia.org/wiki/Talk:Connectivism][disputed]]. 
The central application of connectivism to date is as a theory of what
happens in Massive Open Online Courses.

The connectivist theory describes learning as a process of creating
connections and developing networks. It is based on the premise that
knowledge exists out in the world, rather than inside an individual's
mind. Connectivism sees the network as a central metaphor for learning,
with a node in the network being a concept (data, feelings, images,
etc.) that can be meaningfully related to other nodes. Not all
connections are of equal strength in this metaphor; in fact, many
connections may be quite weak.

On a practical level, this approach recommends that learning should
focus on where to find information (streams), and how to evaluate and
mash up those streams, rather than trying to enter lots of (perishable)
information into one's skull. Knowing the pipes is more important than
knowing what exactly each pipe contains at a given moment.  This is the
theory.  The practice takes place in Connectivist MOOCs (cMOOCs), like
[[http://change.mooc.ca/about.htm][Change11]].  Here, people are free to
participate at will.  Each week a subject is discussed during
synchronous sessions, which are recorded and uploaded for reference on
the Change11 website. The site also includes an archive of daily
newsletters and RSS-feeds of blog posts and tweets from participants.

cMOOCs tend to be learner-centered. People are encouraged to pursue
their own interests and link up with others who might help them. But the
distributed and free nature of the projects also leads to complaints;
participants often find it confusing when they attempt to follow up on
all the discussions (the facilitators say one should not try to follow
up on /all/ the content).

#+BEGIN_QUOTE
  *Stephen Downes*: This implies a pedagogy that (a) seeks to describe
  'successful' networks (as identified by their properties, which I have
  characterized as diversity, autonomy, openness, and connectivity); and
  (b) seeks to describe the practices that lead to such networks, both
  in the individual and in society (which I have characterized as
  modeling and demonstration (on the part of a teacher) and practice and
  reflection (on the part of a learner).
#+END_QUOTE

* Anatomy of a cMOOC
   :PROPERTIES:
   :CUSTOM_ID: anatomy-of-a-cmooc
   :END:

One example of a MOOC that claims to embody the connectivist theory is
[[http://change.mooc.ca/index.html][change.mooc.ca]]. The
"[[http://change.mooc.ca/how.htm][how it works]]" section of the site
explains what connectivism means in practice.  The MOOC organizers
developed a number of ways to combine the distributed nature of the
discussions with the need for a constantly updated overview and for a
federated structure. So, if your team wants to organize an open online
course, these are five points to take into consideration:

There is no body of content the participants have to memorize, but the
learning results from activities they undertake. The activities are
different for each person. A course schedule with suggested reading,
assignments for synchronous or asynchronous sessions is provided (e.g.
using Google Docs spreadsheets internally, Google Calendar externally;
one could also use a wiki), but participants are free to pick and choose
what they work on. Normally there is a topic, activities, reading
resources and often a guest speaker for each week. One should even
reflect upon the question whether a start and end date are actually
needed. It is crucial to explain the particular philosophy of this kind
of MOOC, and this right from the outset, because chances are learners
will come with expectations informed by their more traditional learning
experiences.

1. It is important to discuss the "internal" aspects, such as
   self-motivation: what do the participants want to achieve, what is
   their larger goal? And what are their intentions when they select
   certain activities (rather than other possibilities)? Everyone has
   her own intended outcome. Suggest that participants meditate on all
   this and jot down their objectives. And how can they avoid becoming
   stressed out and getting depressed because they feel they cannot
   "keep up with all this?" The facilitators should have a good look at
   these motivations, even if it's impossible to assist every
   participant individually (for large-scale MOOCs).

2. Ideally, participants should prepare for this course by acquiring the
   necessary digital skills.  Which skills are "necessary" can be
   decided by the group itself in advance. It's all about selecting,
   choosing, remixing - also called "curating". There are lots of tools
   which you can use for this: blogs, social bookmarks, wikis, mindmaps,
   forums, social dashboards, networks such as Twitter with their
   possibilities such as hashtags and lists. Maybe these tools are
   self-evident for some, but not necessarily for all the participants.

3. The course is not located in one place but is distributed across the
   web: on various blogs and blogging platforms, on various groups and
   online networks, on photo- and video-sharing platforms, on mindmaps
   and other visualization platforms, on various tools for synchronous
   sessions. This wide variety is in itself an important learning
   element.

4. There are weekly synchronous sessions (using Blackboard collaborate,
   or similar group chatting tool). During these sessions, experts and
   participants give presentations and enter into discussions. Groups of
   participants also have synchronous meetings at other venues (such as
   Second Life). Try to plan this well in advance!

5. Many participants highly appreciate efforts to give an overview of
   the proceedings. Specifically,
   the [[http://change.mooc.ca/newsletter.htm][Daily Newsletter]] is a
   kind of hub, a community newspaper. In that Daily there is also a
   list of the blog posts mentioning the course-specific tag
   (e.g. "Change11"), also the tweets with hashtag #change11 are listed
   in the Daily. Of course, the MOOC has a
   [[http://change.mooc.ca/index.html][site]] where sessions,
   newsletters and other resources are archived and discussion threads
   can be read.

From the very beginning of the course, it's necessary to explain
the importance of tagging the various contributions, to suggest
a hashtag.

For harvesting all this distributed content, Stephen Downes advocates
the use of [[http://grsshopper.downes.ca/index.html][gRSShopper]], which
is a personal web environment that combines resource aggregation, a
personal dataspace, and personal publishing (Downes developed it and
would like to build a hosted version - eventually financed via
Kickstarter). The gRSShopper can be found on the registration page,
which is useful primarily for sending the newsletter. It allows you to
organize your online content any way you want, to import content - your
own or others' - from remote sites, to remix and repurpose it, and to
distribute it as RSS, web pages, JSON data, or RSS feeds.

#+BEGIN_QUOTE
  *Stephen Downes*: For example, the gRSShopper harvester will harvest a
  link from a given feed. A person, if he or she has admin privileges,
  can transform this link into a post, adding his or her own comments.
  The post will contain information about the original link's author and
  journal. Content in gRSShopper is created and manipulated through the
  use of system code that allows administrators to harvest, map, and
  display data, as well as to link to and create their own content.
  gRSShopper is also intended to act as a fully-fledged publishing tool.
#+END_QUOTE

Alternatives for registrations: Google Groups for instance. But specific
rules about privacy should be dealt with: what will be the status of the
contributions? In this MOOC the status is public and open by default,
for Downes this is an important element of the course.

* Technologies
   :PROPERTIES:
   :CUSTOM_ID: technologies
   :END:

Some MOOCs use Moodle, but Downes dislikes the centralization aspect and
it's not as open as it could be, saying "people feel better writing in
their own space." Other possibilities: Google Groups, Wordpress, Diigo,
Twitter, Facebook page, Second Life; but each course uses different
mixtures of the many tools out there. People choose their environment -
whether it is WoW or Minecraft. Students use Blogger, WordPress, Tumblr,
Posterous as blogging tools.

* RSS harvesting is a key element
   :PROPERTIES:
   :CUSTOM_ID: rss-harvesting-is-a-key-element
   :END:

Give participants a means to contribute their blogfeed. In
"[[http://change.mooc.ca/new_feed.htm][Add a New Feed]]," Downes
explains how to get this structure and additional explanations (via
videos) in order to contribute their blog feed. The administrator in
this case uses gRSShopper to process the content and put it in a
database, process it and send it to other people. Alternatively one can
use Google Reader (the list of feeds is available as an OPML file -
which can be imported to other platforms). There is also a plug-in for
Wordpress that lets you use a Google Doc spreadsheet for the feeds, then
 Wordpress for the aggregation). Many other content management systems
have RSS harvesting features.

Each individual could run her own aggregator, but Downes offers it as a
service. But aggregators are needed, whether individual, centralized or
both.

** Specialized harvesting
    :PROPERTIES:
    :CUSTOM_ID: specialized-harvesting
    :END:

Using Twitter, Diigo, Delicious, Google Groups, If This Then That
([[http://ifttt.com][IFTTT]]) and [[http://feed43.com][Feed43]] (take
ordinary web page and turn it into an RSS feed).

** Synchronous environments
    :PROPERTIES:
    :CUSTOM_ID: synchronous-environments
    :END:

Synchronous platforms include Blackboard Collaborate (used now for
Change11); Adobe Connect; Big Blue Button; WizIQ; Fuze; WebX;
webcasting; web radio; videoconferencing with Skype or Google Hangout in
conjunction with Livestream or ustream.tv. Or take the Skype/Hangout
audiostream and broadcast is as webradio. Set up and test ahead of time,
but don't hesitate to experiment.  Note also, there is a more extensive
discussion of [[http://peeragogy.org/real-time-meetings/][real-time
tools]] in another section of the handbook.

** Newsletter or Feeds
    :PROPERTIES:
    :CUSTOM_ID: newsletter-or-feeds
    :END:

Feeds are very important (see earlier remarks about the Daily
newsletter). You can use Twitter or a Facebook page, Downes uses email,
he also creates an RSS version through gRSShopper and sends it through
Ifttt.com back to Facebook and Twitter. For the rest of us there is
Wordpress, which you can use to
[[http://www.wpbeginner.com/wp-tutorials/create-a-free-email-newsletter-service-using-wordpress/%20][create
an email news letter]].  Downs also suggests a handy guide on
[[http://www.smashingmagazine.com/2010/01/19/design-and-build-an-email-newsletter-without-losing-your-mind/][how
to design and build an email newsletter without loosing your mind]]!

Consider using a content management system and databases to put out
specialized pages and the newsletter in an elegant way, but this
requires a steep learning curve. Otherwise, use blogs / wikis.

** the Use of Comments
    :PROPERTIES:
    :CUSTOM_ID: the-use-of-comments
    :END:

Participants are strongly encouraged to comment on each others' blogs
and to launch discussion threads. By doing so they practice a
fundamental social media skill - developing networks by commenting on
various places and engaging in conversations. It is important to have
activities and get people involved rather than to just sit back and
watch. For an in-depth presentation, have a look
at [[http://www.downes.ca/presentation/290][Facilitating a Massive Open
Online Course]] by Stephen Downes, in which he focuses on research and
survey issues, preparing events, and other essentials.

* Resources
   :PROPERTIES:
   :CUSTOM_ID: resources
   :END:

- Change MOOC: [[http://change.mooc.ca/how.htm][How this Course Works]]
- [[http://www.youtube.com/watch?v=eW3gMGqcZQc][What is a MOOC]] (video)
- [[http://www.youtube.com/watch?v=r8avYQ5ZqM0][Success in a MOOC]]
  (video)
- [[http://www.youtube.com/watch?v=bWKdhzSAAG0][Knowledge in a MOOC]]
  (video)
- [[http://www.youtube.com/watch?v=mqnyhLfNH3I][Introduction and
  invitation]] (video)
