#+TITLE: Context

The context in which Peeragogy is applied is explored in several case studies.
- [[file:cases.org][Case Studies]]

Within the Peeragogy project, our working context seems to contain a
number of significant sub-contexts:
- [[file:website.org][Website]]
- [[file:project.org][Project]]
- [[file:course.org][Course]]
- [[file:podcast.org][Podcast]]
- [[file:paper.org][Paper]]
- [[file:community.org][Community]]
- [[file:handbook.org][Handbook]]

* Context as pattern
- The problem of context: to manifest relationships
- The solution of context: put problems into communication with solutions
- The context of context is always a bigger context


* Next steps

** BACK Podcast production meetings                                :podcast:
- These are now regularly scheduled, every week (optional, RSVP for interested people)
- For sourcing guests, doing promotions, include e.g. Arlington Media
- Good to have future guests along if they can drop in
- Production meetings set up to run weekly on the public peeragogy calendar
** BACK Upcoming podcast recording sessions                        :podcast:
- Charlotte is maintaining the Master Schedule of podcasts as a spreadsheet
  - These dates are copied into the public calendar when they get firmed up
- Some unofficial possible topics and themes are as follow:
- *Peeragogy Of Course* scheduled for the 12th — details need to be firmed up. Presently many of these various possible attendees have been invited...?
  - Howard and Melanie
  - Sherry, Kristy, Pete
  - … and the course participants would need to be confirmed — maybe 5, people pop in and out
- *‘Difficult conversations’* — ‘Crucial Conversations’ & difficult conversations, sticking to facts. What other people — Henry Pierce could come along for this one (Washington, Texas, Mass., Minn.)
  - Intercultural communication, differences in cultures & communication — Judith had some training in this (e.g., relating to body language, noticing where people’s eyes are going...); now relevant every time you go on a Zoom call.
- *“Peeragogy in Brazil”* w/ 3 or 4 guests — Vitor, Monica, Hermano, Analua...?  Noting, in the Brazilian context:
  - Teachers are overworked, people are losing their jobs, people worry about the vaccine
  - If peeragogy is some extra thing, then people won’t do it
  - Vitor can gather 10 or 15 people but they might not make a lot of noise about it
- *Wiki revisited* - the 2 additional sessions we had planned (maybe Pete, Monica, Judith would all want to drop in)
- *Podcast about the podcast* to wrap up the first season?
  - Maybe invite the Streamyard creators themselves sometime.

** BACK Book meetings                                             :handbook:
- Pick one weekday morning and one weekend?
- Announce on social media
** BACK Get podcast contributors lined up & committed              :podcast:
- Contact, spreadsheet, checklist
- Can each podcast become a chapter?
** BACK Podcast checklist can become a chapter                     :podcast:
- W/ Vitor a potential reader...
** BACK Blog about progress?                                       :website:
- Share Sacha's guide and start doing it!
** BACK Develop an Outreach pattern                                :podcast:
** BACK Convert Berkeley 3 week into next pitch [50%]               :course:
- (50% done, but need to figure out who we are actually pitching to!)
- Can draw on the longer version for Tufts as needed
- Melanie and Howard are interested
  - [ ] Start by making a natural extension of the 3wk v and compression of the Tufts v
  - [ ] Set up little sessions to do the course, maybe doing 30 minute or longer sessions to build up the topics
  - [ ] Outreach to students as appropriate
  - [ ] Diploma for completing the course - origami
