#+title: Course
#+roam_tags: SUB

#+begin_quote
It’s not peeragogy unless it’s collaborative: simultaneously, we can’t expect people to “get it” unless we co-create opportunities to “do with us”.

A set of interactive exercises that help people wrap their hearts and minds around peeragogy can help us understand if it’s working.

In the context of ‘education’ this may be a renegade activity; in workplace cultures, open learning may also be unfamiliar. But peeragogy thrives in open source settings!
#+end_quote

One of the reasons for writing the [[file:peeragogy_handbook_v4.org][Peeragogy Handbook v4]] is that we
didn’t think that the predecessor was actually sufficiently used (or
sufficiently useful, if we’re honest). We included a short syllabus we
called [[file:action.org][Peeragogy in action]], but it didn’t seem to catch on.  So we
figured we should deliver a course about Peeragogy ourselves
somewhere, using the /Handbook/ as the course text.  At first we were
looking around for the right venue, but we also figured we could just
pilot the course ourselves any time.  So we’ve been working on that.

* Next steps

- For now “course” is [[https://peeragogy.org/tags][one of the tags]] used on peeragogy.org, but it should probably develop into its own pattern.

