#+TITLE: Discerning a pattern
#+FIRN_ORDER: 60

* The Definition:
     :PROPERTIES:
     :CUSTOM_ID: the-definition
     :END:

Discerning patterns helps us build our vocabulary or repertoire for
peer-learning projects. (The classic example of an architectural pattern
is "A place to wait" -- a type of space found in many architectural and
urban design projects.)

* The Problem:
     :PROPERTIES:
     :CUSTOM_ID: the-problem
     :END:

We might notice an underlying pattern if something repeats, and if we're
paying attention. However, unless we make a record of the patterns we
notice, others cannot will not learn from our experience, and with time,
we'll forget what we learned.

* The Solution:
     :PROPERTIES:
     :CUSTOM_ID: the-solution
     :END:

Writing down patterns achieves at least two things: it helps us pay
attention and notice patterns in the first place, and it provides a
concrete summary of collective experience that is relatively easy for
others to engage with and extend. Once a pattern is detected, give it a
title and write down how the pattern works.

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

People may not be in the habit of writing down patterns that they
observe, and they are not likely to do it if the task is not made easy
and painless. Some projects that use the design pattern methodology have
developed detailed templates to gather information, but this then needs
to be processed by experts. We've tried to use a simple template that is
not much different from what you'd find in any short textual abstract,
to help make it easy to contribute new patterns. Understanding how a
given pattern relates to other patterns already listed in in the catalog
-- or to the wider context -- is not something that can be easily
encapsulated with templates. But it is still well worth trying to
express.

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

What do the patterns we've observed say about the self-selection
processes of the group? For instance, it's possible that a widespread
interest in organic gardening, say, may indicate the participants are
oriented to cooperation, personal health, or environmental activism.
What can we learn about the Peeragogy project from our collected
patterns?
