#+TITLE: Emergent Roadmap
#+FIRN_ORDER: 17

#+BEGIN_QUOTE
  This section reprises the "What's Next" steps in all the previous
  patterns, offering another view on the project *Roadmap* in its
  emergent form.
#+END_QUOTE

*** ▶ Peeragogy
    :PROPERTIES:
    :CUSTOM_ID: peeragogy
    :END:

We intend to revise and extend the patterns and methods of peeragogy to
make it a workable model for learning, inside or outside of
institutions.

*** ▶ Roadmap
    :PROPERTIES:
    :CUSTOM_ID: roadmap
    :END:

If we sense that something needs to change about the project, that is a
clue that we might need to record a new pattern, or revise our existing
patterns.

*** ▶ Reduce, reuse, recycle
    :PROPERTIES:
    :CUSTOM_ID: reduce-reuse-recycle
    :END:

We've converted our old pattern catalog from the /Peeragogy Handbook/
into this paper, sharing it with a new community and gaining new
perspectives. Can we repeat that for other things we've made?

*** ▶ Carrying capacity
    :PROPERTIES:
    :CUSTOM_ID: carrying-capacity
    :END:

Making it easy and fruitful for others to get involved is one of the
best ways to redistribute the load. This often requires skill
development among those involved; compare the pattern.

*** ▶ A specific project
    :PROPERTIES:
    :CUSTOM_ID: a-specific-project
    :END:

We need to build specific, tangible "what's next" steps and connect them
with concrete action. Use the Scrapbook to organize that process.

*** ▶ Wrapper
    :PROPERTIES:
    :CUSTOM_ID: wrapper
    :END:

We have prototyped and deployed a visual "dashboard" that people can use
to get involved with the ongoing work in the project. Let's improve it,
and match it with an improved interaction design for peeragogy.org.

*** ▶ Heartbeat
    :PROPERTIES:
    :CUSTOM_ID: heartbeat
    :END:

Identifying and fostering new and new working groups is a task that can
help make the community more robust. This is the time dimension of spin
off projects described in Reduce, reuse, recycle.

*** ▶ Newcomer
    :PROPERTIES:
    :CUSTOM_ID: newcomer
    :END:

A more detailed (but non-limiting) "How to Get Involved" walk-through or
"DIY Toolkit" would be good to develop. We can start by listing some of
the things we're currently learning about.

*** ▶ Scrapbook
    :PROPERTIES:
    :CUSTOM_ID: scrapbook
    :END:

After pruning back our pattern catalog, we want it to grow again: new
patterns are needed. One strategy would be to "patternize" the rest of
the /Peeragogy Handbook./
