#+TITLE: Foreword
#+FIRN_ORDER: 1

I was invited to lecture at UC Berkeley in January, 2012, and to involve
their faculty and their graduate students in some kind of seminar, so
[[http://vimeo.com/35685124][I told the story of how I've used social
media in teaching and learning]] - and invited them to help me create a
handbook for self-learners.

I called it the Peeragogy Handbook. I met twice on the Berkeley campus
in the weeks following the lecture with about a dozen Berkeley faculty
and graduate students. We also had a laptop open with Elluminate, an
online platform that enabled video chatting and text chat, enabling
people around the world who were interested in the subject, who I
recruited through Twitter and email, to also participate in this
conversation. All of the faculty and grad students at Berkeley dropped
out of the project, but we ended up with about two dozen people, most of
them educators, several of them students, in Canada, Belgium, Brazil,
Germany, Italy, Mexico, the UK, USA, and Venezuela who ended up
collaborating on a voluntary effort to create this Peeragogy Handbook,
at [[http://peeragogy.org/][peeragogy.org]]. We all shared an interest
in the question: "If you give more and more of your power as a teacher
to the students, can't you just eliminate the teacher all together, or
can't people take turns being the facilitator of the class?"

Between the time nine years ago, when I started out using social media
in teaching and learning, clearly there's been an explosion of people
learning things together online via Wikipedia and YouTube, MOOCs and
Quora, Twitter and Facebook, Google Docs and video chat, and I don't
really know what's going to happen with the institutions, but I do know
that this wild learning is happening and that some people are becoming
more expert at it.

I started trying to learn programming this summer, and I think that
learning programming and doing programming must be very, very different
now from before the Web, because now, if you know the right question to
ask, and you put it into a search query, there's someone out there on
StackOverflow who is already discussing it. More and more people are
getting savvy to the fact that you don't have to go to a university to
have access to all of the materials, plus media that the universities
haven't even had until recently. What's missing for learners outside
formal institutions who know how to use social media is useful lore
about how people learn together without a teacher. Nobody should ever
overlook the fact that there are great teachers. Teachers should be
trained, rewarded, and sought out. But it's time to expand the focus on
learners, particularly on self-learners whose hunger for learning hasn't
been schooled out of them.

I think that we're beginning to see the next step, which is to develop
the methods -- we certainly have the technologies, accessible at the
cost of broadband access -- for self-learners to teach and learn from
each other more effectively. Self-learners know how to go to YouTube,
they know how to use search, mobilize personal learning networks. How
does a group of self-learners organize co-learning?

In the Peeragogy project, we started with a
[[http://socialmediaclassroom.com/host/peeragogy/][wiki]] and then we
decided that we needed to have a mechanism for people who were
self-electing to write articles on the wiki to say, OK, this is ready
for editing, and then for an editor to come in and say, this is ready
for Wordpress, and then for someone to say, this has been moved to
WordPress. We used a forum to hash out these issues and met often via
Elluminate, which enabled us to all use audio and video, to share
screens, to text-chat, and to simultaneously draw on a whiteboard. We
tried Piratepad for a while. Eventually we settled on WordPress as our
publication platform and moved our most of our discussions to Google+.
It was a messy process, learning to work together while deciding what,
exactly it was we were doing and how we were going to go about it. In
the end we ended up evolving methods and settled on tools that worked
pretty well. We tackled key questions and provided resources for dealing
with them: How you want to govern your learning community? What kinds of
technologies do you want to use, and why, and how to use them? How are
learners going to convene, what kind of resources are available, and are
those resources free or what are their advantages and disadvantages. We
were betting that if we could organize good responses to all these
questions, a resource would prove to be useful: Here's a resource on how
to organize a syllabus or a learning space, and here are a lot of
suggestions for good learning activities, and here's why I should use a
wiki rather than a forum. We planned the Handbook to be an open and
growable resource -- if you want to add to it, join us! The purpose of
all this work is to provide a means of lubricating the process of
creating online courses and/or learning spaces.

Please use this handbook to enhance your own peer learning and please
join our effort to expand and enhance its value. The people who came
together to create the first edition -- few of us knew any of the
others, and often people from three continents would participate in our
synchronous meetings -- found that creating the Handbook was a training
course and experiment in peeragogy. If you want to practice peeragogy,
here's a vehicle. Not only can you use it, you can expand it, spread it
around. Translators have already created versions of the first edition
of the handbook in Spanish, and Italian, and work is in progress to
bring these up to date with the second edition. We've recently added a
Portuguese translation team: more translators are welcome.

What made this work? Polycentric leadership is one key. Many different
members of the project stepped up at different times and in different
ways and did truly vital things for the project. Currently, over 30
contributors have signed the CC Zero waiver and have material in the
handbook; over 600 joined our Peeragogy in Action community on G+; and
over 1000 tweets mention peeragogy.org. People clearly like the concept
of peeragogy -- and a healthy number also like participating in the
process.

We know that this isn't the last word. We hope it's a start. We invite
new generations of editors, educators, learners, media-makers,
web-makers, and translators to build on our foundation.

Howard Rheingold, Marin County, January, 2014

