#+TITLE: Forums
#+FIRN_ORDER: 36

#+BEGIN_QUOTE
  Forums are web-based communication media that enable groups of
  people to conduct organized multimedia discussions about multiple
  topics over a period of time. Selecting the right kind of platform
  for forum conversations is important, as is know-how about
  facilitating ongoing conversations online. Forums can be a powerful
  co-learning tool for people who may have never met face-to-face and
  could be located in different time zones, but who share an interest
  in co-learning.  Asynchronous media such as forums (or simple email
  distribution lists or [[http://www.youtube.com/watch?v=VVFbqHhkb-k][Google Docs]]) can be an important part of a
  co-learning toolkit that also include synchronous media from
  face-to-face meetups to [[http://www.google.com/+/learnmore/hangouts/][Google+ Hangouts]] or webinars via [[http://www.blackboard.com/Platforms/Collaborate/Products/Blackboard-Collaborate.aspx][Blackboard
  Collaborate]], [[http://www.adobe.com/products/adobeconnect.html][Adobe Connect]], or the open source webconferencing tool,
  [[http://www.bigbluebutton.org/][Big Blue Button]]).
#+END_QUOTE

* What is a forum and why should a group use it?
    :PROPERTIES:
    :CUSTOM_ID: what-is-a-forum-and-why-should-a-group-use-it
    :END:

A forum, also known as a message board,
[[http://en.wikipedia.org/wiki/Bulletin_board_system][bbs]], threaded
discussion, or conferencing system, affords asynchronous, many-to-many,
multimedia discussions for large groups of people over a period of time.
That means that people can read and write their parts of the discussion
on their own schedule, that everyone in a group can communicate with
everyone else, and that graphics, sounds, and videos can accompany text.
The best forums index discussion threads by topic, title, tag, date,
and/or author and also keep track of which threads and entries (also
known as posts) each logged-in participant has already read, making it
possible to click on a "show me all the new posts and threads" link each
time a participant logs in. This particular form of conversational
medium meets the need for organizing conversations after they reach a
certain level of complexity. For example, if twenty people want to
discuss five subjects over ten days, and each person makes one comment
on each subject every day, that makes for one thousand messages in each
participant's mailbox. On email lists, when the conversation drifts from
the original topic, the subject line usually does not change, so it
makes it difficult to find particular discussions later.

Forums make possible a new kind of group discussion that unfolds over
days, weeks, and months, in a variety of media. While blogs are
primarily about individual voice, forms can be seen as the voice of a
group. The best forum threads are not serial collections of individual
essays, but constitute a kind of discourse where the discussion becomes
more than the sum of its individual posts. Each participant takes into
account what others have said, builds on previous posts, poses and
answers questions of others, summarize, distill, and concludes.

This short piece on
[[http://www.lehigh.edu/~indiscus/doc_guidelines.html][guidelines for
discussion board writing]] is useful, as is this short piece on
[[http://academiccommons.org/commons/essay/shaping-culture-conversation][shaping
a culture of conversation]]. Lively forums with substantial conversation
can glue together the disparate parts of a peeragogy group -- the
sometimes geographically dispersed participants, texts, synchronous
chats, blogs, wikis and other co-learning tools and elements. Forum
conversations are an art in themselves and forums for learning
communities are a specific genre. Reading the resources linked here --
and communicating about them -- can help any peeragogy group get its
forums off to a good start

* How to start fruitful forum discussions:
    :PROPERTIES:
    :CUSTOM_ID: how-to-start-fruitful-forum-discussions
    :END:

In most contexts, starting a forum with a topic thread for introductions
tends to foster the sense of community needed for valuable
conversations. [[http://www.rheingold.com/texts/artonlinehost.html][This
short piece on how to host good conversations online]] offers general
advice. In addition to introductions, it is often helpful to start a
topic thread about which new topic threads to create -- when everybody
has the power to start a new thread and not everybody knows how forums
work, a confusing duplication of conversations can result, so it can be
most useful to make the selection of new topic threads a group exercise.
A topic thread to ask questions about how to use the forum can prevent a
proliferation of duplicate questions. It helps to begin a forum with a
few topic threads that invite participation in the context of the
group's shared interest "Who is your favorite photographer" for a group
of photographers, for example, or "evolution of human intelligence" for
a group interested in evolution and/or human intelligence. Ask
questions, invite candidate responses to a challenge, make a provocative
statement and ask for reactions.

Whether or not you use a rubric for assessing individual participants'
forum posts, this guide to
[[http://www.wpi.edu/Academics/ATC/Collaboratory/Idea/boards.html][how
forum posts are evaluated]] by one professor can help convey the
difference between a good and a poor forum conversation:

/4 Points -/The posting(s) integrates multiple viewpoints and weaves
both class readings and other participants' postings into their
discussion of the subject.

/3 Points -/The posting(s) builds upon the ideas of another participant
or two, and digs deeper into the question(s) posed by the instructor.

/2 Points -/A single posting that does not interact with or incorporate
the ideas of other participants' comments.

/1 Point -/A simple "me too" comment that neither expands the
conversation nor demonstrates any degree of reflection by the student.

/0 Points -/No comment.

* Selecting a forum platform
    :PROPERTIES:
    :CUSTOM_ID: selecting-a-forum-platform
    :END:

- You don't want a forum for discussions among two or three people; you
  do want a forum for discussions among half a dozen or five thousand
  people.
- You don't want a forum for exchanges of short duration (an hour, a day
  or two) among any number of people; you do want a forum for ongoing
  conversations that can continue for months.
- You don't want a forum if blogs with comment threads will do -- blogs
  with comments afford group discourse, but is not easily indexed and
  discourse gets complicated with more than a dozen or so bloggers and
  commenters.

If you do want to select a platform for forum discourse, you will want
to decide whether you have the technical expertise available to install
the software on your own server or whether you want to look for a hosted
solution. Cost is an issue.

Fortunately, an online forum maven by the name of
[[http://thinkofit.com/whoweare.htm][David Wooley]] has been keeping an
up-to-date list of available software and services for more than a
decade:

- [[http://thinkofit.com/webconf/forumsoft.htm][Forum Software for the
  Web]]
- [[http://thinkofit.com/webconf/hostsites.htm][Forum and Message Board
  Hosting Services]]

These
[[https://docs.google.com/document/d/1D606u7SfVD3p7xH0lbf2mOO1hIdX97r7kVe753hSYeE/edit][2003
suggestions on how to choose a forum]] by Howard Rheingold can be
helpful. If blogs with comments afford a kind of networked
individualistic discourse, and video conferencing emulates face-to-face
meeting, forums can be seen as a channel for expression of the group
voice. When people react to and build on each other's comments, they can
learn to act as a collective intelligence as well as a collection of
individuals who are communicating in order to learn.

 

