#+TITLE: Introduction
#+FIRN_ORDER: 1.1

#+BEGIN_QUOTE
  We live where no one knows the answer and the struggle is to figure
  out the question. [1]
#+END_QUOTE

Welcome to the /Peeragogy Handbook/! We want to kick things off with a
candid confession: we're not going to pretend that this book is perfect.
In fact, it's not an ordinary book at all. The adventure starts when you
get out your pen or pencil, or mouse and keyboard, and begin marking it
up. It gets kicked into high gear when you join /Peeragogy in Action/.
You'll find a lot of friendly support as you write, draw, or dance your
own peeragogical adventure. But first, what is /peeragogy/?

Peeragogy is a flexible framework of techniques for peer learning and
peer knowledge production. Whereas pedagogy deals with the transmission
of knowledge from teachers to students, peeragogy is what people use to
produce and apply knowledge together. The strength of peeragogy is its
flexibility and scalability. The learning mind-set and strategies that
we are uncovering in the Peeragogy project can be applied in classrooms,
hackerspaces, organizations, wikis, and interconnected collaborations
across an entire society.

The /Peeragogy Handbook/ is a compendium of know how for any group of
people who want to co-learn any subject together, when none of them is
an expert in the particular subject matter -- learning together without
one traditional teacher, especially using the tools and knowledge
available online. What we say in the /Handbook/ draws extensively on our
experiences working together on the /Handbook/ -- and our experiences in
other collaborative projects that drew us here in the first place. The
best way to learn about peeragogy is to do peeragogy, not just read
about it. Towards that end, coauthors and fans of the /Handbook/ have an
active Google+ community, conveniently called /Peeragogy in Action/. We
maintain a regular schedule of weekly meetings that you're welcome to
join. The /Handbook/ includes a short syllabus, which also called
"Peeragogy in Action", and you can work through this with your own group
as you read through the book.

You're warmly invited to combine your local projects with the global
effort, and get involved in making the next edition of the /Handbook/.
That doesn't necessarily require you to do extensive writing or editing.
We're always interested in new use cases, tricky problems, and
interesting questions. In fact, our view is that any question is a good
question.

Here are some of the ways in which the current edition of the Handbook
is /not perfect/. You're welcome to add to the list! These are places
where you can jump in and get involved. This list gives a sense of the
challenges that we face putting peeragogy into action.

* Scrapbook of Peeragogical Problems
  :PROPERTIES:
  :CUSTOM_ID: scrapbook-of-peeragogical-problems
  :END:

** Maintaining a list of useful resources
   :PROPERTIES:
   :CUSTOM_ID: maintaining-a-list-of-useful-resources
   :END:

We include references and recommended reading in the /Handbook/, and
there are a lot more links that have been shared in the /Peeragogy in
Action/ community. It's a ongoing task to catalog and improve these
resources -- including books, videos, images, projects, technology, etc.
In short, let's "Reduce, Reuse, Recycle"! As a good start, Charlotte
Pierce has been maintaining a spreadsheet under the heading "survey" in
our Google Drive.

** Developing a really accessible DIY tool-kit
   :PROPERTIES:
   :CUSTOM_ID: developing-a-really-accessible-diy-tool-kit
   :END:

A short "workbook" containing interviews and some activities follows
this introduction, but it could be much more interactive. Amanda Lyons
and Paola Ricaurte made several new exercises and drawings that we could
include. A more developed workbook could be split off from the handbook
into a separate publication. It would be great to have something simple
for onramping. For example, the workbook could be accompanied by video
tutorials for new contributors.

Paola Ricaurte points out that a really useful book will be easy to
sell. For teachers interested in peeragogy, this needs to be something
that can be use in workshops or on their own, to write in, to think
through issues. We're partway there, but to improve things, we really
need a better set of activities.

The next time Paola or someone else uses the handbook or workbook to run
a workshop, she can say, "turn to this page, let's answer this question,
you have 10 minutes." There are lots of places where the writing in the
handbook could be made more interactive. One technique Paola and Amanda
used was turning "statements" from the handbook into "questions."

** Crafting a visual identity
   :PROPERTIES:
   :CUSTOM_ID: crafting-a-visual-identity
   :END:

Amanda also put together the latest cover art, with some collaboration
from Charlotte using inDesign. A more large-scale visual design would be
a good goal for the 4th Edition of the book. Fabrizio Terzi, who made
the handbook cover art for the 1st Edition, has been working on making
our website more friendly. So, again, work is in progress but we could
use your help.

** Workflow for the 4th edition
   :PROPERTIES:
   :CUSTOM_ID: workflow-for-the-4th-edition
   :END:

We've uploaded the content of the book to Github and are editing the
"live" version of the site in Markdown. For this and previous print
editions, we've converted to LaTeX. There are a number of workflow
bottlenecks: First, people need to be comfortable updating the content
on the site. Second, it would be good to have more people involved with
the technical editing work that goes into compiling for print. Remember,
when we produce an actual physical handbook, we can sell it. In fact,
because all co-authors have transferred their copyright in this book to
the Public Domain, /anyone/ can print and sell copies, convert the
material into new interactive forms, or do just about anything with it.

** Translations
   :PROPERTIES:
   :CUSTOM_ID: translations
   :END:

Translating a book that's continually being revised is pretty much a
nightmare. With due respect to the valiant volunteer efforts that have
been attempted so far, it might be more convenient for everyone involved
to just pay professional translators or find a way to foster a
multi-lingual authoring community, or find a way to create a more robust
process of collective translation. Ideas are welcome, and we're making
some small steps here. More on this below.

** Next steps? What's the future of the project?
   :PROPERTIES:
   :CUSTOM_ID: next-steps-whats-the-future-of-the-project
   :END:

In short: If we make the Handbook even more useful, then it will be no
problem to sell more copies of it. That is one way to make money to
cover future expenses. It's a paradigmatic example for other business
models we might use in the future. But even more important than a
business model is a sense of our shared vision, which is why we're
working on a "Peeragogy Creed" (after the Taekwondo creed, which exists
in various forms, one example is [2]). No doubt you'll find the first
version on peeragogy.org soon! Chapter [[./distributed_roadmap.html][7]]
contains a further list of practical next steps for the project.

** References
   :PROPERTIES:
   :CUSTOM_ID: references
   :END:

1. Joshua Schimel, 2012. "Writing Science", Oxford University Press.

2. Taekwondo Student Creed, World Martial Arts Academy,
   [[http://www.worldtaekwondo.com/handbook.htm]]

