#+TITLE: Isolation
#+FIRN_ORDER: 44

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

Many projects that are ostensibly oriented towards "the commons"
nevertheless want to funnel participants into "their way" of thinking
about things. Be careful with that, it's a slippery slope to total
isolation.

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

This problem is actually dual: with a too-narrow focus, collaboration is
impossible. However, with an overly-wide focus, things are chaotic in
other ways.

* Solution:
     :PROPERTIES:
     :CUSTOM_ID: solution
     :END:

#+BEGIN_QUOTE
  *Félix Guattari*: Imagine a fenced field in which there are horses
  wearing adjustable blinkers, and let's say that the "coefficient of
  transversality" will be precisely the adjustment of the blinkers. If
  the horses are completely blind, a certain kind of traumatic encounter
  will be produced. As soon as the blinkers are opened, one can imagine
  that the horses will move about in a more harmonious way.
  ([[http://nine.fibreculturejournal.org/][Quoted by Andrew Murphy]],
  himself quoting Gary Genosko)
#+END_QUOTE

Like the underlying problem, the solution is has two sides to it: you
can avoid isolation by becoming highly transversal -- or avoid noise and
chaos by blinkering yourself and shutting out other things.

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

The challenge, of course, is that it's hard not to over-correct. The
moderate interpretation of the quote is that it's good to be open, but
not too open. We need to allow for uncertainty, but not be completely
vague. Not so easy. (See also:
[[http://peeragogy.org/antipatterns/navel-gazing/][Navel Gazing]].)

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

We recently submitted an abstract called "Escape from Peeragogy Island"
to a geography conference talking about the spatiality of peer
production. The idea behind this article is that we feel like we've come
up with something great with the Peeragogy project, but we're going to
be a bit isolated if it's not transparently useful to others. If we
can't explain why it's a great idea, then it's not entirely clear how
great of an idea it actually is.
