#+TITLE: Magical Thinking
#+FIRN_ORDER: 46

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

While we could imagine an ideal information processing system that would
(magically) come with all solutions pre-built, a more realistic approach
recognizes that real problem solving always takes time and energy.

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

Given a difficult problem, we usually want to take a shortcut.

* Solution:
     :PROPERTIES:
     :CUSTOM_ID: solution
     :END:

Magical thinking robs a context of its "process" or "motion". The more
completely we fall back on "traditional" modes of doing things
(including magical ones) the less we stand to learn. It's also true that
traditions and habits can serve a useful function: they can massively
simplify and streamline, and adopting some healthy habits can free up
time and energy, making learning possible. But if we try something new
and imagine that things work the way they always have (e.g. sign up for
a course and get told what to do, then do it and pass), we can run into
trouble when the situation doesn't match our preconceptions.

* Example:
     :PROPERTIES:
     :CUSTOM_ID: example
     :END:

Joe Corneli's 2011 DIY Math course at P2PU went quite badly. Students
signed up hoping to learn mathematics, but none of them had very
concrete goals about what to learn, or very developed knowledge about
how to study this subject. This was what the class was supposed to help
teach. However, it seemed as if the students felt that signing up for
the course would "magically" give them the structure they needed. Still,
it's not as if the blame can be placed entirely on the students in this
case. Building a learning space with no particular structure and saying,
"go forth and self-organize!" is not likely to work, either. The one
saving grace of DIY Math is that the course post-mortem informed the
development of the paragogy principles (see page ): it was not a mistake
we would repeat again.

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

If we already "knew", 100%, how to do peeragogy, then we would not stand
to learn very much by writing this handbook. Difficulties and tensions
would be resolved "in advance". We know this, but readers may still
expect "easy answers".

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

Fast-forwarding a few years from the DIY Math experiment: as part of the
PlanetMath project, we are hoping to build a well-thought-through
example of a peer learning space for mathematics. One of the ideas we're
exploring is to use patterns and antipatterns (exactly like the ones in
this catalog) as a way not only of designing a learning space, but also
of talking about the difficulties that people frequently run into when
studying mathematics. Building an initial collection of Calculus
Patterns may help give people the guide-posts they need to start
effectively self-organizing.
