#+TITLE: Messy with lurkers
#+FIRN_ORDER: 47

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

#+BEGIN_QUOTE
  *Gigi Johnson*: (1) Co-learning is Messy. It needs time, patience,
  confusion, re-forming, re-norming, re-storming, etc. Things go awry
  and part of norms needs to be how to realign. (2) Co-learning is a
  VERY different experience from traditional teacher-led learning in
  terms of time and completion. It is frustrating, so many people will
  lurk or just step in and out, the latter of which is very different
  from what is acceptable in traditonal learning. Online learning
  programs are painted with the brush now of an "unacceptable" 50%
  average non-completion rate. Stanford's MOOC AI class, which started
  out with +100,000 people, had 12% finish. If only 12% or 50% of my
  traditional class finished, I'd have a hard time getting next
  quarter's classes approved!
#+END_QUOTE

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

#+BEGIN_QUOTE
  *Tomlinson /et al./*: More authors means more content, but also more
  words thrown away. Many of the words written by authors were deleted
  during the ongoing editing process. The sheer mass of deleted words
  might raise the question of whether authoring a paper in such a
  massively distributed fashion is efficient.
#+END_QUOTE

* Solution:
     :PROPERTIES:
     :CUSTOM_ID: solution
     :END:

People have to join in order to try, and when joining is low-cost, and
completion low-benefit, it is not surprising that many people will
"dissipate" as the course progresses. The "messiness" of co-learning is
interesting because it points to a sort of "internal dissipation", as
contributors bring their multiple different backgrounds, interests, and
communication styles to bear.

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

If we were to describe this situation in the traditional subject/object,
sender/receiver terms of information theory, we would say that peer
production has a "low signal to noise ratio", and we would tend to think
of it as a highly inefficient process. However, it may be more
appropriate (and constructive) to think of meanings as co-constructed as
the process runs, and of messiness (or meaninglessness) as symptomatic,
not of peer production itself, but of deficiencies or infelicities in
shared meaning-making and "integrating" features.

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

What comes out of thinking about the anti-pattern is that we need to be
careful about how we think about "virtues" in a peer production setting.
It is not just a question of being a "good contributor" to an existing
project, but of continually improving the methods that this project uses
to make meaning.

* References:
     :PROPERTIES:
     :CUSTOM_ID: references
     :END:

1. Tomlinson, B., Ross, J., André, P., Baumer, E.P.S., Patterson, D.J.,
   Corneli, J., Mahaux, M., Nobarany, S., Lazzari, M., Penzenstadler,
   B., Torrance, A.W., Callele, D.J., Olson, G.M., Silberman, M.S.,
   Ständer, M., Palamedi, F.R., Salah, A., Morrill, E., Franch, X.,
   Mueller, F., Kaye, J., Black, R.W., Cohn, M.L., Shih, P.C., Brewer,
   J., Goyal, N., Näkki, P., Huang, J., Baghaei, N., and Saper, C.,
   [[http://altchi.org/submissions/submission_wmt_0.pdf][Massively
   Distributed Authorship of Academic Papers]], /Proceedings of
   Alt.Chi/, Austin Texas, May 5--10 2012 (10 page extended abstract),
   ACM, 2012,

2. Yochai Benkler, and Helen Nissenbaum (2006). "Commons-based Peer
   Production and Virtue." /Journal of Political Philosophy/ 14.4 :
   394-419.

3. Paul Kockelman (2010). "Enemies, parasites, and noise: How to take up
   residence in a system without becoming a term in it" /Journal of
   Linguistic Anthropology/ 20.2: 406-421
