#+TITLE: Misunderstanding power
#+FIRN_ORDER: 48

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

#+BEGIN_QUOTE
  *Wikipedia*: Zipf's law states that given some corpus of natural
  language utterances, the frequency of any word is inversely
  proportional to its rank in the frequency table. Thus the most
  frequent word will occur approximately twice as often as the second
  most frequent word, three times as often as the third most frequent
  word, etc. [1]
#+END_QUOTE

Related formulations, called power laws, model the
[[http://www2.econ.uu.nl/users/marrewijk/geography/zipf/index.htm][size
of cities]], and describe
[[http://pricetags.wordpress.com/2010/10/26/kleibers-law-growth-and-creativity-in-cities/][energy
use in animals]] and social network effects. Creativity and other social
network effects -- like crime -- are more prevalant in large cities.
Power laws also describe the forces governing
[[http://shirky.com/writings/powerlaw_weblog.html][online
participation]]. But it is easy to forget this.

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

How many times have we been at a conference or workshop and heard
someone say (or said ourselves) "wouldn't it be great if this energy
could be sustained all year 'round?" Or in a classroom or peer
production setting, wondered why it is that everyone does not
participate equally. "Wouldn't it be great if we could increase
participation?" But participation in a given population will fall off
according to some power law (see Introduction to Power Laws in
[[http://www.theuncertaintyprinciple.danoff.org/v2i3.html][The
Uncertainty Principle, Volume II, Issue 3]]). It would be an illusion to
assume that everyone is coming from a similar place with regard to the
various literacies and motivations that are conducive to participation.

* (Bogus) Solution:
     :PROPERTIES:
     :CUSTOM_ID: bogus-solution
     :END:

It can be tempting to adopt a "provisionist" attitude, and say: "If we
change our system we will equalize participation and access."

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

Power laws are an inherent epiphenomenon of network flows. If you can
adjust the way the way the network is shaped, for example, through
[[http://peeragogy.org/practice/moderation/][moderatation]], then you
may be able to change the "exponent" in the power law. But even so,
"equality" remains a largely abstract notion. Note, also, that
participation in a given activity tends to fall off over time. It's easy
to imagine writing a hit song or a best selling novel, but hard to pull
this off, because it takes sustained effort over time. See the
anti-pattern
[[http://peeragogy.org/antipatterns/magical-thinking/][Magical
Thinking]].

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

As Paul Graham wrote about programming languages -- programmers are
typically "satisfied with whatever language they happen to use, because
it dictates the way they think about programs" -- so too are people
often "satisfied" with their social environments, because these tend to
dictate the way they think and act in life. Nevertheless, if we put our
minds to it, we can become more "literate" in the patterns that make up
our world and the ways we can effect change.

* References:
     :PROPERTIES:
     :CUSTOM_ID: references
     :END:

1. [[http://en.wikipedia.org/w/index.php?title=Zipf%27s_law&oldid=575709945][Zipf's
   law]]. (2013). In /Wikipedia, The Free Encyclopedia/.

2. Graham, P. (2001). [[http://www.paulgraham.com/avg.html][Beating the
   averages]].
