#+TITLE: Moderation
#+FIRN_ORDER: 49

Moderation seems to have a double meaning: there's moderation as in
moderation in all things and moderation as in keeping a discussion going
smoothly. Actually, both of them are about the same thing.

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

[[http://peeragogy.org/organizing-a-learning-context/participation/][Participation]]
in online forums tends to follow a "power law," with vastly unequal
engagement.

* Solution:
     :PROPERTIES:
     :CUSTOM_ID: solution
     :END:

If you want to counteract this tendency, one possibility would simply be
for the most active participants to step back, and moderate how much
they speak. This is related the the
[[http://peeragogy.org/patterns-usecases/patterns-and-heuristics/carrying-capacity/][Carrying
Capacity]] pattern and the
[[http://peeragogy.org/practice/antipatterns/misunderstanding-power/][Misunderstanding
Power]] anti-pattern: check those out before you proceed.

* Examples:
     :PROPERTIES:
     :CUSTOM_ID: examples
     :END:

Occupy Wall Street used a technique that they called the
"[[http://en.wikipedia.org/wiki/Progressive_stack][progressive stack]]."
There are lots of other strategies to try.

#+BEGIN_QUOTE
  *The Co-Intelligence Institute*: Why is a fishbowl more productive
  than debate? The small group conversations in the fishbowl tend to
  de-personalize the issue and reduce the stress level, making people's
  statements more cogent. Since people are talking with their fellow
  partisans, they get less caught up in wasteful adversarial games.
#+END_QUOTE

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

In a distributed project, there are many side-conversations, and it is
impossible (and would be undesirable) for any one person to moderate all
of them. The difficulty occurs if one of these conversations becomes
uncomfortable for one or more participants, for whatever reason. Rather
than depending on one central moderator, it's useful for everyone in the
project to be aware of the principles underlying effective moderation,
and apply them together even in small side-projects.

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

We recently ran a Paragogical Action Review to elicit feedback from
participants in the Peeragogy project. Some of them brought up
dissatisfactions, and some of them brought up confusion. Can we find
ways to bring these concerns front-and-center, without embarrassing the
people who brought them up?
