#+TITLE: Navel Gazing
#+FIRN_ORDER: 50

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

The difficulty breaks down like this:

1. Certainly we cannot get things done just by talking about them.

2. And yet, feedback can be useful, i.e., if there are mechanisms for
   responding to it in a useful fashion.

3. The associated anti-pattern is a special case of the prototypical
   Batesonian [[http://en.wikipedia.org/wiki/Double_bind][double bind]],
   "the father who says to his son: go ahead, criticize me, but strongly
   hints that all effective criticism will be very unwelcome" [1],
   p. 88.

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

Criticism is not always useful. Sometimes it is just "noise".

* (Bogus) Solution:
     :PROPERTIES:
     :CUSTOM_ID: bogus-solution
     :END:

It's tempting to create "open" systems that inadvertantly replicate the
double bind -- by being open to criticism, but unable to act on it
effectively.

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

A long list of criticisms that haven't been dealt with is maybe better
than no communication at all, but it's also a tell-tale sign of deeper
dissatisfaction. It's better to make sure you have enough bandwidth (see
[[http://peeragogy.org/patterns-usecases/patterns-and-heuristics/carrying-capacity/][Carrying
Capacity]]) for dealing with a given class of problems and issues.
Adjust your focus accordingly, but be careful (see
"[[http://peeragogy.org/antipatterns/isolation/][Isolation]]").

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

We have hinted that, in this project,
[[http://peeragogy.org/how-to-use-this-handbook/][effective criticism is
very welcome]]! But understanding what makes criticism effective is, in
general, still a research problem.

* Reference:
     :PROPERTIES:
     :CUSTOM_ID: reference
     :END:

1. Deleuze, G., and Guattari, F. (2004). /Anti-oedipus/. Continuum
   International Publishing Group.
