#+TITLE: Participation
#+FIRN_ORDER: 30

#+BEGIN_QUOTE
  Methods of managing projects, including learning projects, range from
  more formal and structured to casual and unstructured. As a
  facilitator, you'll see your peeragogy community constantly adjust, as
  it seeks an equilibrium between order and chaos, ideally allowing
  everyone to be involved at their own pace without losing focus, and in
  such a manner that the collective can deliver.
#+END_QUOTE

For teachers reading this, and wondering how to use peeragogy to improve
participation in their classrooms, it's really quite simple: reframe the
educational vision using peeragogical eyes.  Recast the classroom as a
community of people who learn together, the teacher as facilitator, and
the curriculum as a starting point that can be used to organize and
trigger community engagement.  However, just because it's simple doesn't
mean it's easy!  Whatever your day job may be, consider: how well do the
various groups you participate in work together -- even when the members
ostensibly share a common purpose?  Sometimes things tick along nicely,
and, presumably, sometimes it's excruciating.  What's your role in all
of this?  How do /you/ participate?

* Guidelines for participation
   :PROPERTIES:
   :CUSTOM_ID: guidelines-for-participation
   :END:

- Accept that some people want to watch what is going on before jumping
  in. This doesn't mean you have to keep them hanging around forever.
  After a while, you may un-enroll people who don't add any value to the
  community. In our Peeragogy project, we've asked people to explicitly
  re-enroll several times. Most do renew; some leave.
- Accept that people may only contribute a little: if this contribution
  is good it will add value to the whole.
- Understand that you can not impose strict deadlines on volunteers;
  adjust targets accordingly.
- Let your work be "open" in the sense described in
  Wikipedia's [[http://en.wikipedia.org/wiki/Wikipedia:Neutral_point_of_view][Neutral
  Point of View]] policy.
- Give roles to participants and define some "energy centers" who will
  take the lead on specific items in the project.
- Organize regular face-to-face or online meetings to talk about
  progress and what's needed in upcoming days/weeks.
- Ask participants to be clear about when they will be ready to deliver
  their contributions.
- Have clear deadlines, but allow contributions that come in after the
  deadline -- in general, be flexible.
- Add a newcomer section on your online platform to help new arrivals
  get started. Seasoned participants are often eager to serve as
  mentors.

When we think about project management in an organization, we often
relate to well-established tools and processes. For example, we can use
the [[http://www.pmi.org/PMBOK-Guide-and-Standards.aspx][Project
Management Body of Knowledge]] (PMBOK) as a standard. For the Project
Management Institute (PMI) and many workers, these standards are seen as
the key to project success. In classical project management, tasks and
deadlines are clearly defined. We will, for example, use
[[http://en.wikipedia.org/wiki/PERT][Program Evaluation and Review
Technic]] (PERT) to analyze and represent tasks. We often represent the
project schedule using
a [[http://en.wikipedia.org/wiki/Gantt_chart][Gantt chart]]. Those are
just two of the project management tools that illustrate how
"mainstream" project management rests firmly on an engineering
background. In these very structured projects, each actor is expected to
work exactly as planned and to deliver his part of the work on time;
every individual delay can potentially lead to a collective delay.

Peeragogy projects may be, naturally, a bit different from other
settings, although we can potentially reuse both formal and informal
methods of organization.  For example, unlike a typical wiki -- or
classroom -- peeragogy projects often expect to break
the [[http://en.wikipedia.org/wiki/1%25_rule_%28Internet_culture%29][90/9/1
rule]]. Keep in mind that some participants may not contribute all the
time -- but one really good idea can be a major contribution.  See the
anti-pattern
"[[http://peeragogy.org/practice/antipatterns/misunderstanding-power/][Misunderstanding
Power]]" for some further reflections on these matters.

How are we doing? If we consider our basic population to be those in our
Google+ community, then as of January 2014, over 4% have contributed to
the handbook -- pretty good.  However, we have yet to reach a
contribution profile like 70/20/10. It's important to remember that --
especially in a volunteer organization -- no one can "make"' other
people participate, and that all the lists of things to do are for
nought if no one steps in to do the work.  For this reason, if anything
is going to happen, what's needed are /realistic/ estimates of available
work effort. Finally, in closing this section, we want to emphasize that
measures of participation offer only a very rough proxy for measures of
learning, although the two are clearly related.

