#+TITLE: Play
#+FIRN_ORDER: 21

Once more we're back to the question, "What makes learning fun?" There
are deep links between play and learning. Consider, for instance, the
way we learn the rules of a game through playing it. The first times we
play a card game, or a physical sport, or a computer simulation we test
out rule boundaries as well as our understanding. Actors and
role-players learn their roles through the dynamic process of
performance. The resulting learning isn't absorbed all at once, but
accretes over time through an emergent process, one unfolding further
through iterations. In other words, the more we play a game, the more we
learn it.

In addition to the rules of play, we learn about the subject which play
represents, be it a strategy game (chess, for example) or simulation of
economic conflict. Good games echo good teaching practice, too, in that
they structure a single player's experience to fit their regime of
competence (cf. Vygotsky's zone of proximal learning, a la Gee [1]).
That is to say a game challenges players at a level suited to their
skill and knowledge: comfortable enough that play is possible, but so
challenging as to avoid boredom, eliciting player growth. Role-playing
in theater lets performers explore and test out concepts; see Boal [2].
Further, adopting a playful attitude helps individuals meet new
challenges with curiousity, along with a readiness to mobilize ideas and
practical knowledge. Indeed, the energy activated by play can take a
person beyond an event's formal limitations, as players can assume that
play can go on and on [3].

#+BEGIN_QUOTE
  *Douglas Thomas and John Seely Brown*: "All systems of play are, at
  base, learning systems." [4]
#+END_QUOTE

Games have always had a major social component, and learning plays a key
role in that interpersonal function. Using games to build group cohesion
is an old practice, actually a triusm in team sports.

It is important to locate our peeragogical moment in a world where
gaming is undergoing a renaissance. Not only has digital gaming become a
large industry, but gaming has begun to infiltrate non-gaming aspects of
the world, sometimes referred to as "gamification." Putting all three of
these levels together, we see that we can possibly improve co-learning
by adopting a playful mindset. Such a playful attitude can then mobilize
any or all of the above advantages. For example,

- Two friends are learning the Russian language together. They invent a
  vocabulary game: one identifies an object in the world, and the other
  must name it in Russian. They take turns, each challenging the other,
  building up their common knowledge.
- A middle-aged man decides to take up hiking. The prospect is somewhat
  daunting, since he's a very proud person and is easily stymied by
  learning something from scratch. So he adopts a "trail name", a
  playful pseudonym. This new identity lets him set-aside his
  self-importance and risk making mistakes. Gradually he grows
  comfortable with what his new persona learns.
- We can also consider the *design* field as a useful kind of playful
  peeragogy. The person /playing the role/ of the designer can select
  the contextual frame within which the design is performed. This frame
  can be seen as the /rules/ governing the design, the artifact and the
  process. These rules, as with some games, may change over time.
  Therefore the possibility to adapt, to tailor one's activities to
  changing context is important when designing playful learning
  activities. (And we'll look at some ways to design peer learning
  experiences next!)

Of course, "game-based learning" can be part of standard pedagogy too.
When peers create the game themselves, this presumably involves both
game-based learning and peer learning. Classic strategy games like
[[http://senseis.xmp.net/?MythOfOrigin][Go]] and
[[http://www.amazon.com/Chess-Success-Using-Strengths-Children/dp/0767915682][Chess]]
also provide clear examples of peer learning practices: the question is
partly, what skills and mindsets do our game-related practices really
teach?

#+BEGIN_QUOTE
  *Socrates*: "No compulsory learning can remain in the soul ...In
  teaching children, train them by a kind of game, and you will be able
  to see more clearly the natural bent of each."
#+END_QUOTE

*** Exercises that can help you cultivate a playful attitude
    :PROPERTIES:
    :CUSTOM_ID: exercises-that-can-help-you-cultivate-a-playful-attitude
    :END:

- Use the [[http://www.rtqe.net/ObliqueStrategies/][Oblique Strategies]]
  card deck (Brian Eno and Peter Schmidt, 1st edition 1975, now
  available in its fifth edition) to spur playful creativity. Each card
  advises players to change their creative process, often in surprising
  directions.
- Take turns making and sharing videos. This online collaborative
  continuous video storytelling involves a group of people creating
  short videos, uploading them to YouTube, then making playlists of
  results. Similar to [[http://clipkino.info/][Clip Kino]], only online.
- Engage in theater play using Google+ Hangout. e.g. coming together
  with a group of people online and performing theatrical performances
  on a shared topic that are recorded.

** References
   :PROPERTIES:
   :CUSTOM_ID: references
   :END:

1. Gee, J. P. (1992). /The social mind: Language, ideology, and social
   practice/. Series in language and ideology. New York: Bergin &
   Garvey.

2. Boal, A. (1979). /Theatre of the oppressed/. 3rd ed. London: Pluto
   Press.

3. Bereiter, C. and Scadamalia, M. (1993). /Surpassing ourselves, an
   inquiry into the nature and implications of expertise/. Peru,
   Illinois: Open Court.

4. Douglas Thomas and John Seely Brown (2011), /A New Culture of
   Learning: Cultivating the Imagination for a World of Constant
   Change/. CreateSpace.

5. Malone, T.W. (1981), Toward a Theory of Intrinsically Motivating
   Instruction, /Cognitive Science/, 4, pp. 333-369

