#+title: Problem

The /Introduction/ of our book focuses on explaning the problem that
Peeragogy addresses.  The link below goes to the existing introductory
material from v3 of the book.

- [[file:introduction.org][Introduction]]

On this page we present a few other short introductory texts we have
written more recently that could feed into a revised introduction.

* Problem as pattern
- Every problem has a problem: how do we articulate the problem clearly?
- The solution to the problem of the problem: to put ourselves in a situation where we face the problem head on.
- The problem has three primary contexts: philosophy, design, and peeragogy.
* Understanding Peeragogy to Maximize Resources and Efficiencies

by Lisa Snow MacDonald, from https://docs.google.com/document/d/1w2JZhpkrYYKknpJSSJgz23PPYxI31Cu1eWvw8I9ZraM/edit#

** Peeragogy: What Is It?

‘Peeragogy’ was coined in comparison to pedagogy. Pedagogy is a term that is often referred to in the context of educational environments and classrooms. Within the US, pedagogy often carries a hierarchical connotation, where there is a teacher who disperses work and information to students who do what they are told. If we step back, we can see these hierarchical constructs occur outside the classrooms. They occur in business, volunteer organizations, families, churches, etc.  Peeragogy was also coined in contrast with the hierarchical approach. At its core is the idea of peer-to-peer learning. This can occur in classrooms as well as businesses, volunteer organizations, families, churches, etc.

The key is that at their core both ‘peeragogy’ and ‘pedagogy’ describe how individuals orient themselves to work together in groups to accomplish designated tasks. They just do so in very different ways.

** Peeragogy: Why Is It Important

It is important to distinguish these different environments and approaches because the same words take on different meanings depending upon the context.  For example, think of the word ‘teacher’ in a pedagogical context. How would the teacher act? What sorts of things would the teacher be doing? What are the behavioral expectations of students?  Now consider the word ‘teacher’ in a peer-to-peer learning environment? How would the teacher act? What sorts of things would the teacher be doing? What are the behavioral expectations of students?

Within a pedagogical environment, we would expect there to be a designated teacher who provides information to students. The students should be working to understand what is being told to them by the teacher. Students would be expected to keep pace with the instructor and not move ahead or fall behind — regardless, though, the teacher will continue to move forward.  Within a peeragogical environment, we would expect the teacher to act more as a facilitator to make sure that the students are free to exchange information and ideas. Students may ask questions of the teacher and other students. Students would move more or less at their own pace as they master topics.

If the significance of this still has not hit home, consider what would happen if a teacher with a pedagogical approach tries to teach students who are expecting a peeragogical method (or vice versa). The likelihood of confusion, anger and frustration is high, because each person will think that they are acting as they are supposed to, they may even sense that the others seem dedicated to progress, but in the end, together, they will find it difficult to work together effectively.  They may communicate and seemingly agree on next steps only to find that their efforts are wasted. And that is because the environments are so different many words (not just the word ‘teacher’) have different connotations.  Understanding and being conscious of these different environments is important, and having a vocabulary that allows us to distinguish between them is the first critical step — hence the introduction of the term peeragogy as a comparison to pedagogy.

As mentioned earlier, the models we have in mind influence other ways in which we interact. Businesses, volunteer organizations, families, churches and even sports teams can be approached in very different ways. Because they involve different people, with different backgrounds and different expectations, commonly used terms like ‘leader’, ‘team’, and ‘teamwork’ can look very different. When the discrepancies are great and not understood, the result can be frustration.  The possibility of confusion is enhanced because consistent approaches may not be used within the same organizations or even by the same people within that organization. Often people assume they are on the same page until it is too late.  Things have gone badly, and people are confused as to why, and are struggling to fix it. To make matters worse, they don’t even know what they are trying to fix or what broke.  I have experienced this first hand. Fortunately, two experiences happened less than 24 hours apart and I was quickly able to identify the issue.

The first experience was when I found out that Chivas USA won the MLS (Major League Soccer) Public Relations Department Award for the year. Chivas USA was only three years old at the time. I was involved in building their day-of-game PR staff. We started from scratch — from recruitment to training. It was a long process, because we had to train and achieve baseline competencies in all positions, and then we cross trained people so that we had depth at different positions and each person would have a better understanding of other things that were happening. As we grew, so did our confidence. I worked hard to empower the staff. While I set up team assignments and coordinated things, they were empowered to be proactive, to make recommendations, and to fix things that seemed to be going wrong. Over time, we got to the point where the group would do bigger games at different venues without me and not miss a beat. We had achieved a high level of trust even among the most skittish of venue officers. That the Chivas Public Relations Department won the award was a validation of the work we had done and how effective our team was.

After receiving this surprising news (I did not even know there was an award for this), I walked into my other job at a Japanese automaker the following day, and soon found myself sitting in a conference room with my boss going through my yearly performance appraisal. Her major comment was that I was not a “team player”. I struggled to understand how she came to this conclusion. If anything, I had been told that I was too much of a team player in the past, so hearing the complete opposite was disorientating. I asked to her to give examples and explain. Examples were few, and an explanation was not forthcoming.  But it hit me a little bit later when I was driving home. We were working from two different definitions of ‘team’. The Chivas definition was one in which all members were actively engaged and empowered. We were all expected to be proactive problem solvers, and we had worked together to ensure that everyone had the tools to be good at problem solving. We succeeded in doing more than building a team: our vision worked relative to what was going on across the entire soccer league. However, at the auto company, my boss’s definition of ‘team’ was top down. Within the broader organization, participation was encouraged, however, for her and others immediately around her, this was not their working definition. To test this, I took a big step back following the performance appraisal, and I just followed orders. I sat quietly (not in a pouty way!) — but I did not offer suggestions, ideas or comments. Or, if I did make any comments, I would just respond positively to what others had said. Even though I understood the environment in which we were working and the expectations of our customers, and my boss and other higher-ups were all new to the area, I refrained from engaging too much. In some respects though it was easy, because I had already learned that my thoughts were not welcomed.

I had got to the point where my input largely consisted of trying to summarize the best of their different proposals into another proposal so we could move forward and everyone would have some ownership of the final proposal, and indicating where they might run into a problem because, even though I knew they did not want to hear it, I felt I had a moral obligation to raise the issue if things were going to run off the cliff.

In the latter case I would raise the issue and then let it go, knowing that I had done what I could. They would not listen, which was ok and their choice. I did not argue with them. I just pointed it out. Anyway, I stopped even doing this. And here is the amazing thing. I was right. Incredibly right. Within a short period of time, I was praised for how much better I was doing, and they seemed almost surprised at how quickly I changed. (Understanding the issue was key to this.)

That these two things happened within 24 hours led me to the answer quickly, but I also need to highlight again that many people are not consistent with their use of terms like ‘team’. For example, the same people mentioned above, who wanted me to sit quietly, were furious when executives or upper management did not take their suggestions. They seemed to expect their suggestions to be implicitly blessed, pointing to a more peeragogical way of thinking. And indeed the organization as a whole was peeragogical. If these people had understood how the organization worked, their ideas could have been implemented without executive approval in many cases if they had talked to the affected groups. The affected groups would then have explained to those same executives what they were doing and why. In one way, they seemed to have a peeragogical approach, in that they wanted their voices to be heard by those above them, but they were really still working with a hierarchical mindset, because they were looking for executive approval to force their ideas on others.  All of this can be confusing, but understanding that these apparent inconsistencies are out there in the wild, and trying to understand how they work, is much better than being unaware and getting blindsided.

** Peeragogy: Business and Peeragogy

I am going to turn to my experiences in business.  Frankly, if you are in business, you cannot afford to not understand peeragogy and how it works because it is the way that you can tap into and reap the benefits from your greatest asset — your employees.  And, your employees (for most if not all company owners) are your competitive advantage.  You may be selling a product comparable to your competitors. Your sourcing costs may be comparable. Your transportation costs, comparable. While you can make incremental improvements in all of these things, there is one thing that will always make you different than your competitors and that is your workforce. Your employees. How well you utilize their talents. To what extent are they empowered. They can teach you. And they can teach others.  There can be a tendency in businesses to think of each person as an atom, a singular unit that contributes to the larger whole. In manufacturing environments (on a manufacturing line), each person or ‘atom’ may have their output registered to make sure that they are keeping up.  That said, this type of thinking can really affect the efficiencies and potential of the organization, because people, like atoms, can be transformed into something else when around different atoms. Think of two hydrogen atoms and one oxygen atom. Separate they are combustible gases. Together, as a molecule, they form water, which is used to put out fires.

Still not clear? Take two people and a couch. Individually they cannot move the couch. Only when they work together can they move the couch. If they work together well, they will be able to move the couch effectively and efficiently.  So, when you have two people who work well together, you have the benefit of both of their talents separately AND you have the benefit plus ‘alpha’ of things that they can do together that they could never do on their own. In a very real sense, 1 + 1 = 3 or = 4 or = 5.  By understanding peeragogy, you can increase your ‘alpha’ without having to pay for additional headcount. You may also find your employees are happier and empowered, which reduces sick time and turn over.

You can also think about this in terms of departments, and not just individuals. Working to develop feedback between departments can also reap huge benefits. When departments need to interact but they have a silo or inwardly-focused approach, misunderstandings can often develop, and frustration can build over time. One group may not understand that they are doing something which is making things more difficult for another group. In fact, it sometimes happens that the one group may be doing something thinking that it is helping the other group, only to be shocked and puzzled when the other group responds, not with thankfulness, but with anger and frustration. Having departments talk to each other about the challenges they face and encouraging collective problem solving (not finger pointing) can have huge benefits. Even if the problems can’t be solved at that time, the departments will understand the larger issues and be more sympathetic, instead of frustrated, and better able to work together in the future. Additionally, there will be organizational alliances looking for joint solutions which can result in quicker identification and implementation.  And the craziest part? You can make these changes without spending a cent. You just need to change your thinking and language.

** Peeragogy: Its Power Is Unlimited

You still may be wondering if it is really such a big deal.

Before I go further though, I need to define “it” a bit better. “It” is the alpha that you tap into using a peeragogical approach.

“It” is the extra you get when you bring people together, that extra that you could not get if you had them working separately. It is the conversion of hydrogen and oxygen into water, or the ability to move a couch. It is the alpha. And you get it without having to invest in more atoms or more people. It is what people will do naturally when you let them, if they have the platform.  Don’t believe me?

Well, today, examples are endless. Encarta, an on-line encyclopedia developed by Microsoft, was essentially done in by Wikipedia. This public wiki relies on volunteers and contributors to write new entries, check entries for accuracy and make corrections. Wiki provides the platform and the “rules”, but others did the rest — and at no pay.

There are other examples of the power of people working collectively in groups. More and more software is being developed by volunteers on their own time (‘open source’). People have collectively developed open source programs in which you can edit photos, edit video, and create animated videos. While it takes time to develop them, many of these programs are becoming as good as their much more expensive counterparts, and the open source programs are continuously updated by thousands of contributors and are typically free for anyone to use.

** Peeragogy: Your Secret To Success

Just like Microsoft discovered with Encarta, regular software manufacturers are going to find it harder and harder to charge enough to cover their development costs and to keep up with these open, collaborative, communities. That is not the point though. The point is that people will work together — even for free — to accomplish big things. People are driven by the need to feel like they are valued and contributing. If you can tap into this, you will be doing well. This is your alpha. This is when your employees are coming in motivated and looking to make a difference.  

** Peeragogy: If It Is So Great, Why Have I Not Heard About This Before?

You may have heard elements of peeragogy picked up without the larger context or word to describe it. You may have heard of ‘servant leader’ or ‘flat organization’. These point to systems which may have peeragogical elements — the number of those elements and their successfulness in implementation can vary widely.  Another example is kaizen, which is the idea of “continuous improvement”. It was first introduced in a big way to the US from Japan in the 80’s in the auto industry. At the time the assembly lines of American automakers would keep moving regardless of what happened. If there was a problem, the workers had to just keep going and the problems would be fixed at the end, or at the dealership, or indeed discovered by the customer later. The Japanese kaizen system allowed for the assembly line workers to stop the line so that problems could be fixed and addressed right away. This shifted the paradigm from a hierarchical model where the line kept moving no matter what and workers did their best to keep up without a voice or much control as to the quality, to a paradigm where the workers had a voice, had input, and were involved in problem solving right away. This is one of the ways in which Japanese were able to produce much higher quality cars at the time.  

While you may see things that may point to aspects of peeragogy, it can sometimes be hard to implement in some organizations and with some people. There are several reasons for this.

** Peeragogy: And Why Isn’t Everyone Doing This?

There are cultural and psychological reasons why peeragogy is not tapped into the extent to which it could be. Incidentally, I understand that cultural influences could also be considered psychological by some, which is another case of different terminologies: I will separate them for the purposes of this document. The key point is that that much of what is happening, regardless of its cultural or psychological origins, is happening at a subconscious level.

We are not actively making choices and decisions. We are running on autopilot with how we read situations and respond. This autopilot works well most of the time but, when it doesn’t, we are slow to recognize it and adjust effectively. Awareness of our autopilot processing is a huge first step. Instead of continuing on and getting more frustrated or angry, knowing that things may be going on under the surface and taking a step back — like I did in the example above with my manager — can get you to an understanding and a constructive adjustment more quickly.

At the highest level, culture can be an obstacle. In the US, we tend to focus on the “the big one” — the one who stands out. That person is often the one who seems to have power. This was demonstrated in the Michigan Fish Test. The participants were shown an aquarium with 3 big fish, a couple smaller fish, some plants, snails, and pebbles. US participants tended to notice the big fish in the aquarium, and to describe them in more detail, while not noticing or paying less attention to the smaller fish or the rest of the environment. Japanese participants noticed the details of the environment and were less focused on the big fish.

Your cultural predisposition can influence how you read and respond to situations in groups. Some of this makes establishing a healthy peeragogical environment slightly more difficult. If you’re from the US, the people who stand out — often the “take charge” type of people — are the ones who are considered more valuable. They are credited for their leadership. This more aggressive way of defining leadership often fits in better with a hierarchical approach. In peeragogical systems, there is more equality, with distributed power and influence. These are qualities that, by default, are more easily overlooked in US culture. (Readers from other cultures may be confused or wondering why I have made some statements that I have. Things that they may understand implicitly may not be understood or observed here in the US.)

There is another issue with US culture, and that is that we do not have a metaphor that jumps out when we explain peeragogy. Just saying “hierarchy”, for example, readily triggers several mental constructs which clarify what we are talking about and how things will be organized. Some examples include org charts and pyramids. However, at this point in time, there may be very few of such salient constructs that come to mind when we try to describe peeragogy.

Metaphors or mental constructs can act as a guide to help us understand and assimilate additional information quickly and easily. So, if we understand that we are working within a hierarchy, we can use our existing knowledge of hierarchies to determine how to respond to new information or situations. Since we may have fewer familiar constructs associated with peeragogy, finding common understanding and common ground can be more difficult to achieve and sustain. Additionally, since the hierarchical approach is so commonly and easily understood, people may also defer to it at times just out of convenience.

There are also personality differences. Some people embrace the hierarchy because they want to be at the top. In the DISC personality assessment, they are the “D” — that is how embedded it is. These people will do reasonably well in the hierarchical environment, but they will struggle in a peeragogy environment. So, if you are thinking about integrating peeragogy into your company or organization, it is very likely that you will have a person or two who will struggle and may not be able to make the transition. They may be long term employees, but if you are going for a peeragogical approach, you need to be ready to move them or fire them. If they are not willing to change, you are probably losing talent who would not thrive in the new environment. You may lose something whatever you do way. The question is “which people do you want to retain?” Then, make a commitment to make the changes you want and need to.

One other point, when someone is unwilling or unable to adapt, get them out of the situation and away from people who are working together as soon as possible. If you don’t, you may very well lose the people you need and end up with the person you don’t. They are like a poison and come in two types — one worse than the other, but both will get you, if they are ignored.  The first and worst are the people who need to dictate and direct people. They do not have the answers but act like they do. They are often unwilling to listen to others. The second poison is the person who just wants to do what they are told. They will wear away at a group over time, so you need to be aware of them. The key is that you need to know who may be resisting your efforts. Think of the example of the couch. You only get alpha if people actually work together.

That said, it is important to remember that I am not saying someone who has difficulty with peeragogy is a bad person. Yes, I understand, I just described them as a poison, and they are in that situation. This does not make them bad people. They are a mismatch for the environment and company. If your organization has been hierarchical, you have been losing people who prefer a peeragogical approach all along. Now you are shifting priorities. The people who prefer a hierarchical approach will find another environment, a better fit for them, and will be much happier in the long run.

One thing to note here is that, in peeragogy and business, there will be disagreements and these disagreements can be good. You don’t want to communicate that disagreeing is an issue. You don’t want to establish a group think situation. There are ways in which you can determine whether this is healthy disagreement and what is unhealthy. A full discussion of this is outside the scope of the current document. For now, just be aware that embracing peeragogy does not mean eliminating friction.

Remember that there are very real psychological reasons why a peeragogical approach can be difficult for some people.  For many people it will feel different, and different is often uncomfortable. Most of us were conditioned with hierarchy in school. We grew up in schools that had the traditional teachers at the front of the classroom who imparted information to us.

We also grow up with different familial models (see Lakoff’s classic work [1]), some where there is a strict father model (hierarchical) and some where there is a nurturant parent model (peeragogical). Lakoff shows that these two models inform how people approach and discuss politics. This shows how deeply embedded these models are, and how much of an impact they have on us.  Moving from one model to the other will feel uncomfortable, which may then trigger the need to feel in control. This need for control, if moving from a peeragogical approach to a hierarchical approach, could help the transition. However, when moving from a hierarchical approach to the peeragogical approach, the need to control may cause some problems. A hierarchical approach gives someone a sense of control. Not only does hierarchy impose a structure on the situation: with the structure often comes a reporting procedure so work is divided, possibly further sub-divided into a plan and timeline.

There are some well-known limitations to all this: the plans are never anywhere close to accurate, and the business becomes silo-driven as employees become focused on their particular area and less concerned about the actual results. As they become disconnected with the end result, they lose appreciation for the impact they are having and morale declines, and so does productivity over time. Additionally, and significantly, the plan and timelines are also often constructed without the input of some key people — the people on the front lines who actually do the work. Management or those higher up think that they understand how things work so they focus, not just on what to do, but also how to do it. This can be a huge mistake. I have seen this first hand several times. That said, it takes patience to learn to work in a peeragogical environment.

Some people may feel more comfortable moving forward. Movement to them has its own value. Working in a peeragogical environment, sometimes we would spend 30% to 40% of the time planning or preparing, without moving. It is easy to get nervous, but the key is that once we started going (implementing the plan), we needed far less time to execute. There may have been glitches, but things typically did not run off the tracks completely. There were very few times where everything needed to stop for a massive cleanup, because the planning time was also a time to educate everyone involved so they were aware of the relevant issues. These things were discussed up front and understood in advance so, not only was the plan more solid, there was a much better understanding of the issues at play when adjustments needed to be made.

Additionally, a peeragogical approach can feel a bit chaotic relative to a hierarchical approach. Org charts don’t mean as much because people in different parts of the company have critical roles in moving things through. The most appropriate person is involved in decisions and discussions. Their role is determined by what they can contribute to the project at that time, and not so much their title. This can be a bit disorientating when people are trying to understand what is happening using a familiar hierarchical mindset. They instinctively are looking for the leader of the group as designated on the org chart. Org charts in a peeragogy environment can be difficult to find, because they do not have as much significance as they do in other environments.

These are just some of the issues and challenges. Notice that none of the challenges are overcome with significant investment in machinery or intensive training. It starts simply with the words you use and how you use them. While there are challenges, there are strong psychological reasons why peeragogy is so powerful. When people feel empowered, they are productive and engaged. People also thrive in connecting. Remember that the power of groups, even loosely organized volunteers, can compete with large well organized companies. Remember the difference between Wikipedia and Encarta.

** Peeragogy: What is next?

This was a super high-level overview of my take on the subject. Further study of peeragogy can be useful because it provides a framework for understanding. It can also provide tools, such as design patterns, that may help you navigate through a transition until your organization becomes more accustomed to a new way of working.

I have been part of a peeragogy group that includes people from many different backgrounds from all over the world.  These folks may or may not agree with what I have written. My background and interest is pretty different from theirs. That said, we all understand the power of peeragogy and hope that others will too. And some of this document was informed based on discussions I have had with this group.

Together, and with many others, we completed a Peeragogy Handbook that is available here: http://peeragogy.github.io/

** Reference

[1] Lakoff G. Moral politics: How conservatives and liberals think. Chicago, IL: University of Chicago Press; 1996.

* 🐉 vs 🐒: A kaijū introduction to Peeragogy
** Abstract

Our workshop will introduce attendees to peeragogy: an interconnected collection of techniques for peer learning and peer production. The learning mind-set and strategies we are uncovering can be applied by students, teachers, groups of friends, communities of practice, hackerspaces, organizations, wikis, and/or networked collaborations across an entire society! In this workshop we put peeragogy into action as we break into small groups and play "Flaws of the Smart City", a futures studies game that imagines scenarios for the evolution of urban environments. After playing, each group will do a Project Action Review to reflect on lessons learned. Subsequently, the groups will present their PARs to the wider audience so everyone can learn from their experience and extract patterns. Finally, all attendees will "hive edit" a 500 to 1,000 word writeup of the workshop that will be included in the upcoming fourth edition of the Peeragogy Handbook.

** 🐉 vs 🐒: A kaijū introduction to Peeragogy (1 hour Workshop)

Connected Learning Summit 2021 Workshop Submission by Charlie Danoff, Joe Corneli and Howard Rheingold

** SIXTY MINUTE WORKSHOP TIMELINE

2 Minutes 30 Seconds - Video Intro to Peeragogy

7 Minutes 30 Seconds - Presentation of the workshop timeline and succinct description of the methods we will experiment with today — Project Action Review, Causal Layered Analysis, Design Patterns — as well as the rules of Flaws of the Smart City, allowing time for Q&A

30 Minutes - Play Flaws of the Smart City in small teams

5 Minutes – Each team does a Project Action Review

5 Minutes - Each group presents their PAR about how their game went, we take notes into the CLA template

10 Minutes - Hive-edit the CLA into a 500 to 1,000 word writeup of the experience to be included in the Peeragogy Handbook, including any design patterns that you noticed

** DESCRIPTION

The term kaijū translates literally as "strange beast". — Wikipedia

Since we started working together in the Peeragogy Project in 2012, we have used many methods to pursue our shared goal of learning more about peer learning and peer production by practicing them together! We modified the US Army’s After Action Review (2002) to create the Project Action Review, as a way to cultivate shared mindfulness. We have fed our reflections into futurologist Sohail Inayatullah’s Causal Layered Analysis (1998) to create varied answers to the question ‘What is our vision for change and how is progress measurable?’. Along the way, we also experimented with patterns, poetry, and play. In this one-hour workshop we will demonstrate the power of these and other peeragogical methods with audience volunteers. To begin with, we make the ‘audience’ disappear and replace it with a ‘concerned public’!

After a brief introduction to the methods mentioned above we will dive into playing a game called Flaws of the Smart City developed by the Design Friction collective. We are now no longer watching a talk: we are residents of a city that has begun to take on a mind of its own, mediated by a Guardian Angel or an Evil Genius — or perhaps a giant lizard with psychic powers, if you so choose.

We, as the concerned public, begin to relax into what we are doing enough to not be distracted by other things. We do not have any ulterior motives outside of the game. For example, when we are playing Flaws of the Smart City, we are not particularly worried about paying rent or publishing papers. We are not particularly worried about what our tablemates think about us: it is a fun game but it is not that serious. More or less we are embracing the phenomenon of being alive, here and now. To bring these ideas home through another sensory channel, we recommend that participants listen to the song “Shuffering and Shmiling” by Fela Kuti while they play. 

When we wrap up the game, each group will do a Project Action Review, addressing these questions:

1. Review the intention: what do we expect to learn or make together?
2. Establish what is happening: what and how are we learning?
3. What are some different perspectives on what’s happening?
4. What did we learn or change?
5. What else should we change going forward?

We will then report back and take notes into a shared outline, following the template provided by Inayatullah (op. cit., p. 820):

The first level is the ‘litany’—quantitative trends, problems, often exaggerated, often used for political purposes—(overpopulation, eg) usually presented by the news media.

The second level is concerned with social causes, including economic, cultural, political and historical factors (rising birthrates, lack of family planning, eg).

The third deeper level is concerned with structure and the discourse/worldview that supports and legitimates it (population growth and civilizational perspectives of family; lack of women’s power; lack of social security; the population/consumption debate, eg.).

The fourth layer of analysis is at the level of metaphor or myth. These are the deep stories, the collective archetypes, the unconscious dimensions of the problem or the paradox (seeing population as non-statistical, as community, or seeing people as creative resources, e.g.).

Lastly, we will co-edit this outline into a mixed media product — perhaps including narrative, poetry and images — reflecting on the process we have just experienced through the lens of a concept borrowed from religious studies (Batchelor, 2015): asking how does Peeragogy differ from other approaches? As regards the mixed medium presentation and experience as a whole, we take inspiration from the poet and visual artist Marcel Broodthaers (quoted by Wyma, 2016):

“I am now able to express myself on the edge of things, where the world of visual arts and the world of poetry might eventually, I wouldn’t say meet, but at the very frontier where they part.” 

** WORKS CITED

Batchelor, Stephen. (2015) After Buddhism: Rethinking the dharma for a secular age. Yale University Press.

Design Friction. (2016) Flaws of the Smart City. URL: http://www.flawsofthesmartcity.com/ 

Inayatullah, Sohail. (1998) “Causal layered analysis: Poststructuralism as method”. Futures,
Volume 30, Issue 8, October 1998, pp. 815-829.

Kuti, Fela. (1978) “Shuffering and Shmiling”. Coconut PMLP 1005 distributed by Phonogram Inc.

US Army. (2002). “Training the Force”. FM 7-0.

Wyma, Chloe. (2016) “Breaking Down Broodthaers: Three Keys to Understanding His Essential MoMA Retrospective” Artspace. URL: https://www.artspace.com/magazine/news_events/exhibitions/marcel-broodthaers-at-moma-53532 

* Next steps
** BACK Can we revise the text of Lisa’s Introduction adequately highlight the problem we’re addressing?
** BACK What about an intro to peeragogy for... project managers? … agile practitioners? … artists?
