#+TITLE: Quickstart Guide

- *Book* :: This book can help any group of people learn or create
  something together. You can read it online or download it with zero
  cost, or buy a paper copy, or fork a copy of your own to work on.
- *Podcast* :: The Peeragogy Podcast is available on multiple sites:
  Videos are available on YouTube.[fn:: [[https://www.youtube.com/playlist?list=PLG6fmEnfJR2yaWGiK0tSp8QSis4btdCzE][[[https://www.youtube.com/playlist?list=PLG6fmEnfJR2yaWGiK0tSp8QSis4btdCzE][https://www.youtube.com/playlist?list=PLG6fmEnfJR2yaWGiK0tSp8QSis4btdCzE]]]]]
- *Mailing List* :: Our main public discussions are on Google Groups
  Sign up there to get email and post to the wider contributor
  community.[fn:: [[https://groups.google.com/forum/#!forum/peeragogy][[[https://groups.google.com/forum/#!forum/peeragogy][https://groups.google.com/forum/#!forum/peeragogy]]]]]
  Remember to ask questions!  We also have a second mailing list that
  is focused on revisions to the Peeragogy Handbook.  It is hosted by
  the OSU Open Source Lab.[fn:: [[https://lists.osuosl.org/mailman/listinfo/peeragogy-handbook][https://lists.osuosl.org/mailman/listinfo/peeragogy-handbook]]]
- *Live Meetings* :: Public meetings appear on our public calendar.[fn:: [[https://calendar.google.com/calendar/embed?src=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com][[[https://calendar.google.com/calendar/embed?src=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com][https://calendar.google.com/calendar/embed?src=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com]]]]]
  You subscribe for updates via Google Calendar.[fn:: [[https://www.google.com/calendar/render?cid=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com][[[https://www.google.com/calendar/render?cid=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com][https://www.google.com/calendar/render?cid=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com]]]]]
  You can also subscribe with other software that reads the =.ics= format.[fn:: [[https://calendar.google.com/calendar/ical/3iq41odpn85s51mem8cgekmong%40group.calendar.google.com/public/basic.ics][https://calendar.google.com/calendar/ical/3iq41odpn85s51mem8cgekmong%40group.calendar.google.com/public/basic.ics]]]
- *Annotations* :: To comment on the Peeragogy Handbook please make an
  account at Hypothesis and use the mini-toolbar on the right-hand
  side of each page on peeragogy.org.[fn:: [[https://hypothes.is/][[[https://hypothes.is/][https://hypothes.is/]]]]]
  Comments from across the site are available.[fn:: [[https://hypothes.is/search?q=url%3Apeeragogy.org%2F*][[[https://hypothes.is/search?q=url%3Apeeragogy.org%2F*][https://hypothes.is/search?q=url%3Apeeragogy.org%2F*]]]]]
  You're also welcome to share reviews or comments elsewhere of course!
- *Organization* :: We’ve managed many of our projects through a Github "organization".[fn:: [[https://github.com/Peeragogy][[[https://github.com/Peeragogy][https://github.com/Peeragogy]]]]]
  The master copy of the Handbook content is on Github Pages.[fn:: [[https://github.com/Peeragogy/Peeragogy.github.io][[[https://github.com/Peeragogy/Peeragogy.github.io][https://github.com/Peeragogy/Peeragogy.github.io]]]]]
  Pull requests are welcome, but /Handbook/ editors are happy to take submissions in other formats as well.
- *Projects* :: We’re currently managing subprojects inside the /Handbook/
  itself using Emacs and Org Mode.  We made a guide for newcomers, but
  it might be better just to ask one of us.[fn:: [[https://github.com/PeeragogyLabs/PeeragogyORG/wiki][https://github.com/PeeragogyLabs/PeeragogyORG/wiki]]]
- *More details* :: Please have a look at this [[https://github.com/Peeragogy/peeragogy-handbook/wiki/Quickstart-guide][longer quickstart guide]]
  for more information about our tools and workflow, and more ways to
  get involved.


