#+title: Researching Peeragogy
#+FIRN_ORDER: 34

#+BEGIN_QUOTE
  This is an unfinished essay from 2001, found nearly a decade and a
  half later in a box of odds and ends. The essay foreshadows our
  ongoing research on peer produced peer learning, and also helps to
  highlight some of the difficulties associated with this enterprise.
#+END_QUOTE

* RESEARCH SKILL DEVELOPMENT PROGRAM
     :PROPERTIES:
     :CUSTOM_ID: research-skill-development-program
     :END:

*THE POINT.* This is an effort at understanding how research skills in
the mathematical sciences [but it could be any topic] can be acquired by
students.

*WHO WE ARE.* We are students at a state-funded liberal arts college
based in Sarasota, Florida [but it could be anyone]. Our school is
called New College. The emphasis of the program at New College is
self-directed learning.

*SELF-DIRECTED LEARNING.* Since people have free will and learn from
experience, self-directed learning could be said to take place wherever
people engage in any activity. However, this view is unfounded, and the
implication is false. Unstructured learning is more accurately
undirected. If learning is structured, say by a teacher, this does not
imply that it is self-directed, even given the free will of the learner
to participate. The choice to participate in learning is not the same as
directing the learning. Structure can impose the direction on a
(passive) learner. This does not mean that the presence of a teacher or
a system to learn implies that the student's learning is not
self-directed. The criterion we are looking for is that the student have
an active, ongoing and purposive role in deciding the structure of
his/her/its [e.g. in the case of computer programs] learning
environment. A teacher must be informed by and responsive to the
student's feedback, or the learning the student does under that
teacher's instruction is not self-directed.

*INTEGRATION OF RESEARCH AND EDUCATION.* In deciding upon a course of
study, it behooves the student, as he/she/it examines a potential
activity, to consider questions such as these, with the utmost care:

- What is the intellectual merit of the proposed activity?
- Is there sufficient access to resources?
- How well-conceived and organized is the proposed activity?
- To what extent does the proposed activity suggest and explore creative
  and original concepts?
- To what extent will it enhance possibilities for future work?
- What are the broader impacts of the proposed activity?
- What is the product?

If these questions are addressed well, the student will enter upon a
focused program and will have already at the beginning devised a
coherent plan for its satisfactory completion. Furthermore, the product
is likely to be a net benefit to society. The idea of traditional
education is that it is the student, with an increased knowledge and
skill base, who constitutes the product. His/her/its knowledge and
skills (upon exiting the educational program) are valued by society, and
he/she/it is willing to put forth during the program a commensurate
amount of blood, sweat, and tears (not to mention tuition and time) to
extract the valuable knowledge and skills. In scientific fields, one of
these skills is supposed to be the ability to do research. The idea that
"the best proof of someone's research ability is the research they have
done" has played a significant role in the way scientific education, and
the scientific enterprise, has been run in recent years. Research
experience at the undergraduate level is one of the top criteria
considered by graduate programs in science when they decide which
candidates to admit. It is not without reason, then, that national
programs for undergraduate researchers (most notably, the National
Science Foundation's Research Experiences for Undergraduates (REU)
summer programs) are highly competitive, taking only the best qualified
applicants nationwide. Many technical and land-grant universities have
internally- or industry-funded Undergraduate Research Opportunities
Programs (UROP) which offer financial awards to undergraduate students,
which enable them to collaborate with faculty on specialized research
projects in their joint field of interest, or to do original work on
their own. These programs make it possible for students to make research
a part of their background. In particular, such programs give students a
chance to see what it is like to work on open problems (usually the
problems devised by the program administrator or principal investigator;
occasionally on questions proposed by the student researchers
themselves). It goes without saying that such experiences are typically
only part of the curriculum. The NSF's vision of integrating research
and education is to have individuals concurrently assume
responsibilities as researchers, educators, and students, where all
engage in joint efforts that infuse education with the excitement of
discovery and enrich research through the diversity of learning
perspectives. The benefits of such a system are manifold. It is however
very difficult to implement in most educational contexts. A place like
New College, where the culture already is disposed towards student
self-direction, may be unique in its ability to foster an undergraduate
scientific curriculum based primarily on research. The questions listed
at the beginning of this section are the questions a researcher must
answer when initiating a research program for undergraduates. (They were
lifted from the NSF's summary of how they review REU proposals.) By
pointing out here that the same questions are the natural questions for
a student to ask when considering how to invest his/her/its time and
energy, we mean to point to the unique possibility afforded the
self-directed learner, namely: he/she/it can act as a researcher, an
educator, and a student concurrently, and, to a degree that is possible
for very few, harmoniously.

*RESEARCH AS A WAY OF LIFE (ADDITIONAL REVIEW CRITERIA SPECIFIC TO
REU).* There are other criteria considered by the NSF, for example, the
qualifications of the person who proposes the research project. This is
/prima facie/ difficult for undergraduates to fulfil satisfactorily.
Further criteria include:

- The appropriateness and value of the educational experience for the
  student participants, particularly the appropriateness of the research
  project(s) for undergraduate involvement and the nature of student
  participation in these activities.
- The quality of the research environment, including the record of the
  mentor(s) with undergraduate research participation, the facilities,
  and the professional development opportunities.
- Appropriateness of the student recruitment and selection plan,
  including plans for involving students from underrepresented groups
  and from institutions with limited research opportunities.
- Quality of plans for student preparation and follow-through designed
  to promote continuation of student interest and involvement in
  research.
- For REU sites, effectiveness of institutional commitment and of plans
  for managing the project and evaluating outcomes.

* Some afterthoughts, with the benefit of hindsight (2015)
     :PROPERTIES:
     :CUSTOM_ID: some-afterthoughts-with-the-benefit-of-hindsight-2015
     :END:

The idea that an undergraduate student could run an REU program is
perhaps not entirely ridiculous, but it is still extremely unlikely to
work -- as the essay points out. What is possible is for a student or
group of students to set up a website and collaborate informally online.
This is what Aaron Krowne did in around 2001, with PlanetMath.org. I
joined a few years later, as a graduate student in mathematics.
PlanetMath was a little bit like an always-on version of the project
outlined in the essay above. The main emphasis was on building a
mathematics encyclopedia, but some contributors were doing original
research and collaborating with each other. The site administrators and
assorted devotees were also doing a lot of meta-level thinking about how
the project could improve. In 2005 or thereabouts, I started a wiki
called AsteroidMeta to help organize those discussions. By this time, I
was no longer in the mathematics graduate programme: I had more or less
stopped going to classes a year earlier. My interests had more to do
with how computers could change the way people do mathematics than in
doing mathematics the way it had always been done. Myself and a few
other PlanetMath contributors published research papers on this theme in
a symposium on Free Culture and the Digital Library that Aaron helped
organize at Emory, where he was then Head of Digital Library Research.
Working on informal collaborations like this, and doing related open
source software development, I built a CV that helped me get into
another postgrad program in 2010. This time, in the United Kingdom,
where I was able to largely set my own research agenda from the start. I
focused on rebuilding the PlanetMath website (as described in the
/Handbook/ chapter on "New Designs for Co-Working and Co-Learning").
Presenting some of this work at Wikimania 2010, I met Charlie Danoff,
and when we later met online at P2PU, we decided to sit in on each
others first round of courses. As the term progressed, we
collaboratively developed a critique of the way things worked at P2PU
and suggested some principles that would guide improvement. We called
this "paragogy." When Howard Rheingold learned about this work from
Charlie, who was taking one of his online classes at RheingoldU, he
suggested the more accessible name "peeragogy." To our pleasant surprise
Howard then drew on his network of friends and fans to kick off the
Peeragogy project. Naturally, I joined, and was able to draw on what we
learned in my thesis. Unlike the previous time around, I also had a lot
of formal support from my supervisors, as well as a lot of
self-organized support from others, and I completed the program
successfully. In doing so, I began to accrue the credentials that would
be necessary for organizing a formally-funded research project like the
one outlined in the essay above. Doing this in the undergraduate
research setting would, of course, require interested undergraduates. At
the moment, I'm employed as a computer science researcher, exploring the
development of peer learning and peer production with the computational
"its" mentioned in the essay. The Peeragogy project continues to be a
great resource for collaborative research on research and collaboration.

