#+TITLE: Roles
#+FIRN_ORDER: 54

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

Educational interactions tend to have a number of different roles
associated with them. Everything could bifurcate from the "autodidact",
as in, (1) Autodidact, (2) Tutor-Tutee, (3) Tutor-Tutee-Peer, etc.,
until we have bursars, librarians, technicians, janitors, editors of
peer reviewed research journals, government policy makers, spin-off
industrial ventures and partnerships, and so on.

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

Even the autodidact may assume different roles at different points in
time - sometimes building a library, sometimes constructing a model,
sometimes checking a proof. The decomposition of "learning" into
different phases or polarities could be an endless theoretical task. The
simpler problem is to be aware of the roles that you and your teammates
have in the projects you're working on.

* Solution:
     :PROPERTIES:
     :CUSTOM_ID: solution
     :END:

We've described some exercises on
"[[http://peeragogy.org/can-we-work-together/][metacognition]]" that you
can apply when thinking about the roles that you're taking on and those
that you'd like to take on in your project.

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

Roles are often present "by default" at the start of a learning process,
and that they may change as the process develops. Both of these features
can be challenging, but they also present learning opportunities.

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

We've listed some of the roles for which we're seeking volunteers in
the[[http://peeragogy.org/peeragogy-org-roadmap/][Peeragogy.org
Roadmap]]: Volunteer Coordinator, Seminar Coordinator, Usability Guru,
Activities Master, and Tech lead. As with everything else in the
roadmap, this list should be reviewed and revised regularly, as the
roles are understood relative to the actual happenings in the Peeragogy
project.
