#+TITLE: Stuck
#+FIRN_ORDER: 57

* Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

Knowing how to make good use of "weak ties" is often seen as a "personal
strength".

#+BEGIN_QUOTE
  *Nancy Darling*: When we need a big favor or social or instrumental
  support, we ask our friends. We call them when we need to move a
  washing machine. But if we need information that we don't have, the
  people to ask are our weak ties. They have more diverse knowledge and
  more diverse ties than our close friends do. We ask them when we want
  to know who to hire to install our washing machine. [1]
#+END_QUOTE

The question is less to do with whether we are forming weak ties or
strong ties. We can be "peers" in either a weak or a strong sense. The
question to ask is whether our needs match our expectations!

* Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

In the peeragogy context, this has to do with how we interact.

#+BEGIN_QUOTE
  *One of us*: I am learning about peeragogy, but I think I'm failing to
  be a good peeragogue. I remember that Howard once told us that the
  most important thing is that you should be responsible not only for
  your own learning but for your peers' learning. [...] So the question
  is, are we learning from others by ourselves or are we helping others
  to learn?
#+END_QUOTE

If we are "only" co-consumers of information then this seems like a
classic example of a weak tie. We are part of the an "audience".

* (Bogus) Solution:
     :PROPERTIES:
     :CUSTOM_ID: bogus-solution
     :END:

Perhaps especially in an online, mediated, context, it is possible to
stay at the level of "weak ties." (Cf.
[[http://peeragogy.org/antipatterns/isolation/][Isolation]].)

* Challenges:
     :PROPERTIES:
     :CUSTOM_ID: challenges
     :END:

This strategy reveals its problems directly, if you ever need help
moving your washing machine.

* What's Next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

If we are actively engaging with other people, then this is a foundation
for strong ties. In this case of deep learning, our aims are neither
instrumental nor informational, but "interactional". Incidentally, the
"One of us" quoted above has been one of the most consistently engaged
peeragogues over the years of the project. Showing up is a good step --
you can always help someone else move their washing machine!

* Reference:
     :PROPERTIES:
     :CUSTOM_ID: reference
     :END:

Nancy Darling (2010).
[[http://www.psychologytoday.com/blog/thinking-about-kids/201005/facebook-and-the-strength-weak-ties][Facebook
and the Strength of Weak Ties]], /Psychology Today/.
