#+TITLE: Student Syllabus
#+FIRN_ORDER: 26

In either formal learning, informal learning or models which transition
between the two, there are many opportunities for learners to co-create
the syllabus and/or outline their own course of action. The /sage on the
stage/ of formal instruction must become at the most /a guide on the
side/ who acts as a coach appearing only when needed rather than as a
lecturer who determines the content that the learners need to master. In
the following inspirational but certainly not prescriptive examples, we
will focus on co-learning methods drawn from a Social Constructivist
perspective, which fits nicely here.

We offer a few examples below to show a range of learner centered
approaches. They all are based on co-learners hosting each other for one
of a number of digestible topics in the larger subject area or domain
that the group formed in order to explore. This can take place across a
number of media and timelines.

The following methods will result in each co-learner gaining deep
knowledge in a specific topic and moderate knowledge across several
topics. The unique joy of this approach is that no two cohorts will ever
be the same. The content will always be fresh, relevant, and changing. A
group can even reconvene with slightly or dramatically different topics
over and over using the same underlying process.

The appropriateness of the learner-created syllabus technique depends on
two factors: 1) the involvement of experts in the group and 2) the level
of proficiency of the group. In general, novices who may or may not have
a deep interest in the subject matter benefit from more structure and
experts who point to key concepts and texts. An example of this is the
university survey course for first or second year students who, we
assume, need more guidance as they enter the subject matter. Graduate
seminars are generally much more fluid, open dialogues between motivated
experts require little structure or guidance.

We also need effective methods for groups which contain novices,
experts, and everyone in between. In groups with a wide range of
expertise, it is important that each co-learner chooses to focus their
deep inquiry on a topic that they are less familiar with. This will
/even out/ the expertise level across the cohort as well as ensure that
a co-learner is neither bored nor dominating the dialogue.

** 3 example designs to structure the learning
   :PROPERTIES:
   :CUSTOM_ID: example-designs-to-structure-the-learning
   :END:

*** Weekly topics structure
    :PROPERTIES:
    :CUSTOM_ID: weekly-topics-structure
    :END:

One way to structure the course is to have each co-learner host a topic
each week. Perhaps multiple students host their topics in the same week.
This progression provides a rotation of presentations and activities to
support the entire group in engaging with the topics and challenges to
the thinking of the presenters in a constructive and respectful manner.

#+BEGIN_QUOTE
  /Pro:/ co-learners have discrete timelines and manageable chunks of
  responsibility.

  /Con:/ the format may become disjointed, and the depth of inquiry will
  likely be somewhat shallow.
#+END_QUOTE

*** Milestone based structure
    :PROPERTIES:
    :CUSTOM_ID: milestone-based-structure
    :END:

In this structure, each co-learner hosts their topics in parallel with
similar activities and milestones that the whole group moves through
together. Milestones can be set for a certain date, or the group can
/unlock/ their next milestone whenever all participants have completed
the previous milestone. This second milestone timeline can be great for
informal groups in which participation levels vary from week to week due
to external factors, and the sense of responsibility and game-like
levels can be motivating for many co-learners.

Each co-learner may start with a post of less than 500 words introducing
the topic on a superficial level. When everyone has done this, the group
might move on to posting questions to the post authors. Then, there may
be a summary post of the activity so far with critical recommendations
or insights.

#+BEGIN_QUOTE
  /Pro:/ co- learners have more time to digest a topic, formulate a
  complex schema, and generate deeper questions.

  /Con:/ it will be a few weeks before the topic level schema can form
  into a broader understanding of the subject matter or domain (seeing
  the big picture takes longer).
#+END_QUOTE

*** Relay learning structure.
    :PROPERTIES:
    :CUSTOM_ID: relay-learning-structure.
    :END:

This is similar to the milestone structure. However, co-learners rotate
topics. If one learner posts an introductory write-up on a topic the
first cycle, they may be researching questions on another topic in the
next cycle, posting a summary in a third, and then posting a summary on
their original topic in the fourth.

#+BEGIN_QUOTE
  /Pro:/ co-learners can experience responsibility for several topics.

  /Con:/ co-learners may receive a topic that is poorly researched or
  otherwise neglected.
#+END_QUOTE

** Content
   :PROPERTIES:
   :CUSTOM_ID: content
   :END:

*** A vast number of topics
    :PROPERTIES:
    :CUSTOM_ID: a-vast-number-of-topics
    :END:

Within a subject of mutual interest to a group, there are a considerable
number of topics or questions. What is important is that each co-learner
can take responsibility for a reasonably narrow area given the duration
of the course or the timeline of the group. Areas that are too broad
will result in a very superficial understanding, and areas that are too
narrow will result in a dull experience. For example, in marine biology,
topics such as "the inter-tidal zone" may be too broad for a course
cycle of a few weeks. Narrowing to one species may be too specific for a
course over a few months.

*** Learner generated topics
    :PROPERTIES:
    :CUSTOM_ID: learner-generated-topics
    :END:

Most cohorts will have some knowledge of the shared area of interest or
an adjacent area. It is a good idea to respect the knowledge and
experience that each member of the group brings to the table. A
facilitator or coordinator may generate a list of potential topic areas,
setting an example of the scale of a topic. We suggest that the
participants in the group are also polled for additions to the list. In
large courses, sending out a Google Form via email can be an effective
way to get a quick list with a high response rate.

*** Expert informed topics
    :PROPERTIES:
    :CUSTOM_ID: expert-informed-topics
    :END:

If there is no expert facilitator in the group, we suggest that the
cohort begin their journey with a few interviews of experts to uncover
what the main buzz words and areas of focus might be. One way to locate
this type of expert help is through contacting authors in the subject
matter on social networks, reviewing their posts for relevance, and
reaching out with the request.

We recommend two people interview the expert over video chat, for
example in a Hangout. One person conducts the interview, and one person
takes notes and watches the time. We strongly suggest that the interview
be outlined ahead of time:

#+BEGIN_QUOTE
  /Warm up/: Who are you, what are your goals, and why do you think this
  interview will help?

  /Foundational questions/: Ask a few questions that might elicit short
  answers to build rapport and get your interviewee talking.

  /Inquiry/: What people say and what they do can often be very
  different. Ask about topics required for mastery of the subject matter
  (e.g. What are the areas someone would need to know about to be
  considered proficient in this subject?). Also, ask
  [[http://en.wikipedia.org/wiki/Critical_Incident_Technique][questions
  that require storytelling]]. Avoid
  [[http://en.wikipedia.org/wiki/Superlative][superlative]] or
  [[http://en.wikipedia.org/wiki/Closed-ended_question][close-ended
  questions]].

  /Wrap up/: Thank the interviewee for his or her time, and be sure to
  follow up by sharing both what you learned and what you accomplished
  because he or she helped you.
#+END_QUOTE

** Shared goals and group norms
   :PROPERTIES:
   :CUSTOM_ID: shared-goals-and-group-norms
   :END:

*** Choosing useful outputs
    :PROPERTIES:
    :CUSTOM_ID: choosing-useful-outputs
    :END:

Getting together for the sake of sharing what you know in an informal
way can be fairly straightforward and somewhat useful. Most groups find
that a common purpose and output that are explicitly defined and
documented help to engage, motivate, and drive the group. For the
examples above, the group may decide to create a blog with posts on the
various topics or create a wiki where they can share their insights.
Other outputs can include community service projects, business
proposals, recommendations to senior management or administration, new
products, and more. The key is to go beyond sharing for sharing sake and
move toward an output that will be of use beyond the co-learning group.
This activity is best described in
[[http://www.elearnspace.org/Articles/connectivism.htm][Connectivist]]
theory as the special case of networked learning where we find evidence
of learning in collective action and/or behavioral change in groups
rather than a psychological or neurological process in individuals.

*** Group cohesion (a.k.a. the rules of the road)
    :PROPERTIES:
    :CUSTOM_ID: group-cohesion-a.k.a.-the-rules-of-the-road
    :END:

One challenge of this kind of collaboration is that each group will need
to decide on norms, acceptable practices and behaviors. Culturally
diverse groups in particular may run into communication or other issues
unless there is a way to create shared expectations and communicate
preferences.

One way to do this is with a team charter. This is a living document
where the initial rules of engagement can live for reference. The group
may add or edit this document over time based on experience, and that is
a welcome thing! This documentation is a huge asset for new members
joining the group who want to contribute quickly and effectively. Any
co-editing word processing program will work, but we strongly recommend
something that can be edited simultaneously and that lives in the cloud.
(Google Docs is convenient because you can also embed your Charter into
another site.)

Try starting with the following three sections, and allow some time for
the group to co-edit and negotiate the document between icebreakers and
kicking off the official learning process.

#+BEGIN_QUOTE
  /Mission:/ Why are you forming the group? What do you want to
  accomplish together?

  /Norms:/ Use
  [[http://en.wikipedia.org/wiki/Netiquette#Netiquette][netiquette]]? No
  [[http://en.wikipedia.org/wiki/Flaming_%28Internet%29][flaming]]? Post
  your vacation days to a
  [[http://support.google.com/calendar/bin/answer.py?hl=en&answer=36598][shared
  calendar]]? Cultural norms?

  /Members:/ It is useful to include a photo and a link to a public
  profile such as Twitter, Google+ or Facebook.
#+END_QUOTE

** Assessments and feedback loops
   :PROPERTIES:
   :CUSTOM_ID: assessments-and-feedback-loops
   :END:

*** Co-authored assessment rubrics
    :PROPERTIES:
    :CUSTOM_ID: co-authored-assessment-rubrics
    :END:

Tests. Quizzes. Exams. How can the co-learning group assess their
performance?

These types of courses benefit from an approach similar to coaching. Set
goals as individuals and a group in the beginning, define what success
looks like, outline steps that are needed to achieve the goal, check in
on the goal progress periodically, and assess the results at the end of
the course against the goal criteria. Goals may include domain
expertise, a business outcome, a paper demonstrating mastery, a
co-created resource, or even the quality of collaboration and adherence
to shared group norms.

*** Learner created assessments
    :PROPERTIES:
    :CUSTOM_ID: learner-created-assessments
    :END:

Another effective way to create an assessment is to decide on an
individual or group output and create a peer assessment rubric based on
the goals of the individual or group.

One way to create a rubric is to spend some time defining the qualities
you want your output to have based on positive examples. Perhaps a group
wants to create a blog. Each person on the team may identify the
qualities of a great blog post based on examples that they admire. They
can use that example to create a criteria for assessment of co-learner
authored blog posts. We recommend that the criteria have a 0 to 5 point
scale with 0 being non-existent and 5 being superb. Writing a few
indicators in the 1, 3, and 5 columns helps to calibrate reviewers.

Create a
[[https://support.google.com/drive/bin/answer.py?hl=en&answer=143213&topic=21010&ctx=topic][shared
document]], perhaps starting with a list of criteria. Collapse similar
criteria into one item, and create the indicators or definitions of 1,
3, and 5 point performance. Agree on the rubric, and decide on how the
co-learners will be assigned assessment duties. WIll everyone review at
least two others? Will each co-learner product need at least 3 reviewers
before it goes live? Will you use a
[[https://support.google.com/drive/bin/answer.py?hl=en&answer=141195&topic=20329&ctx=topic][spreadsheet]]
or a
[[http://support.google.com/drive/bin/answer.py?hl=en&answer=87809][form]]
to collect the assessments?

In a university setting, the instructor of record may wish to approve a
peer assessment rubric, and it is sometimes a good idea to have a few
outside experts give feedback on criteria that the group may have
missed.

*** Outside assessments
    :PROPERTIES:
    :CUSTOM_ID: outside-assessments
    :END:

It is possible that an instructor of record or similar authority will
create the assessment for performance. In these cases, it is crucial
that the co-learners have access to the grading rubric ahead of time so
that they can ensure their activities and timeline will meet any
requirements. In this case, it may be possible to require that the
co-learners self-organize entirely, or there may be intermediary
assignments such as the charter, project plan or literary review.

** Cyclical use of these models
   :PROPERTIES:
   :CUSTOM_ID: cyclical-use-of-these-models
   :END:

*** So much more to learn
    :PROPERTIES:
    :CUSTOM_ID: so-much-more-to-learn
    :END:

As mentioned above, the joy of this type of learning is that no two
groups will ever do it the same. Their process, goals, and outcomes can
all be unique. As designers and facilitators of this type of learning
environment, we can say it is a wild ride! Each class is exciting,
refreshing, and on trend. The co-learners become our teachers.

If a group generates more topics than it is possible to cover at one
time given the number of group members or if a group has plans to
continue indefinitely, it is always possible to set up a system where
potential topics are collected at all times. These unexplored topics can
be harvested for use in another learning cycle, continuing until the
group achieves comprehensive mastery.

** Risks
   :PROPERTIES:
   :CUSTOM_ID: risks
   :END:

This format is not without its own unique pitfalls: some challenges are
learner disorientation or frustration in a new learning structure with
ambiguous expectations and uneven participation. Some groups simply
never gel, and we do not know why they have failed to achieve the
cohesion required to move forward. Other groups are the exact opposite.
Here are a few risks to consider if you would like to try the methods
suggested here and how to mitigate them.

#+BEGIN_QUOTE
  /Uneven expertise:/ Ask co-learners to be responsible for topics that
  are new to them.

  /Uneven participation and cohesion:/ Ask co-learners what they want to
  do to motivate the group rather than imposing your own ideas.

  /Experts/facilitators that kill the conversation:/ In the charter or
  other documentation, explicitly state that the purpose of the
  discussion is to further the conversation, and encourage experts to
  allow others to explore their own thinking by asking probing (not
  leading) questions.

  /Ambiguous goals:/ Encourage the group to document their mission and
  what they will do as a team. This can change over time, but it is best
  to start out with a clear purpose.
#+END_QUOTE

*** Conclusion
    :PROPERTIES:
    :CUSTOM_ID: conclusion
    :END:

Make mistakes. Correct course. Invite new perspectives. Create a
structure that everyone can work with. Change it when it breaks. Most of
all, have fun!

