#+TITLE: SWATS
#+FIRN_ORDER: 18

#+BEGIN_QUOTE
  Learning to use technology with peers -- the case of Students With
  Abilities in Technology (SWATs).
#+END_QUOTE

Authors: Miguel Ángel Álvarez Pérez and Elisa Armendáriz

* Part 1: Introduction
   :PROPERTIES:
   :CUSTOM_ID: part-1-introduction
   :END:

Mind-amplifying technologies [1], technologies of cooperation [2], such
as conversation technologies, as well as visualization tools, video and
photo edition software, simulators or programming technologies are
emerging learning tools in schools around the world. They are affordable
and accessible enough to design learning environments. Latin America is
no exception and it is fast becoming the norm to find convergent
technology in the classroom.

We challenged students to develop a three-level game with a score or
marker using Scratch, a program developed by MIT. This program allows
you to develop computer programs using modules or blocks of
instructions. The educational value of this tool lies not in its ease of
use but in its nature as an authentic learning environment and ideal
context for developing intellectual skills.

Once students have developed their programs and documented the process
in a learning log, we asked them if they had faced problems in handling
Scratch. In this way we were able to identify which students had
difficulties in developing programs and what their problems were in the
process of choosing instructions.  However, we're also able to identify
those students with particular technical skills.  We call them Students
With Abilities in Technology (SWATs).  In case of difficulty, SWATs can
be called in, and can decide if they want to give advice to peers and
the teacher in the use of Scratch.

The idea of identifying these students and asking them to support their
peers and teachers in specific tasks has an additional educational
component. It is clear that when a student is given the task of
explaining or advising peers or teachers, he develops new competences
and masters, to an even greater extent, those competences for which
he/she was selected as SWAT.

We have observationally determined that this approach is relevant to the
widespread use of digital devices in academic tasks and its extended
application contributes to a more positive use of digital technologies
for learning. We see how, as the use of technology in all learning
environments becomes general, this approach of peer learning becomes an
alternative to underpin the work of teachers. The figure of the SWAT in
the classroom also enables a different form of relationship between
pairs that generate new forms of interaction and learning that we can
appraise and evaluate.

* Part 2. Representation as a pattern
   :PROPERTIES:
   :CUSTOM_ID: part-2.-representation-as-a-pattern
   :END:

Here's how the above case could be described using the pattern template
that we've presented in the book.  This may help others use the same
model --- or at least understand how it works in practice in more
detail.  Further questions may come to mind, which the reader can try to
answer by transforming or extending the pattern in their own context.

*** Title:
     :PROPERTIES:
     :CUSTOM_ID: title
     :END:

Students With Abilities in Technology (SWAT)

*** Definition:
     :PROPERTIES:
     :CUSTOM_ID: definition
     :END:

Private and public schools increasingly have digital devices in
classrooms with Internet access (laptops, desktops, tablets, cell
phones, etc.) and teachers with little or no expertise in the
educational use of such devices.  However, some of the students have
considerable background with these kinds of tools.  They can help the
teachers and other students.

*** Problem:
     :PROPERTIES:
     :CUSTOM_ID: problem
     :END:

In general, teachers have multiple deficiencies in the adoption of
emerging technologies. Their lack of expertise prevents them from
realizing the full potential that technology has as a relevant
pedagogical mediation.  The rate of change in the school context,
however, is not coupled to the rate of change in  current teacher
training programs. This lack of pedagogical training is having a majorly
disruptive impact in the classroom given this presence of technological
devices in the classroom.  The reaction of administrators and teachers
to the proliferation of devices is, in a significant number of cases,
rejection and stigmatization of emerging technologies. The cause of this
rejection is that teachers ignore the educational potential of
technology. They ignore how technology has changed the cognitive model
of a whole generation.  Having technical specialists to support the work
of the teacher in the classroom is unthinkable from an economic
standpoint.

*** Solution:
     :PROPERTIES:
     :CUSTOM_ID: solution
     :END:

The students themselves can be the solution to this problem. Some have
superior technical knowledge and this is usually wasted. Teachers can
incorporate them as assistants to help them and their peers. A student
with digital skills can be the agent of change that many teachers need
in order to learn how to use technology for the design of learning
environments.  This empowered group of students, that we named SWAT
(Students With Abilities in Technology) support teachers and peers with
lower-level digital competences. Support from students with technical
knowledge could mean a significant change in the learning process,
because teachers can now combine that knowledge with their teaching
experience and pedagogical strategies. The result of this can be the
discovery of the many possibilities technology has for the construction
of knowledge and the development of new intellectual abilities.

In our work with middle school students (ages 12-14), the support of
SWATs inside and outside the classroom was a very positive experience.
At the beginning of each course students are required to develop
projects involving the use of technology. Students who show a greater
competence in the use of technical tools are invited to join as SWAT.
Once SWATs are identified, they are asked about the possibility of
supporting teachers and their peers in the use of specific computer
tools. It is impressive to see teachers becoming co-learners who take
advantage of this privileged status of their students to master tools
that promote their ability to redesign learning environments.  When
students need support for developing their projects, SWATs show them
strategies to accomplish them. The majority report great pleasure and
pride in their new role as peer advisors.

*** Challenges arising in practice:
     :PROPERTIES:
     :CUSTOM_ID: challenges-arising-in-practice
     :END:

This peeragogical approach changes the prevailing educational paradigm
through collaboration between teachers and students, and among students
themselves.  There are many possible points of friction.  To have one or
more SWATs in each learning group transforms the way in which teachers
and students interact with each other and with available technologies,
but, again, can create challenges for teachers who may be used to a more
"banking" style of teaching.

*** What's next:
     :PROPERTIES:
     :CUSTOM_ID: whats-next
     :END:

Can we find mentors for the SWATs to help them become even better with
technology?  Can we find other ways to reward these students?  At the
same time, can the idea be applied across the curriculum, and across
other competencies, to involve more students in the peer-teaching role?

* References
   :PROPERTIES:
   :CUSTOM_ID: references
   :END:

1. Howard Rheingold (2012), "Mind Amplifier: Can Our Digital Tools Make
   Us Smarter?"

2. Institute of the Future (2005),
   "[[http://www.rheingold.com/cooperation/Technology_of_cooperation.pdf][Technology
   of cooperation]]."

