#+TITLE: Top
#+roam_tags: AN

* Tippy Top
The /Peeragogy Handbook/ is both a (very large!) /design pattern/ and a
/pattern language/.  That is to say: the book describes the solution to
a problem in a context, and it also built out of interlinked patterns
that smaller and more detailed solutions to constituent problems, in
their own particular contexts.

What is the Peeragogy design pattern?

- How can we learn and adapt to the challenges we face as human beings?
- We put learning and adaptation at the forefront of our minds.
- That’s a first approximation of what ‘culture’ is: we want to work together to understand and use it better.

That’s all you need to know to know what peeragogy ‘is’.  But all three of these components unfold in practice.

- The [[file:problem.org][Problem]] posed by learning and adaptation is hard to do and may even seem impossible.
- Articulating a [[file:solution.org][Solution]] to this problem based on collaboration can be complicated, confusing, and personally challenging (but, also, rewarding).
- The [[file:context.org][Context]] in which this problem applies — offers some evidence that solutions we’ve spotted (and in some cases helped develop) seem to work.

* [[file:peeragogy.org][Peeragogy]]

#+begin_quote
How do /we/ improve at learning, adapting, growing, aging, engaging?

We do that when we to pay attention to their dynamics.

This accelerates when we work together.
#+end_quote

** [[file:problem.org][Problem]]
#+begin_quote
How to do you decide what to learn or engage with?  Sometimes there are clear incentives.  Sometimes it’s fun.

The pedagogical system is about creating a reasonably stable society: and to some extent that’s fine. If you go a little out of the box that’s permitted. Even laws are how society learns over time.

This only ever happens in the real world, where we’re subject to the pressure of being effective.
#+end_quote

** [[file:solution.org][Solution]]

#+begin_quote
Every solution also has a problem: the problem it solves.

Once there’s a solution, the problem ceases to be a problem. If you start with the problem you’ll have to find the solution?

The solution, which developed through time and enterprise, stops mattering.
#+end_quote

*** [[file:convene.org][Convening]]
#+begin_quote
When you first start thinking about a problem it can be hard to wrap your mind around.

Get in touch with other people who are thinking about similar things to contextualise your thinking.

Others will have seen different aspects of the problem, even if they don’t see exactly what you see.
#+end_quote
**** [[file:newcomer.org][Newcomer]]
#+begin_quote
Newcomers can feel overwhelmed by the amount of things to learn. 

Instead of thinking of newcomers as "them", and trying to provide solutions, we focus on newcomers as "us".

When there's learning happening, it's because there is someone who is new to a topic, or to something about the topic.
#+end_quote
**** [[file:a_specific_project.org][A specific project]]
#+begin_quote
It's easy to think about issues that matter: there are many of them.

If you /are/ able to get concrete about something to do, learn, and achieve, you move from thinking about a topic to becoming a practitioner.

You find yourself interested in or concerned about something, but you only have a vague idea about how it works or how you fit in.
#+end_quote
*** [[file:organizing.org][Organizing]]
#+begin_quote
We can’t learn unless there’s a structure there to learn, and a way of apprehending that structure.

So there are two structures here that need to be brought into communication.

Organization exists at many levels: matter in space, events in time, species in the world of biology, cultural patterns in society.
#+end_quote
**** [[file:heartbeat.org][Heartbeat]]
#+begin_quote
How will the effort be sustained and coordinated sufficiently?

People seem to naturally gravitate to something with a pulse.

A number of people have a shared interest, and have connected with each other: however, they are not going to spend 24 hours a day, 7 days a week working together.
#+end_quote
**** [[file:roadmap.org][Roadmap]]
#+begin_quote
In order to collaborate, people need a way to share current, though incomplete, understanding of the space they are working in, and to nurture relationships with one another and the other elements of this space.

Building a guide to the goals, activities, experiments and working methods can help newcomers and old-timers alike understand their relationship with the project.

The discussants or contributors who collaborate on a project have different points of view and heterogeneous priorities, but they come together in conversations and joint activities.
#+end_quote
*** [[file:cooperate.org][Cooperation]]
#+begin_quote
Moving to a well-formulated problem requires concerted effort.

Coordinate effort that involves the concerned parties.

Part of this is finding partial solutions elsewhere, and places where you can contribute.
#+end_quote
**** [[file:reduce_reuse_recycle.org][Reduce, reuse, recycle]]
#+begin_quote
Many projects die because the cost of [[http://c2.com/cgi/wiki?ReinventingTheWheel][Reinventing the Wheel]] is too high.

"Steal like an artist," and make it possible for other people to build on your work too.

In a peer production context, you are simultaneously "making stuff" and building on the work of others.
#+end_quote
*** [[file:assessment.org][Assessment]]
#+begin_quote
You’ll have to find ways to figure out what constitutes progress.

Use your embodied sense of when you’re training and learning, and when you’re overdoing it or treading water.

Confer with others to get their assessments, which won’t be obvious to you unless you ask.
#+end_quote
**** [[file:scrapbook.org][Scrapbook]]
#+begin_quote
Not all of the ideas we've come up with have proved workable.

In order to maintain focus, is important to "tune" and "prune" the things we give our attention to.

We have maintained and revised our pattern catalog, and we are achieving some of the "What's Next" steps associated with some of the patterns.
#+end_quote
**** [[file:pattern-carrying.org][Carrying capacity]]
#+begin_quote
How can we help prevent those people who are involved with the project from over-promising or over-committing, and subsequently crashing and burning?

Serious frustration is a sign that it's time to revisit the group's and your own individual plan.

There's only so much any one person can do, since we all have limited time and energy.
#+end_quote
*** [[file:share.org][Share]]
#+begin_quote
You’ll want to get input and feedback from other people who are concerned.

Keep them in the loop, create ways for them to engage.

This applies across all the ongoing activities, as well as the products.
#+end_quote
**** [[file:wrapper.org][Wrapper]]
#+begin_quote
In an active project, it can be effectively impossible to stay up to date with all of the details.

Someone involved with the project should regularly create a wrap-up summary, distinct from other project communications.

You are part of an active, long-running, and possibly quite complex project with more than a handful of participants.
#+end_quote
** [[file:context.org][Context]]

#+begin_quote
The bigger challenge is always: to manifest meaningful relationships.

That happens through communication.

And always within a bigger context.
#+end_quote


* Ongoing PAR of the Top level summary!
** 1. Review the intention: what do we expect to learn or make together?
- Present some ‘poetic’ peeragogy progress, and ‘a way in’ to everthing we have to offer
** 2. Establish what is happening: what and how are we learning?
- Rough drafts here in Org Mode
- Pairing to look at some of these sections on 1st Saturday
** 3. What are some different perspectives on what’s happening?
- Starting with this top-level summary and revising it together could be a good way forward
** 4. What did we learn or change?
- Bringing voice into the mix changed the contents for the better
** 5. What else should we change going forward?
- Keep patternizing things
- Keep working over the text
- SPREAD TASKS THIN NOT PEOPLE

