#+TITLE: Top
#+roam_tags: AN

* Tippy Top
 - For some background on what we’re doing here, please see [[file:introduction_to_pattern_languages.org][Introduction to Pattern Languages]].

* [[file:peeragogy.org][Peeragogy]]

#+begin_quote
- P: How do we improve at learning and engaging?
- S: By paying attention to their dynamics.
- C: And this accelerates when we work together.
#+end_quote

# We need to make it so that when people read the friendly Peeragogy Handbook, they *get* to practice peeragogy.
# - We don’t want to stand in front of a room and ‘teach’ peeragogy, rather, what kind of activities can we bring so that people get
# - Similar to Leo: having a REPL that will bully you into knowing!
# - - A lot of people tell you that the Rust REPL that took Rust’s harshness further
# - - The subtext: Prepare you for the work environment

# L oop
# S tudy
# D esign
# W rite

# ----- < Mirror

# R ead
# E val
# P rint
# L oop

# What’s missing?  Where to look stuff up!  Who else to talk to.

** [[file:problem.org][Problem]]
#+begin_quote
- P: How do you learn when there is no teacher, OR textbook; there’s no tutor, OR explicit curriculum, only each other — and you’re stuck?
- S: Practice peeragogy, i.e., understand the patterns that are transferrable.
- C: Significant change and creativity only ever happens in the real world, where we’re subject to the pressure of being effective.
#+end_quote

*** Micro-case studies

**** “Hard science vs soft science”
#+begin_quote
- P: All else equal I would prefer to do my scientific research but collaborators are preoccupied and the situation breaks down.
- S: So, I’ve engaged with some soft patterns like Heartbeat and Zettlekasten and I can get it working again.
- C: Science is done within a community so if the context hasn’t come prefab’ed it needs to be constructed.
#+end_quote

** [[file:solution.org][Solution]]
#+begin_quote
- P: The problem we consider is the same one Spinoza talked about: the problem of human freedom.
- S: The solution we’ve found relates to engagement in understanding the process of learning and creativity.
- C: Things can be empowered or disempowered socially: we write and think about the forms of organisation that empower people.
#+end_quote

*** [[file:convene.org][Convening]]
#+begin_quote
- P: When you first start thinking about a problem it can be hard to wrap your mind around it.
- S: If you get in touch with other people who are thinking about similar things, that can contextualise your thinking.
- C: Others will have seen different aspects of the problem: they don’t see exactly what you see.
#+end_quote

**** [[file:newcomer.org][Newcomer]]
#+begin_quote
- P: Newcomers can feel overwhelmed by the amount of things to learn.
- S: We focus on newcomers as "us", and try to make it clear what we are actively learning, and who "we" are, and how we learn — and teach!
- C: When there's learning, there’s someone who is new to a topic, and hopefully someone to give some guidance even if they figure it out on the fly.
#+end_quote
**** [[file:specific.org][A specific project]]
#+begin_quote
- P: It's easy to think about issues that matter: there are many of them.
- S: If you /are/ able to get concrete about something to do, learn, and achieve, you move from thinking about a topic to becoming a practitioner.
- C: You find yourself interested in or concerned about something, but you only have a vague idea about how it works or how you fit in.
#+end_quote
*** [[file:organizing.org][Organizing]]
#+begin_quote
- P: We can’t learn unless there’s a structure there to learn, and a way of apprehending that structure.
- S: So there are two structures here that need to be brought into communication.
- C: Organization exists at many levels: matter in space, events in time, species in the world of biology, cultural patterns in society.
#+end_quote
**** [[file:heartbeat.org][Heartbeat]]
#+begin_quote
- P: How will the effort be sustained and coordinated sufficiently?
- S: People seem to naturally gravitate to something with a pulse.
- C: A number of people have a shared interest, and have connected with each other: however, they are not going to spend 24 hours a day, 7 days a week working together.
#+end_quote

**** [[file:roadmap.org][Roadmap]]
#+begin_quote
- P: In order to collaborate, people need a way to share current, though incomplete, understanding of the space they are working in, and to nurture relationships with one another and the other elements of this space.
- S: Building a guide to the goals, activities, experiments and working methods can help newcomers and old-timers alike understand their relationship with the project.
- C: The discussants or contributors who collaborate on a project have different points of view and heterogeneous priorities, but they come together in conversations and joint activities.
#+end_quote

*** [[file:cooperate.org][Cooperation]]
#+begin_quote
- P: Moving to a well-formulated problem requires concerted effort.
- S: Coordinate effort that involves the concerned parties.
- C: Part of this is finding partial solutions elsewhere, and places where you can contribute.
#+end_quote
**** [[file:reduce.org][Reduce, reuse, recycle]]
#+begin_quote
- P: Many projects die because the cost of [[http://c2.com/cgi/wiki?ReinventingTheWheel][Reinventing the Wheel]] is too high.
- S: "Steal like an artist," and make it possible for other people to build on your work too.
- C: In a peer production context, you are simultaneously "making stuff" and building on the work of others.
#+end_quote
*** [[file:assessment.org][Assessment]]
#+begin_quote
- P: You’ll have to find ways to figure out what constitutes progress.
- S: Your mind and body will tell you when you’re training and learning, and when you’re overdoing it or treading water.
- C: Confer with others to get their assessments, which won’t be obvious to you unless you ask.
#+end_quote
**** [[file:scrapbook.org][Scrapbook]]
#+begin_quote
- P: Not all of the ideas we've come up with have proved workable.
- S: In order to maintain focus, is important to "tune" and "prune" the things we give our attention to.
- C: We have maintained and revised our pattern catalog, and we are achieving some of the "What's Next" steps associated with some of the patterns.
#+end_quote
**** [[file:carrying.org][Carrying capacity]]
#+begin_quote
- P: How can we help prevent those people who are involved with the project from over-promising or over-committing, and subsequently crashing and burning?
- S: Serious frustration is a sign that it's time to revisit the group's and your own individual plan.
- C: There's only so much any one person can do, since we all have limited time and energy.
#+end_quote
*** [[file:share.org][Share]]
#+begin_quote
- P: You’ll want to get input and feedback from other people who are concerned.
- S: Keep them in the loop, create ways for them to engage.
- C: This applies across all the ongoing activities, as well as the products.
#+end_quote
**** [[file:wrapper.org][Wrapper]]
#+begin_quote
- P: In an active project, it can be effectively impossible to stay up to date with all of the details.
- S: Someone involved with the project should regularly create a wrap-up summary — distinct from other project communications.  In the long run it’s valuable if more than one person practice this role.
- C: You are part of an active, long-running, and possibly quite complex project.
#+end_quote

** [[file:context.org][Context]]
#+begin_quote
- P: The bigger challenge is always: to manifest meaningful relationships.
- S: That happens through communication.
- C: And always within a bigger context.
#+end_quote
**** [[file:the_peeragogy_project.org][The Peeragogy Project]]
#+begin_quote
- P: The Peeragogy project is just one of the contexts in which ‘peeragogy’ happens.
- S: The project has been going since 2011.
- C: It’s driven by volunteers who are interested in understanding peer learning and peer production better to apply it in their own contexts.
#+end_quote
***** [[file:project.org][Project]]
#+begin_quote
- P: Since we have been at it for quite a while we have a lot of data on how things have been going, but maybe not yet such a clear sense of where it’s going.
- S: In order to get anywhere we need to keep apprised of all of our resources; as well as whether and how they are sustained.
- C: In any enterprise it makes sense to be careful to ‘spread tasks thin, not people’.
#+end_quote
***** [[file:website.org][Website]]
#+begin_quote
- P: The key informatic challenges are those of accessing and interacting with information
- S: This means that when we write we’re not only posting updates but also working to make the material a two way street (or multi-way roadmap!)
- C: Our project exists in a context of readers, viewers, contributors, and others who might want to interact with our materials
#+end_quote
***** [[file:course.org][Course]]
#+begin_quote
- P: It’s not peeragogy unless it’s collaborative: simultaneously, we can’t expect people to “get it” unless we co-create opportunities to “do with us”.
- S: A set of interactive exercises that help people wrap their hearts and minds around peeragogy can help us understand if it’s working.
- C: In the context of ‘education’ this may be a renegade activity; in workplace cultures, open learning may also be unfamiliar. But peeragogy thrives in open source settings!
#+end_quote
***** [[file:podcast.org][Podcast]]
#+begin_quote
- P: Helping us understand what we actually have to offer
- S: A series of structured discussions
- C: People have interesting things to say
#+end_quote
***** [[file:paper.org][Paper]]
#+begin_quote
- P: Developing thinking along a number of complex and somewhat novel directions
- S: Write one or more academic papers to a high standard, suitable for discussing with specialists
- C: With specialist topics there are discipline-specific communities who are ready to discuss and give feedback
#+end_quote
***** [[file:community.org][Community]]
#+begin_quote
- P: We can’t expect everyone who has interesting this to say to come on our podcast; besides, they might have more to teach us in context
- S: Interact with some other communities on their home turf and report back
- C: Groups of a certain size with somewhat porous boundaries
#+end_quote
***** [[file:handbook.org][Handbook]]
#+begin_quote
- P: Can we create a common ground for people to engage with?
- S: Writing gives us something concrete to do in collaboration
- C: It’s one reasonably accessible way for us to get started organizing contents and contributors
#+end_quote
*** [[file:technologies.org][Technologies]]
#+begin_quote
- P: How we approach technologies makes a big difference: do we think of them simply as tools to use, or as material that we can bend to meet our needs?
- S: Becoming empowered to use and work with technology comes especially from disciplined practice: a form of apprenticeship.
- C: Technologies are part of our the modern landscape, their nature is to be put to use, whether for good or for ill, or a mixture of the two.
#+end_quote
**** [[file:forums.org][Forums]]
#+begin_quote
- P: How do we find common ground to speak about things?
- S: Create an empty, neutral space where people can come together.
- C: This empty space should be in communication with as much of the rest of the space as possible.
#+end_quote
**** [[file:wiki.org][Wiki]]
#+begin_quote
- P: How can we organise our thoughts?
- S: Link key concepts together, preserving flexibility about both the content and the structure.
- C: We want to be able to have multiple perspectives and multiple expressions of ideas related to a body of content.
#+end_quote
**** [[file:social-bookmarking.org][Social Bookmarking]]
#+begin_quote
- P: How can we understand something if we can’t or don’t want to access its internals?
- S: We can know the thing external, by sharing how to access and simple notes?
- C: There are things that we can point to but we can’t easily share
#+end_quote
**** [[file:realtime.org][Realtime]]
#+begin_quote
- P: We have spatial distance between, and time distance can separate us.
- S: Now though we can set up a call that allows us to be more accessible, including w/ low-bandwidth solutions.
- C: We can interact with whatever is in front of us, by using technology to bridge across time and space: radio is the "technology that annihilates distance" (Tesla)
#+end_quote
**** [[file:connectivism.org][Connectivism]]
#+begin_quote
- P: How can we prioritize our limited time and personal bandwidth.
- S: Learning should focus on where and to find and interact with information; however this won’t yet allow us to do learning at a deeper level.
- C: There are learning resource that we can access (even if we haven’t found them yet): possibly these could include peers who we can learn with.
#+end_quote

*** [[file:cases.org][Case Studies]]
#+begin_quote
- P: If we want to learn about peeragogy, we need to amass a collection of different cases in which it actually happens.
- S: The ‘unit of analysis’ is social in nature, and the method of analysis is through patterns.
- C: Peeragogy can happen anywhere people come together: in education, the workplace, or communities.
#+end_quote

**** Emacs Research Group
#+begin_quote
- P: If we tackle big enough projects, it will bring with it the need for collaboration.
- S: Emacs can become part of a system for addressing large-scale existential problems, by expanding the frontier of what’s possible for human beings.
- C: We’ve made progress since we started with the raw themes of *Research on/in/with Emacs* back in December 2020.
#+end_quote

***** FORMAL PATTERNS
#+begin_quote
- P: Using patterns, todo items, CLA, and PARs in an intuitive manner is clearly workable at a small scale, but could become chaotic when we scale up; this *conflicts* with our perspective that these methods can be applied broadly.
- S: Can we develop a more mathematically precise way to describe this set of tools?  We might build on the earlier work of Corneli et al. which describes patterns as /conceptual blends/.
- C: Working with project- and change-management Technologies across a distributed Community.
#+end_quote

***** SERENDIPITY
#+begin_quote
- P: The idea of planning *conflicts* with our experience that reliance on plans can produce rigid behaviour and a corresponding brittleness.
- S: We adapt our plans to increase our /general/ preparedness, and adapt our strategy to decrease our reliance on accurate /forecasting/. This operationalises the ‘serendipity pattern’ described by Merton.
- C: Within an ongoing research and development project.
#+end_quote

***** RECOMMENDER
#+begin_quote
- P: As the body of content grows, it can be harder to find relevant material or the best collaborators in a global pool: this *conflicts* with our desire to achieve excellence.
- S: New software that can help surface relevant material and opportunities would be useful.  Existing implementations include “scrobbling” audio tracks to Last.fm, or buying recommended products on Amazon.  The same ideas can be adapted to FLOSS, research, learning, and other domains.
- C: Within our use of Technologies and materials we could Reduce, reuse, recycle.
#+end_quote

***** DIVERSITY
#+begin_quote
- C: Within a Project.
- P: If we only collaborate within a relatively homogeneous population of people who think like us this *conflicts* with our desire to find new ideas and new solutions, and to do widely relevant work.
- S: Look out for different contexts in which we can collaborate with different people; they don’t all have to work on the same project.  We recognise that collaboration is easier when we share similar languages and literacies.  In cases where collaboration needs to be made tighter, prefer ways of exchanging information and expertise with Newcomers that makes the relationship one of peers rather than a one-way hierarchy.
#+end_quote

**** BACK [[file:5ph1nx.org][5PH1NX]] pattern + analysis                               :handbook:
- Catch up with David about Open Source Learning
**** BACK [[file:action.org][Peeragogy in action]] pattern + analysis                  :handbook:
**** BACK [[file:swats.org][SWATS]] pattern + analysis                                :handbook:
**** BACK [[file:sole.org][SOLE]] pattern + analysis                                 :handbook:
**** BACK [[file:a_meeting_with_the_pro_vice_chancellor.org][A meeting with the Pro Vice-Chancellor]] pattern + analysis :handbook:
**** BACK [[file:collab-ex.org][Collaborative Explorations]] pattern + analysis           :handbook:
**** BACK [[file:coworking-story.org][Coworking Story]] pattern + analysis                      :handbook:

* Ongoing PAR of the Top level summary!
** 1. Review the intention: what do we expect to learn or make together?
- Present some ‘poetic’ peeragogy progress, and ‘a way in’ to everthing we have to offer
- When there’s a full draft, pass to Charlie for revision
** 2. Establish what is happening: what and how are we learning?
- I created a bunch of Scrum Boards to keep track of tasks and progress within the various ongoing sub-projects
#+begin_src
C-c R P C       org-scrum-board-peeragogy-course
C-c R P H       org-scrum-board-peeragogy-handbook
C-c R P J       org-scrum-board-peeragogy-project
C-c R P P       org-scrum-board-peeragogy-podcast
C-c R P R       org-scrum-board-peeragogy-paper
C-c R P W       org-scrum-board-peeragogy-website/technology — Or rather should become different technologies
C-c R P Y       org-scrum-board-peeragogy-community
#+end_src
- Rough drafts of individual patterns here in Org Mode
- Pairing to look at some of these sections with Charlie, Ray, Leo
** 3. What are some different perspectives on what’s happening?
- Concern about the technology: People are excluded “by default” — and no matter what we’re using some people are excluded
  - We never had an ‘inclusive platform’ that was productive and working well
  - At no point was it solving the problems that we want to solve, but we did have “one project at a time where everyone was involved at some level”
- Now we have several sub-projects up and running — not everyone needs to be directly involved in every aspect of the project
- We do need to stay in touch
** 4. What did we learn or change?
- Bringing voice into the mix by reading these things out loud helped to change the contents for the better
** 5. What else should we change going forward?
*** DONE [#A] Work some more on the ‘poem’ version of the handbook  :handbook:
*** BACK Gather some more micro-case-studies in 1-to-1 interviews :handbook:
*** BACK Patternize the rest of the handbook, whatever that means :handbook:
*** BACK Produce some mini-handbooks                              :handbook:
*** BACK Analyse the case studies using patterns                  :handbook:
*** BACK Keep working over the comments from the Reading Group    :handbook:
*** BACK Describe the new pattern "SPREAD TASKS THIN NOT PEOPLE"   :project:
*** BACK Once the Top document is ready, move it to the front page :website:
** See if we want to integrate these notes:
- Like Google’s “don’t be evil” — but better than that.
- Until we sort some of the structure out we can’t expect people to be brought into the project
  - It’s not enough to be ‘public’ (in a read-only sense)
  - Things were written to the directory but then became ‘locked’
- Practical issues :: What is peeragogy from the point of view of someone coming in?  Maybe it’s a regular monthly meeting and we invite people in.  They come along and feel like they are part of it.
- Or the book :: They read it, and then what?
- Compare ERG :: “Can you show up to one of our meetings” — people wouldn’t feel obliged to read our meeting notes!
  - A use case might be: I read something in your notes, or I had another idea and I’d like to discuss it with you
  - Maybe we’re in time to give some patterns back to Peeragogy
- There was some confusion/tension about the paper — e.g., “too much attention on the paper” — but this was a symptom of not having well-defined spaces
  - ‘Complaints about surface things’ (o) /suggest/ some /deeper problems/ with organisation: we had spawned all these things that are now on the list, BUT THE WAY OF ORGANIZING OURSELVES HADN’T KEPT.  (Compare complicated cells with a lot of organelles but not enough structure in the different types of cells.)
    - Recognising: e.g., “happy Hannuka” and not schedule a category theory meeting on a high holiday
- You come along to the monthly meeting and someone raises an issue about project /X/ — it then becomes part of what each project /S/ needs to do to provide such an interface.
  - I don’t know but go to Charlotte to talk about the podcast.
  - We could look at the health metrics of each ‘subproject’ (‘subchannel’)

- It’s intelligent not to have any upcoming meeting info
- We don’t even know where to go if you are interested
- Pay attention to the /elegance of organisation/ — are ready for people or not?

*** Notes to merge
- How do we identify the factors that drive change in the system we are examining?
- How can we make ourselves sensitive to change and modelling the forces that are changing things.
- When do we have to learn things?
- When is there a problem?
- We observe situations of failure, and if we object, we may have to learn something.
- We can observe widespread failure of traditional academic models, at least relative to goals like egalitarianism, or the goals of the learners.
- There are anti-peeragogies in which working together might be considered cheating!
- How do you find them?
- How do you know when you need to contextualise your thinking?
- Who are you looking for?
- Why would they want to talk with you...?
- What’s in it for them?  What do I have to offer?
- What do I have to give? ... which gets back to ‘The Gift’
- (E.g., explaining math to a biologist, who doesn’t have a clear grasp of function... being a newcomer can be useful.)
- It might be hard to find someone who is both a newcomer and willing to talk to you?
- LV: Experts-discoverability-newcomers (a triad): you need someone with a fresh pair of ‘soft eyes’ — it takes an expert to be able to ask probing questions.
- RP: You want to play with someone not much better or worse than you (handicapping)
- I, I+1 — so you should aim in an artificial manner
- How do you maintain a ZPD among peers if you have the blind leading the blind...?  Maybe there’s something that makes it emerge.
- This relates to common ground — considering from this common ground that there’s an overlap with the ZPD
- If you follow a regress, you get to geological epochs...
- Language (e.g., pattern languages should have syntax, semantics, pragmatics, ... phonology)!
- NLP could be a specialisation, audio synthesis...
- JC: to find Siri chapter

*** WHAT ARE THE REAL PROBLEMS THAT PEERAGOGY SOLVES OR ADDRESSES
**** DIFFICULT conversation #1
- Maybe conversation with Cicolab & Charlotte will help overcome future difficulties
**** DIFFICULT conversation #2
- What are the actual problems that people have
  - The cost of education!
  - Barriers to entry!
**** DIFFICULT conversation #3
- We have a lack of new education skills — this gives us a place to practice the soft skills
  - Different from 42.fr, where they say it’s peer learning but they don’t promote peer conversations
**** Putting the network to work
- Finding people who we can solve an issue with quickly!
  - E.g., I didn’t expect Paola to drop everything and take this on but it was a good opportunity for Lilian’s friend who’s interested in ENVIRONMENTAL JUSTICE.
     - And it comes back now that Charlotte is working with the media station on this
  - ‘We can love each other we can hate each other but we’re always there for each other’
**** Meta: we’ve built lots of hammers
**** Things I know, things I know I don’t know, everything else
- Maybe I’m not the best guy to talk about certain topics, but talking with you, it helps a lot to lose the shyness, to open your heart...
**** When Google supplies its technology...
- It needs to be accessible to everyone
- me, maybe I’m 10% literate on Github
- I don’t want to go online, I don’t know how to do it.
- I don’t know how to get to this...
- More people would like to have their hands on this!
- Can we have an “ERG Peeragogy Pool Party”
  - Cannonball’s allowed!

*** Also
- Underscores the role of the Wrapper.
- Should we replace Jitsi?
