#+TITLE: Top
#+roam_tags: AN

* Tippy Top
 - For some background on what we’re doing here, please see [[file:introduction_to_pattern_languages.org][Introduction to Pattern Languages]].

** TODO ... ?
- Underscores the role of the Wrapper.
- Should we replace Jitsi?

* [[file:peeragogy.org][Peeragogy]]

#+begin_quote
How do we improve learning (and at learning), engaging?

By paying attention to their dynamics.

And this accelerates when we work together.
#+end_quote

** [[file:problem.org][Problem]]
#+begin_quote
How do you decide what to learn or do?  Sometimes it’s obvious, sometimes it isn’t.

We’d like to ...

The thing is, significant change and creativity only ever happens in the real world, where we’re subject to the pressure of being effective.
#+end_quote

*** WHAT ARE THE REAL PROBLEMS THAT PEERAGOGY SOLVES OR ADDRESSES
**** DIFFICULT conversation #1
- Maybe conversation with Cicolab & Charlotte will help overcome future difficulties
**** DIFFICULT conversation #2
- What are the actual problems that people have
  - The cost of education!
  - Barriers to entry!
**** DIFFICULT conversation #3
- We have a lack of new education skills — this gives us a place to practice the soft skills
  - Different from 42.fr, where they say it’s peer learning but they don’t promote peer conversations
**** Putting the network to work
- Finding people who we can solve an issue with quickly!
  - E.g., I didn’t expect Paola to drop everything and take this on but it was a good opportunity for Lilian’s friend who’s interested in ENVIRONMENTAL JUSTICE.
     - And it comes back now that Charlotte is working with the media station on this
  - ‘We can love each other we can hate each other but we’re always there for each other’
**** Meta: we’ve built lots of hammers
**** Things I know, things I know I don’t know, everything else
- Maybe I’m not the best guy to talk about certain topics, but talking with you, it helps a lot to lose the shyness, to open your heart...
**** When Google supplies its technology...
- It needs to be accessible to everyone
- me, maybe I’m 10% literate on Github
- I don’t want to go online, I don’t know how to do it.
- I don’t know how to get to this...

** [[file:solution.org][Solution]]

#+begin_quote
The problem we consider is the same one Spinoza talked about: the problem of human freedom.

The solution we’ve found relates to engagement in understanding the process of learning and creativity.

Things can be empowered or disempowered socially: we write and think about the forms of organisation that empower people.
#+end_quote

*** [[file:convene.org][Convening]]
#+begin_quote
When you first start thinking about a problem it can be hard to wrap your mind around it.

If you get in touch with other people who are thinking about similar things that can contextualise your thinking.

Others will have seen different aspects of the problem: they don’t see exactly what you see.
#+end_quote

**** [[file:newcomer.org][Newcomer]]
#+begin_quote
Newcomers can feel overwhelmed by the amount of things to learn.

We focus on newcomers as "us", and try to make it clear what we are actively learning, and who "we" are, and how we learn — and teach!

When there's learning, there’s someone who is new to a topic, and hopefully someone to give some guidance even if they figure it out on the fly.
#+end_quote
**** [[file:specific.org][A specific project]]
#+begin_quote
It's easy to think about issues that matter: there are many of them.

If you /are/ able to get concrete about something to do, learn, and achieve, you move from thinking about a topic to becoming a practitioner.

You find yourself interested in or concerned about something, but you only have a vague idea about how it works or how you fit in.
#+end_quote
*** [[file:organizing.org][Organizing]]
#+begin_quote
We can’t learn unless there’s a structure there to learn, and a way of apprehending that structure.

So there are two structures here that need to be brought into communication.

Organization exists at many levels: matter in space, events in time, species in the world of biology, cultural patterns in society.
#+end_quote
**** [[file:heartbeat.org][Heartbeat]]
#+begin_quote
How will the effort be sustained and coordinated sufficiently?

People seem to naturally gravitate to something with a pulse.

A number of people have a shared interest, and have connected with each other: however, they are not going to spend 24 hours a day, 7 days a week working together.
#+end_quote
**** [[file:roadmap.org][Roadmap]]
#+begin_quote
In order to collaborate, people need a way to share current, though incomplete, understanding of the space they are working in, and to nurture relationships with one another and the other elements of this space.

Building a guide to the goals, activities, experiments and working methods can help newcomers and old-timers alike understand their relationship with the project.

The discussants or contributors who collaborate on a project have different points of view and heterogeneous priorities, but they come together in conversations and joint activities.
#+end_quote

*** [[file:cooperate.org][Cooperation]]
#+begin_quote
Moving to a well-formulated problem requires concerted effort.

Coordinate effort that involves the concerned parties.

Part of this is finding partial solutions elsewhere, and places where you can contribute.
#+end_quote
**** [[file:reduce.org][Reduce, reuse, recycle]]
#+begin_quote
Many projects die because the cost of [[http://c2.com/cgi/wiki?ReinventingTheWheel][Reinventing the Wheel]] is too high.

"Steal like an artist," and make it possible for other people to build on your work too.

In a peer production context, you are simultaneously "making stuff" and building on the work of others.
#+end_quote
*** [[file:assessment.org][Assessment]]
#+begin_quote
You’ll have to find ways to figure out what constitutes progress.

Your mind and body will tell you when you’re training and learning, and when you’re overdoing it or treading water.

Confer with others to get their assessments, which won’t be obvious to you unless you ask.
#+end_quote
**** [[file:scrapbook.org][Scrapbook]]
#+begin_quote
Not all of the ideas we've come up with have proved workable.

In order to maintain focus, is important to "tune" and "prune" the things we give our attention to.

We have maintained and revised our pattern catalog, and we are achieving some of the "What's Next" steps associated with some of the patterns.
#+end_quote
**** [[file:carrying.org][Carrying capacity]]
#+begin_quote
How can we help prevent those people who are involved with the project from over-promising or over-committing, and subsequently crashing and burning?

Serious frustration is a sign that it's time to revisit the group's and your own individual plan.

There's only so much any one person can do, since we all have limited time and energy.
#+end_quote
*** [[file:share.org][Share]]
#+begin_quote
You’ll want to get input and feedback from other people who are concerned.

Keep them in the loop, create ways for them to engage.

This applies across all the ongoing activities, as well as the products.
#+end_quote
**** [[file:wrapper.org][Wrapper]]
#+begin_quote
[C] You are part of an active, long-running, and possibly quite complex project.

[P] In an active project, it can be effectively impossible to stay up to date with all of the details.

[S] Someone involved with the project should regularly create a wrap-up summary — distinct from other project communications.  In the long run it’s valuable if more than one person practice this role.
#+end_quote

** [[file:context.org][Context]]
#+begin_quote
The bigger challenge is always: to manifest meaningful relationships.

That happens through communication.

And always within a bigger context.
#+end_quote
**** [[file:the_peeragogy_project.org][The Peeragogy Project]]
#+begin_quote
The Peeragogy project is just one of the contexts in which ‘peeragogy’ happens.

The project has been going since 2011.

It’s driven by volunteers who are interested in understanding peer learning and peer production better to apply it in their own contexts.
#+end_quote
***** [[file:project.org][Project]]
#+begin_quote
Since we have been at it for quite a while we have a lot of data on how things have been going, but maybe not yet such a clear sense of where it’s going.

In order to get anywhere we need to keep apprised of all of our resources; as well as whether and how they are sustained.

In any enterprise it makes sense to be careful to ‘spread tasks thin, not people’.
#+end_quote
***** [[file:website.org][Website]]
#+begin_quote
The key informatic challenges are those of accessing and interacting with information

This means that when we write we’re not only posting updates but also working to make the material a two way street (or multi-way roadmap!)

Our project exists in a context of readers, viewers, contributors, and others who might want to interact with our materials
#+end_quote
***** [[file:course.org][Course]]
#+begin_quote
It’s not peeragogy unless it’s collaborative: simultaneously, we can’t expect people to “get it” unless we co-create opportunities to “do with us”.

A set of interactive exercises that help people wrap their hearts and minds around peeragogy can help us understand if it’s working.

In the context of ‘education’ this may be a renegade activity; in workplace cultures, open learning may also be unfamiliar. But peeragogy thrives in open source settings!
#+end_quote
***** [[file:podcast.org][Podcast]]
#+begin_quote
Helping us understand what we actually have to offer

A series of structured discussions

People have interesting things to say
#+end_quote
***** [[file:paper.org][Paper]]
#+begin_quote
Developing thinking along a number of complex and somewhat novel directions

Write one or more academic papers to a high standard, suitable for discussing with specialists

With specialist topics there are discipline-specific communities who are ready to discuss and give feedback
#+end_quote
***** [[file:community.org][Community]]
#+begin_quote
We can’t expect everyone who has interesting this to say to come on our podcast; besides, they might have more to teach us in context

Interact with some other communities on their home turf and report back

Groups of a certain size with somewhat porous boundaries
#+end_quote
***** [[file:handbook.org][Handbook]]
#+begin_quote
Can we create a common ground for people to engage with?

Writing gives us something concrete to do in collaboration

It’s one reasonably accessible way for us to get started organizing contents and contributors
#+end_quote

*** [[file:technologies.org][Technologies]]
#+begin_quote
How we approach technologies makes a big difference: do we think of them simply as tools to use, or as material that we can bend to meet our needs?

Becoming empowered to use and work with technology comes especially from disciplined practice: a form of apprenticeship.

Technologies are part of our the modern landscape, their nature is to be put to use, whether for good or for ill, or a mixture of the two.
#+end_quote
**** BACK [[file:forums.org][Forums]] pattern                                          :handbook:
#+begin_quote
- Facilitating high-conflict environments
#+end_quote
**** BACK [[file:wiki.org][Wiki]] pattern                                            :handbook:
**** BACK [[file:realtime.org][Realtime]] pattern                                        :handbook:
#+begin_quote
Spatial distance, and time distance; because it has been a while since we talked.

It seems like we’re stuck with what is in front of us

Now though we can set up a call that allows us to be more accessible, including w/ low-bandwidth solutions.
#+end_quote
**** BACK [[file:social-bookmarking.org][Social Bookmarking]] pattern                              :handbook:
**** BACK [[file:connectivism.org][Connectivism]] pattern                                    :handbook:


*** [[file:cases.org][Case Studies]]
#+begin_quote
If we want to learn about peeragogy, we need to amass a collection of different cases in which it actually happens.

The ‘unit of analysis’ is social in nature, and the method of analysis is through patterns.

Peeragogy can happen anywhere people come together: in education, the workplace, or communities.
#+end_quote
**** BACK [[file:swats.org][SWATS]] pattern + analysis                                :handbook:
**** BACK [[file:5ph1nx.org][5PH1NX]] pattern + analysis                               :handbook:
**** BACK [[file:a_meeting_with_the_pro_vice_chancellor.org][A meeting with the Pro Vice-Chancellor]] pattern + analysis :handbook:
**** BACK [[file:sole.org][SOLE]] pattern + analysis                                 :handbook:
**** BACK [[file:collab-ex.org][Collaborative Explorations]] pattern + analysis           :handbook:
**** BACK [[file:action.org][Peeragogy in action]] pattern + analysis                  :handbook:
**** BACK [[file:coworking-story.org][Coworking Story]] pattern + analysis                      :handbook:

**** BACK ERG pattern + analysis                                  :handbook:








* Some comments

- Like Google’s “don’t be evil” — but better than that.
- Until we sort some of the structure out we can’t expect people to be brought into the project
  - It’s not enough to be ‘public’ (in a read-only sense)
  - Things were written to the directory but then became ‘locked’
- Practical issues :: What is peeragogy from the point of view of someone coming in?  Maybe it’s a regular monthly meeting and we invite people in.  They come along and feel like they are part of it.
- Or the book :: They read it, and then what?
- Compare ERG :: “Can you show up to one of our meetings” — people wouldn’t feel obliged to read our meeting notes!
  - A use case might be: I read something in your notes, or I had another idea and I’d like to discuss it with you
  - Maybe we’re in time to give some patterns back to Peeragogy
- There was some confusion/tension about the paper — e.g., “too much attention on the paper” — but this was a symptom of not having well-defined spaces
  - ‘Complaints about surface things’ (o) /suggest/ some /deeper problems/ with organisation: we had spawned all these things that are now on the list, BUT THE WAY OF ORGANIZING OURSELVES HADN’T KEPT.  (Compare complicated cells with a lot of organelles but not enough structure in the different types of cells.)
    - Recognising: e.g., “happy Hannuka” and not schedule a category theory meeting on a high holiday
- You come along to the monthly meeting and someone raises an issue about project /X/ — it then becomes part of what each project /S/ needs to do to provide such an interface.
  - I don’t know but go to Charlotte to talk about the podcast.
  - We could look at the health metrics of each ‘subproject’ (‘subchannel’)

* Ongoing PAR of the Top level summary!
** 1. Review the intention: what do we expect to learn or make together?
- Present some ‘poetic’ peeragogy progress, and ‘a way in’ to everthing we have to offer
- Try to get a full draft of this document to Charlie for revision
** 2. Establish what is happening: what and how are we learning?
#+begin_quote
C-c R P C       org-scrum-board-peeragogy-course
C-c R P H       org-scrum-board-peeragogy-handbook
C-c R P J       org-scrum-board-peeragogy-project
C-c R P P       org-scrum-board-peeragogy-podcast
C-c R P R       org-scrum-board-peeragogy-paper
C-c R P W       org-scrum-board-peeragogy-website/technology — Or rather should become different technologies
C-c R P Y       org-scrum-board-peeragogy-community
#+end_quote
- Rough drafts here in Org Mode
- Pairing to look at some of these sections on 1st Saturday
- People are excluded “by default” — and no matter what we’re using some people are excluded
  - We never had an ‘inclusive platform’ that was productive and working well
  - At no point was it solving the problems that we want to solve, but we did have “one project at a time where everyone was involved at some level”
  - Now we have 4 project areas or so — not everyone needs to be involved in every aspect of the project
- Something similar also applies to other collaborations (like keeping up to date with research in other loosely linked projects)
  - For peeragogy maybe we need a number of separate meetings in addition to the /quarterly meetings/
    - You don’t need everyone going to every meeting but you need /monthly/ meetings to check-points communicating across
** 3. What are some different perspectives on what’s happening?
- Starting with this top-level summary and revising it together could be a good way forward
** 4. What did we learn or change?
- Bringing voice into the mix changed the contents for the better
** 5. What else should we change going forward?
*** STAR [#A] Keep patternizing the rest of the handbook          :handbook:
*** BACK Keep working over the comments from the Reading Group    :handbook:
*** BACK Describe the new pattern "SPREAD TASKS THIN NOT PEOPLE"   :project:
*** STAR [#A] Work some more on the ‘poem’ version of the handbook  :handbook:
*** BACK Once the Top document is ready move it to the front page  :website:
- It’s intelligent not to have any upcoming meeting info
- We don’t even know where to go if you are interested
- Pay attention to the /elegance of organisation/ — are ready for people or not?

