#+TITLE: Top
#+roam_tags: AN

* Tippy Top

The /Peeragogy Handbook/ is both a (very large!) /design pattern/ as well as a /pattern language/.

That is to say: the book describes a (complex) solution to a problem
in a context, and it also built out of interlinked patterns that
smaller and more detailed solutions to constituent problems, in their
own particular contexts.

** What is the Peeragogy design pattern?

- How can we learn and adapt to the challenges we face as human beings?
- We put learning and adaptation at the forefront of our minds.
- That’s a first approximation of what ‘culture’ is: we want to work together to understand and use it better.

That’s all you need to know to know what peeragogy ‘is’.  But all three of these components unfold in practice.

- The [[file:problem.org][Problem]] posed by learning and adaptation is hard to do and may even seem impossible.
- Articulating a [[file:solution.org][Solution]] to this problem based on collaboration can be complicated, confusing, and personally challenging (but, also, rewarding).
- The [[file:context.org][Context]] in which this problem applies — offers some evidence that solutions we’ve spotted (and in some cases helped develop) seem to work.

* [[file:peeragogy.org][Peeragogy]]

#+begin_quote
How do /we/ improve at learning, adapting, growing, aging, engaging?

We do that when we to pay attention to their dynamics.

This accelerates when we work together.
#+end_quote

** [[file:problem.org][Problem]]
#+begin_quote
How to do you decide what to learn or engage with or do?  Sometimes there are clear incentives.  Sometimes it’s fun.  Sometimes it’s way less clear.

In reasonably stable society, if you go a little out of the box that’s permitted. Even laws are how society learns over time.

The thing is, significant change and creativity only ever happens in the real world, where we’re subject to the pressure of being effective.
#+end_quote

** [[file:solution.org][Solution]]

#+begin_quote
The problem we consider here is the same one Spinoza talked about: the problem of human freedom.

The solution we’ve found relates to engagement in understanding the process of learning and creativity.

Things can be empowered or disempowered socially: we write and think about the forms of organisation that empower people.
#+end_quote

*** [[file:convene.org][Convening]]
#+begin_quote
When you first start thinking about a problem it can be hard to wrap your mind around it.

If you get in touch with other people who are thinking about similar things that can contextualise your thinking.

Others will have seen different aspects of the problem: they don’t see exactly what you see.
#+end_quote
**** [[file:newcomer.org][Newcomer]]
#+begin_quote
Newcomers can feel overwhelmed by the amount of things to learn.

Instead of thinking of newcomers as "them", and trying to provide solutions, we focus on newcomers as "us".

When there's learning happening, it's because there is someone who is new to a topic, or to something about the topic.
#+end_quote
**** [[file:specific.org][A specific project]]
#+begin_quote
It's easy to think about issues that matter: there are many of them.

If you /are/ able to get concrete about something to do, learn, and achieve, you move from thinking about a topic to becoming a practitioner.

You find yourself interested in or concerned about something, but you only have a vague idea about how it works or how you fit in.
#+end_quote
** [[file:context.org][Context]]
#+begin_quote
The bigger challenge is always: to manifest meaningful relationships.

That happens through communication.

And always within a bigger context.
#+end_quote
*** [[file:the_peeragogy_project.org][The Peeragogy Project]]
#+begin_quote
The Peeragogy project is just one of the contexts in which ‘peeragogy’ happens.

The project has been going since 2011.

It’s driven by volunteers who are interested in understanding peer learning and peer production better to apply it in their own contexts.
#+end_quote
**** [[file:project.org][Project]]                                                      :handbook:
#+begin_quote
Since we have been at it for quite a while we have a lot of data on how things have been going, but maybe not yet such a clear sense of where it’s going.

In order to get anywhere we need to keep apprised of all of our resources; as well as whether and how they are sustained.

In any enterprise it makes sense to be careful to ‘spread tasks thin, not people’.
#+end_quote
**** [[file:website.org][Website]]                                                      :handbook:
#+begin_quote
The key informatic challenges are those of accessing and interacting with information

This means that when we write we’re not only posting updates but also working to make the material a two way street (or multi-way roadmap!)

Our project exists in a context of readers, viewers, contributors, and others who might want to interact with our materials
#+end_quote
**** [[file:course.org][Course]]                                                       :handbook:
#+begin_quote
It’s not peeragogy unless it’s collaborative: simultaneously, we can’t expect people to “get it” unless we co-create opportunities to “do with us”.

A set of interactive exercises that help people wrap their hearts and minds around peeragogy can help us understand if it’s working.

In the context of ‘education’ this may be a renegade activity; in workplace cultures, open learning may also be unfamiliar. But peeragogy thrives in open source settings!
#+end_quote
**** [[file:podcast.org][Podcast]]                                                      :handbook:
#+begin_quote
Helping us understand what we actually have to offer

A series of structured discussions

People who have interesting things to say
#+end_quote
**** [[file:paper.org][Paper]] pattern                                                :handbook:
#+begin_quote
Developing thinking along a number of complex and somewhat novel directions

Write one or more academic papers to a high standard, suitable for discussing with specialists

With specialist topics there are discipline-specific communities who are ready to discuss and give feedback
#+end_quote
**** [[file:community.org][Community]] pattern                                            :handbook:
#+begin_quote
We can’t expect everyone who has interesting this to say to come on our podcast; besides, they might have more to teach us in context

Interact with some other communities on their home turf and report back

Groups of a certain size with somewhat porous boundaries
#+end_quote
**** [[file:handbook.org][Handbook]] pattern                                             :handbook:
#+begin_quote
Can we create a common ground for people to engage with?

Writing gives us something concrete to do in collaboration

It’s one reasonably accessible way for us to get started organizing contents and contributors
#+end_quote
*** [[file:technologies.org][Technologies]]
#+begin_quote
How we approach technologies makes a big difference: do we think of them simply as tools to use, or as material that we can bend to meet our needs?

Becoming empowered to use and work with technology comes especially from disciplined practice: a form of apprenticeship.

Technologies are part of our the modern landscape, their nature is to be put to use, whether for good or for ill, or a mixture of the two.
#+end_quote
**** BACK [[file:forums.org][Forums]] pattern                                          :handbook:
**** BACK [[file:wiki.org][Wiki]] pattern                                            :handbook:
**** BACK [[file:realtime.org][Realtime]] pattern                                        :handbook:
**** BACK [[file:social-bookmarking.org][Social Bookmarking]] pattern                              :handbook:
**** BACK [[file:connectivism.org][Connectivism]] pattern                                    :handbook:
*** [[file:cases.org][Case Studies]]
#+begin_quote
If we want to learn about peeragogy, we need to amass a collection of different cases in which it actually happens.

The ‘unit of analysis’ is social in nature, and the method of analysis is through patterns.

Peeragogy can happen anywhere people come together: in education, the workplace, or communities.
#+end_quote
**** BACK [[file:swats.org][SWATS]] pattern + analysis                                :handbook:
**** BACK [[file:5ph1nx.org][5PH1NX]] pattern + analysis                               :handbook:
**** BACK [[file:a_meeting_with_the_pro_vice_chancellor.org][A meeting with the Pro Vice-Chancellor]] pattern + analysis :handbook:
**** BACK [[file:sole.org][SOLE]] pattern + analysis                                 :handbook:
**** BACK [[file:collab-ex.org][Collaborative Explorations]] pattern + analysis           :handbook:
**** BACK [[file:action.org][Peeragogy in action]] pattern + analysis                  :handbook:
**** BACK [[file:coworking-story.org][Coworking Story]] pattern + analysis                      :handbook:

* Ongoing PAR of the Top level summary!
** 1. Review the intention: what do we expect to learn or make together?
- Present some ‘poetic’ peeragogy progress, and ‘a way in’ to everthing we have to offer
** 2. Establish what is happening: what and how are we learning?
- Rough drafts here in Org Mode
- Pairing to look at some of these sections on 1st Saturday
** 3. What are some different perspectives on what’s happening?
- Starting with this top-level summary and revising it together could be a good way forward
** 4. What did we learn or change?
- Bringing voice into the mix changed the contents for the better
** 5. What else should we change going forward?
*** BACK Keep patternizing the rest of the handbook               :handbook:
*** BACK Keep working over the comments from the Reading Group    :handbook:
*** BACK Describe the new pattern "SPREAD TASKS THIN NOT PEOPLE"   :project:
*** TODO [#A] Work some more on the ‘poem’ version of the handbook  :handbook:
