#+title: Website
#+roam_tags: SUB

#+begin_quote
The key informatic challenges are those of accessing and interacting with information

This means that when we write we’re not only posting updates but also working to make the material a two way street (or multi-way roadmap!)

Our project exists in a context of readers, viewers, contributors, and others who might want to interact with our materials
#+end_quote

Our main website is =peeragogy.org= — but because the contents are
public domain, anyone has the right to make their own website, and we
also have a bunch of different things spread out in different areas.

The website itself (and all the other online bits and pieces) could be
better maintained.

* Next steps

- For now “website” is [[https://peeragogy.org/tags][one of the tags]] used on peeragogy.org, but it should probably develop into its own pattern.

** BACK Correlation of project sub-contexts with Quickstart Guide  :website:

The quickstart guide features the following links.  /How do they map to
the project subcontexts we’re working in?/ With any given context this
should have something to do with “next steps” — i.e., as places to
engage or interact.  How do these places — /Community, Website, Course,
Paper, Podcast, Project Miscellany, and Handbook/ — correspond (if at
all) to our idea of the project as analogous to ‘university’?

1. Podcast playlist: https://www.youtube.com/playlist?list=PLG6fmEnfJR2yaWGiK0tSp8QSis4btdCzE
2. Google group: https://groups.google.com/forum/#!forum/peeragogy
3. Peeragogy Handbook Mailman mailing list: https://lists.osuosl.org/mailman/listinfo/peeragogy-handbook
4. Public events listing: https://calendar.google.com/calendar/embed?src=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com
5. Google Calendar: https://www.google.com/calendar/render?cid=3iq41odpn85s51mem8cgekmong%40group.calendar.google.com
6. =.ics= link: https://calendar.google.com/calendar/ical/3iq41odpn85s51mem8cgekmong%40group.calendar.google.com/public/basic.ics
7. Hypothesis: https://hypothes.is/
8. Website Comments: https://hypothes.is/search?q=url%3Apeeragogy.org%2F*
9. Github Organization: https://github.com/Peeragogy
10. Sources for peeragogy.org https://github.com/Peeragogy/Peeragogy.github.io
11. Intro to Emacs, Org Mode, and Git: https://github.com/PeeragogyLabs/PeeragogyORG/wiki
