#+TITLE: Emergent roadmap
#+FIRN_ORDER: 58

  Collecting the "What's Next" steps from the previous patterns, here's
  our current "distributed roadmap" for the Peeragogy project.

* Carrying Capacity:
     :PROPERTIES:
     :CUSTOM_ID: carrying-capacity
     :END:

This pattern catalog has been rewritten in a way that should make it
easy for anyone to add new patterns. Making it easy and fruitful for
others to get involved is one of the best ways to redistribute the load
(compare the Newcomer pattern).

* Creating A Guide:
     :PROPERTIES:
     :CUSTOM_ID: creating-a-guide
     :END:

We've been talking with collaborators in the Commons Abundance Network
about how to make a Pattern Language for the Commons. One of the
challenges that arises is how to support ongoing development of the
Pattern Language itself: a "living" map for a living territory. We're
refining the Peeragogy Pattern language and template as a seed for this.

* Discerning A Pattern:
     :PROPERTIES:
     :CUSTOM_ID: discerning-a-pattern
     :END:

What do the patterns we've observed say about the self-selection
processes of the group? For instance, it's possible that a widespread
interest in organic gardening, say, may indicate the participants are
oriented to cooperation, personal health, or environmental activism.
What can we learn about the Peeragogy project from our collected
patterns?

* Heartbeat:
     :PROPERTIES:
     :CUSTOM_ID: heartbeat
     :END:

When the project is bigger than more than just a few people, it's likely
you'll get several heartbeats -- for instance, we've recently been
running two weekly meetings in the Peeragogy project, for members with
slightly different interests and slightly different availability.
Finding ways to communicate across these different "camps" is useful.

* Isolation:
     :PROPERTIES:
     :CUSTOM_ID: isolation
     :END:

We recently submitted an abstract called "Escape from Peeragogy Island"
to a geography conference talking about the spatiality of peer
production. The idea behind this article is that we feel like we've come
up with something great with the Peeragogy project, but we're going to
be a bit isolated if it's not transparently useful to others. If we
can't explain why it's a great idea, then it's not entirely clear how
great of an idea it actually is.

* Magical Thinking:
     :PROPERTIES:
     :CUSTOM_ID: magical-thinking
     :END:

Fast-forwarding a few years from the DIY Math experiment: as part of the
PlanetMath project, we are hoping to build a well-thought-through
example of a peer learning space for mathematics. One of the ideas we're
exploring is to use patterns and antipatterns (exactly like the ones in
this catalog) as a way not only of designing a learning space, but also
of talking about the difficulties that people frequently run into when
studying mathematics. Building an initial collection of Calculus
Patterns may help give people the guide-posts they need to start
effectively self-organizing.

* Messy With Lurkers:
     :PROPERTIES:
     :CUSTOM_ID: messy-with-lurkers
     :END:

What comes out of thinking about the anti-pattern is that we need to be
careful about how we think about "virtues" in a peer production setting.
It is not just a question of being a "good contributor" to an existing
project, but of continually improving the methods that this project uses
to make meaning.

* Misunderstanding Power:
     :PROPERTIES:
     :CUSTOM_ID: misunderstanding-power
     :END:

As Paul Graham wrote about programming languages -- programmers are
typically "satisfied with whatever language they happen to use, because
it dictates the way they think about programs" -- so too are people
often "satisfied" with their social environments, because these tend to
dictate the way they think and act in life. Nevertheless, if we put our
minds to it, we can become more "literate" in the patterns that make up
our world and the ways we can effect change.

* Moderation:
     :PROPERTIES:
     :CUSTOM_ID: moderation
     :END:

We recently ran a Paragogical Action Review to elicit feedback from
participants in the Peeragogy project. Some of them brought up
dissatisfactions, and some of them brought up confusion. Can we find
ways to bring these concerns front-and-center, without embarrassing the
people who brought them up?

* Navel Gazing:
     :PROPERTIES:
     :CUSTOM_ID: navel-gazing
     :END:

We have hinted that, in this project, effective criticism is very
welcome! But understanding what makes criticism effective is, in
general, still a research problem.

* Newcomer:
     :PROPERTIES:
     :CUSTOM_ID: newcomer
     :END:

We recently revised the "How to Get Involved" page, listing the top ten
sites we use. Another reasonable thing to post would be a top-ten list
of activities, so that people can get an easier view on the kinds of
things we do in the project.

* Polling For Ideas:
     :PROPERTIES:
     :CUSTOM_ID: polling-for-ideas
     :END:

We've considered asking new members of the project to do an "entry
survey" as part of joining the project, to describe their aims and
understanding of what they hope to contribute. This could establish a
context of contribution, and help new members to feel like full "peers".

* Praxis Vs Poeisis:
     :PROPERTIES:
     :CUSTOM_ID: praxis-vs-poeisis
     :END:

"Platform" debates can be frustrating but can also add something to a
project in the long term, since they help people become aware of their
priorities. As mentioned in the Newcomer pattern, developing a more
clear picture of the activities that we engage in in the project will
help make it comprehensible to others. It will also be useful for us to
have a clearer picture of what we do, and what we make.

* Roadmap:
     :PROPERTIES:
     :CUSTOM_ID: roadmap
     :END:

Adding "What's Next" steps to our patterns gives us a "distributed
roadmap." And this works both ways: If we sense that something needs to
change about the project, that's a clue that we might need to record a
new pattern.

* Roles:
     :PROPERTIES:
     :CUSTOM_ID: roles
     :END:

We've listed some of the roles for which we're seeking volunteers in the
Peeragogy.org Roadmap: Volunteer Coordinator, Seminar Coordinator,
Usability Guru, Activities Master, and Tech lead. As with everything
else in the roadmap, this list should be reviewed and revised regularly,
as the roles are understood relative to the actual happenings in the
Peeragogy project.

* Specific Project:
     :PROPERTIES:
     :CUSTOM_ID: specific-project
     :END:

In the third year of the Peeragogy project, rather than just keep
working on the handbook, we've been working on building a Peeragogy
Accelerator, as a peer support system for projects related to peer
learning and peer production. Not only does specificity help member
projects, being clear about what the Accelerator itself is supposed to
do will help people get involved.

* Stasis:
     :PROPERTIES:
     :CUSTOM_ID: stasis
     :END:

We're working on a new handbook chapter about the relationship of open
source software and peeragogy. This will include some more specific
ideas about ways of making change.

* Stuck:
     :PROPERTIES:
     :CUSTOM_ID: stuck
     :END:

If we are actively engaging with other people, then this is a foundation
for strong ties. In this case of deep learning, our aims are neither
instrumental nor informational, but "interactional". Incidentally, the
"One of us" quoted above has been one of the most consistently engaged
peeragogues over the years of the project. Showing up is a good step --
you can always help someone else move their washing machine!

* Wrapper:
     :PROPERTIES:
     :CUSTOM_ID: wrapper
     :END:

We need better practices for wrapping things up at various levels. One
of the latest ideas is to develop a simple visual "dashboard" for the
project.
