#+TITLE: Wiki
#+FIRN_ORDER: 37

#+BEGIN_QUOTE
  In the context of P2P-learning, a wiki platform can be a useful and
  powerful collaboration tool. This section will help you understand
  what a wiki is and what it is not, why you should use it, how to
  choose a wiki engine and finally how you could use it in a P2P
  context. Some examples of P2P-learning projects run on wikis will help
  you see the potential of the tool.
#+END_QUOTE

* What is a wiki?
   :PROPERTIES:
   :CUSTOM_ID: what-is-a-wiki
   :END:

For [[http://en.wikipedia.org/wiki/Ward_cunningham][Ward Cunningham]]
father of the wiki, "a wiki is a freely expandable collection of
interlinked Web 'pages', a hypertext system for storing and modifying
information - a database, where each page is easily editable by any user
with a forms-capable Web browser client" [1].

According to Wikipedia : "a wiki is a website whose users can add,
modify, or delete its content via a web browser using a simplified
markup language or a rich-text editor" [2].

You can watch the CommonCraft video
[[http://www.youtube.com/watch?v=-dnL00TdmLY]["Wikis in Plain English"]]
on YouTube to better understand what a wiki is.

* What differentiates the wiki from other co-editing tools?
   :PROPERTIES:
   :CUSTOM_ID: what-differentiates-the-wiki-from-other-co-editing-tools
   :END:

The previous definitions show that a wiki is a "website," in other words
it is composed of pages that are connected together by hyperlinks. In
addition, every authorized person (not all wikis are totally open like
Wikipedia) can edit the pages from a web browser, reducing time and
space constraints. In case one saves a mistake, or for any other reason,
would like to go back to a previous version, a feature called "history"
allows users to see previous versions and to roll back to any of them.
This version history allows a comparison of versions that avoids the
clutter of the "commentaries rainbow" that we are used to in popular
word processors. For example, if you work on a wiki page and come back
later, you will be able to catch up by comparing your latest version
with the lastest version generated by someone else.

Tools like [[https://docs.google.com/][Google Docs]] or
[[http://en.wikipedia.org/wiki/Etherpad][Etherpad]] are design to enable
co-editing on a single document. This can be seen as a "wiki way" of
working on a document as it is web based and includes versioning. But it
is not a wiki because a single document is not a website. Those tools
offer realtime collaboration which wikis do not and are far easier for
beginners to use as they work in
[[http://en.wikipedia.org/wiki/WYSIWYG][WYSIWYG]] mode, which many wikis
do not support. However, the advanced features of the
[[http://en.wikipedia.org/wiki/Wiki_syntax][wiki markup language]] make
it a more powerful tool. In summary, tools like Googles Docs or Etherpad
are a great way to quickly collaborate (synchronously, asynchronously,
or a mixture of both) on a single document for free, with a low barrier
to entry and no technical support. (Note that Etherpad does have a
"wiki-links" plugin that can allow it to be used in a more wiki-like
way; [[https://hackpad.com/][Hackpad]] is another real-time editing tool
that prominently features linking -- and it claims to be "the best wiki
ever".)

Using a real wiki engine is more interesting for bigger projects and
allows a huge number of users to collaborate on the same platform. A
wiki reduces the coordination complication as e-mails exchanges are no
more needed to coordinate a project. On the other hand it can help us
deal with complexity ([3], [4]) especially if you put basic simple rules
in place like the Wikipedia's
[[http://en.wikipedia.org/wiki/NPOV][neutral point of view]] to allow
every participant to share her or his ideas.

Going back to the continuum we talked about before, some tools like
Moodle, SharePoint, WordPress, Drupal and others have built-in wiki
features. Those features can be good but will typically not be as good
for wiki-building purposes as a well-developed special-purpose wiki
engine. In other words, the main focus of those tools is not the wiki,
which is only a secondary feature. When you choose a real wiki engine
like [[http://www.mediawiki.org/][Mediawiki]],
[[http://www.tiki.org/][Tiki]], [[http://foswiki.org/][Foswiki]], etc.,
the wiki will be your platform, not a feature of it. For example if you
start a wiki activity in a Moodle course, this wiki will be only visible
to a specific group of students and searchable only to those students.
On the other hand if your learning platform is a wiki, the whole
platform will be searchable to all members regarding their permissions.
We are not saying here that a wiki is better than other tools but if you
need a wiki engine to address your needs you may consider going with a
strong wiki engine rather than a "micro-wiki" engine embedded in an
other tool.

* Why use a wiki?
   :PROPERTIES:
   :CUSTOM_ID: why-use-a-wiki
   :END:

Those are the main reasons you should consider a wiki for your peer
learning projects :

- To reduce cumbersome coordination issues by having a central and
  continually updated place to store your content. You will reduce
  e-mail usage drastically, and have access to your content from
  anywhere, using any operating system.
- To keep track of the evolution of your project and be able to view or
  roll back any previous version of a wiki page using the history
  feature.
- To make links between wiki pages to connect ideas and people but also
  make links to external URL's. This last possibility is very handy to
  cite your sources.
- To deal with complexity. As a wiki allows anyone to contribute, if you
  set some easy rules like Wikipedia's NPOV (Neutral Point of View), you
  will be able to catch more complexity as you will allow everyone to
  express his or her opinion. Wikis also integrate a forum or comment
  feature that will help you solve editing conflicts.
- To deal with work in progress. A wiki is a great tool to capture an
  ongoing work.
- To support transparency by letting every member of the community see
  what all the others are doing.
- To support a network structure; as a wiki is in essence a horizontal
  tool.

Using a hyperlinks you can...

#+BEGIN_QUOTE
  *Gérard Ayache*: "... jump by a single click from one network node to
  another, from one computer to another, from one bit of information to
  the other, from one universe to another, from one brain to another." 
  (Translated from [5].)
#+END_QUOTE

* How to choose a wiki engine?
   :PROPERTIES:
   :CUSTOM_ID: how-to-choose-a-wiki-engine
   :END:

You will find more than a hundred different wiki engines.

The first main distinction is between open source ones that are free to
download and commercial ones you will have to pay for. You will find
powerful engines on both sides, both open-source and commercial.
Sometimes, the open-source ones look less polished at first sight, but
are backed by a strong community and offer a range of customization
possibilities. The commercial wiki engines are sold as a package, nicely
presented but often offering less customization on the user side.
Additional features or custom-made tools will cost you extra.

The second distinction that we can make is between wiki farms and
self-hosted wikis. The
[[http://en.wikipedia.org/wiki/Wiki_hosting_service][wiki farm]] is a
hosting service you can find for both open-source or commercial wikis.
The goal of those farms is to simplify the hosting of individual wikis.
If you don't want to choose wiki farm hosting, you will have to host the
wiki on your own server. This will give you more latitude and data
privacy but will require more technical skills and maintenance fees.

The [[http://www.wikimatrix.org/][Wikimatrix]] web site will help you
choose the best wiki for your needs. It allows you to compare the
features of more than a hundred wiki engines. Ward Cunningham's list of
the top 10 best wiki engines can be found on our
[[http://c2.com/cgi/wiki?TopTenWikiEngines][Peeragogy.org]] site.

* How can a wiki be useful in a peeragogy project?
   :PROPERTIES:
   :CUSTOM_ID: how-can-a-wiki-be-useful-in-a-peeragogy-project
   :END:

A wiki is a good tool for collaborative projects and especially suited
for work in progress, as you can easily track changes using the history,
compare those versions and, if necessary, roll back to previous
versions. In other words, nothing gets lost.

Here are some ideas about how to use a wiki in a peeragogy project :

- *Use a wiki as your learning platform*. It can also
  support [[http://socialmediaclassroom.com/host/peeragogy/wiki/connectivism-practice-how-organize-a-mooc][Massive
  Open Online Courses (MOOCs)]]. A wiki will help you organize your
  [[http://socialmediaclassroom.com/host/peeragogy/wiki/organizing-a-learning-context][learning
  context]]. You can choose to give access to your wiki only to the
  project participants or open it to the public
  like [[http://www.wikipedia.org/][Wikipedia]]. Using hyperlinking, you
  will operationalize the theory
  of [[http://en.wikipedia.org/wiki/Connectivism][connectivism]] by
  connecting nodes together. As a learning platform, wikis are powerful
  because you can easily see what others are doing, share with them, get
  inspired, merge ideas or link to ideas. In other words, it fosters
  emulation between learners. For additional resources about wikis in
  education, look on
  [[http://www.diigo.com/user/regisb/wiki%20education][Diigo]].
- *Manage your peeragogy project*. A wiki is an excellent tool for
  project collaboration. Above all, the wiki can be a central place for
  peer learners to write or link to content. Even if you use several
  technologies to run your project as we did to write this handbook, at
  the end of the day all the content can be centralized on a wiki using
  direct writing on wiki pages or embedding hyperlinks. This way,
  members can access the content from anywhere and from any device
  connected to the internet, using any platform or application. They
  will always see the most recent version while being able to browse
  through the version history to understand what has changed since their
  last visit.
- *Publish your project*. As a wiki is a website you can easily use it
  to show your work to the world. Regarding web design, don't forget
  that a wiki can look way better than a Wikipedia page if you customize
  it

* Examples of peeragogy projects run on wikis
   :PROPERTIES:
   :CUSTOM_ID: examples-of-peeragogy-projects-run-on-wikis
   :END:

[[http://www.appropedia.org/Welcome_to_Appropedia][Appropedia]] is a
wiki site for collaborative solutions
in [[http://www.appropedia.org/Sustainability][sustainability]], [[http://www.appropedia.org/Poverty][poverty]] reduction
and [[http://www.appropedia.org/International_development][international
development]] through the use of
sound [[http://www.appropedia.org/Principles][principles]] and [[http://www.appropedia.org/Appropriate_technology][appropriate
technology]] and the sharing of wisdom and
[[http://www.appropedia.org/Project][project]] information. The site is
open to stakeholders to find, create and improve scalable and adaptable
solutions.

[[http://en.wikipedia.org/wiki/Wikipedia:Teahouse][Teahouse]] is a
peeragogy project run on a wiki that gives newcomers a place to learn
about Wikipedia culture and get feedback from experienced Wikipedians.

* What are the best practices when using a wiki?
   :PROPERTIES:
   :CUSTOM_ID: what-are-the-best-practices-when-using-a-wiki
   :END:

- *Cofacilitation* -- help each other learn, help each other administer
- *Self-election* -- enable people to choose what they want to work on,
  at their own pace, in their own way
- *Communication* -- use comment threads and talk pages to discuss wiki
  changes
- *Documenting changes* -- most wikis enable editors to write very brief
  descriptions of their edits
- *Rules* -- keep rules at a minimum level to avoid chaos without
  constraining creativity
- *Fun* -- make it fun for people to contribute

* References
   :PROPERTIES:
   :CUSTOM_ID: references
   :END:

1. Leuf, Bo, et Ward, Cunningham. 2001. The Wiki way : quick
   collaboration on the Web. Boston: Addison-Wesley, xxiii, 435 p. p.14

2. [[http://en.wikipedia.org/wiki/Wiki][Wiki]] on Wikipedia

3. Andrus, Calvin D. 2005. [[http://ssrn.com/abstract=755904][Toward a
   complex adaptative intelligence community - The wiki and the blog]].
   Studies in Intelligence. vol. 49, no 3. Online :

4. Barondeau, Régis.
   2010. [[http://www.regisbarondeau.com/Chapitre+4%3A+Analyse+du+cas#Synth_se][La
   gestion de projet croise le wiki]]. École des Sciences de la Gestion,
   Université du Québec à Montréal, 180 pp.

5. Ayache, Gérard. 2008. Homo sapiens 2.0 : introduction à une histoire
   naturelle de l'hyperinformation. Paris: Milo, 284 p. p.179

