#+TITLE: Workscape
#+FIRN_ORDER: 29

Cultivating a results-oriented peer-learning program in a corporate
learning ecosystem involves a few tweaks of the approach and tools we
discussed in relation to more open, diverse networks.

** The Workscape, a platform for learning
   :PROPERTIES:
   :CUSTOM_ID: the-workscape-a-platform-for-learning
   :END:

Formal learning takes place in classrooms; informal learning happens in
/workscapes./ A workscape is a learning ecosystem. As the environment of
learning, a workscape includes the workplace. In fact, a workscape has
no boundaries. No two workscapes are alike. Your workscape may include
being coached on giving effective presentations, calling the help desk
for an explanation, and researching an industry on the Net. My workscape
could include participating in a community of field technicians, looking
things up on a search engine, and living in France for three months.
Developing a platform to support informal learning is analogous to
landscaping a garden. A major component of informal learning is natural
learning, the notion of treating people as organisms in nature. People
are free-range learners. Our role is to protect their environment,
provide nutrients for growth, and let nature take its course. A
landscape designer's goal is to conceptualize a harmonious, unified,
pleasing garden that makes the most of the site at hand. A workscape
designer's goal is to create a learning environment that increases the
organization's longevity and health and the individual's happiness and
well-being. Gardeners don't control plants; managers don't control
people. Gardeners and managers have influence but not absolute
authority. They can't make a plant fit into the landscape or a person
fit into a team. In an ideal Workscape, workers can easily find the
people and information they need, learning is fluid and new ideas flow
freely, corporate citizens live and work by the organization's values,
people know the best way to get things done, workers spend more time
creating value than handling exceptions, and everyone finds their work
challenging and fulfilling.

** The technical infrastructure of the Workscape
   :PROPERTIES:
   :CUSTOM_ID: the-technical-infrastructure-of-the-workscape
   :END:

When an organization is improving its Workscape, looking at consumer
applications is a good way to think about what's required. Ask net-savvy
younger workers how they would like to learn new skills, and they bring
up the features they enjoy in other services:

- Personalize my experience and make recommendations, like Amazon.
- Make it easy for me to connect with friends, like Facebook.
- Keep me in touch with colleagues and associates in other companies, as
  on LinkedIn.
- Persistent reputations, as at eBay, so you can trust who you're
  collaborating with.
- Multiple access options, like a bank that offers access by ATM, the
  Web, phone, or human tellers.
- Don't overload me. Let me learn from YouTube, an FAQ, or linking to an
  expert.
- Show me what's hot, like Reddit, Digg, MetaFilter, or Fark do.
- Give me single sign-on, like using my Facebook profile to access
  multiple applications.
- Let me choose and subscribe to streams of information I'm interested
  in, like BoingBoing, LifeHacker or Huffpost.
- Provide a single, simple, all-in-one interface, like that provided by
  Google for search.
- Help me learn from a community of kindred spirits, like SlashDot,
  Reddit, and MetaFilter.
- Give me a way to voice my opinions and show my personality, as on my
  blog.
- Show me what others are interested in, as with social bookmarks like
  Diigo and Delicious.
- Make it easy to share photos and video, as on Flickr and YouTube.
- Leverage "the wisdom of crowds," as when I pose a question to my
  followers on Twitter or Facebook.
- Enable users to rate content, like "Favoriting" an item on Facebook or
  +!ing is on Google or YouTube.

Some of those consumer applications are simple to replicate in-house.
Others are not. You can't afford to replicate Facebook or Google behind
your firewall. That said, there are lots of applications you can
implement at a reasonable cost. Be skeptical if your collaborative
infrastructure doesn't include these minimal functions:

*Profiles* - for locating and contacting people with the right skills
and background. Profile should contain photo, position, location, email
address, expertise (tagged so it's searchable). IBM's Blue Pages
profiles include how to reach you (noting whether you're online now),
reporting chain (boss, boss's boss, etc.), link to your blog and
bookmarks, people in your network, links to documents you frequently
share, members of your network.

*Activity stream* - for monitoring the organization pulse in real time,
sharing what you're doing, being referred to useful information, asking
for help, accelerating the flow of news and information, and keeping up
with change

*Wikis* - for writing collaboratively, eliminating multiple versions of
documents, keeping information out in the open, eliminating unnecessary
email, and sharing responsibility for updates and error correction

*Virtual meetings* - to make it easy to meet online. Minimum feature
set: shared screen, shared white board, text chat, video of
participants. Bonus features: persistent meeting room (your office
online), avatars.

*Blogs* - for narrating your work, maintaining your digital reputation,
recording accomplishments, documenting expert knowledge, showing people
what you're up to so they can help out

*Bookmarks* - to facilitate searching for links to information, discover
what sources other people are following, locate experts

*Mobile access* - Half of America's workforce sometimes works away from
the office. Smart phones are surpassing PCs for connecting to networks
for access and participation. Phones post more Tweets than computers.
Google designs its apps for mobile devices before porting them to PCs.

*Social network* - for online conversation, connecting with people, and
all of the above functions.

** Conclusion
   :PROPERTIES:
   :CUSTOM_ID: conclusion
   :END:

Learning used to focus on what was in an individual's head. The
individual took the test, got the degree, or earned the certificate. The
new learning focuses on what it takes to do the job right. The workplace
is an open-book exam. What worker doesn't have a cell phone and an
Internet connection? Using personal information pipelines to get help
from colleagues and the Internet to access the world's information is
encouraged. Besides, it's probably the team that must perform, not a
single individual.  Thirty years ago, three-quarters of what a worker
need to do the job was stored in her head; now it's less than 10%.  

