name: Firn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download firn
        run: curl -s https://raw.githubusercontent.com/theiceshelf/firn/master/install -o install-firn
      - name: Install firn
        run: chmod +x install-firn && sudo ./install-firn
      - name: Print working directory
        run: pwd
      - name: List contents
        run: find /home/runner/work/PeeragogyORG/PeeragogyORG/src
      - name: Build with firn
        run: firn build -d /home/runner/work/PeeragogyORG/PeeragogyORG/src
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: |
                src/_firn/_site/
                src/_firn/_site/static

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: docs
